### ISSUE TITLE
WebRTC transport support

### ISSUE THREAD

**Issue by ivelin** [w3c/webtransport#102]
Currently the [WebRTC section](https://github.com/WICG/web-transport/blob/6c9cbf26870723a5c6e4a5131691b876fbb7b281/explainer.md#webrtc-data-channel) implies that WebRTC is designed for different use cases than what Web Transport targets.

I would like to suggest a discussion on this topic. There is a large class of use cases related to accessing edge devices hosted behind firewall from a web app. Convenient http like transport over WebRTC makes it a lot easier to build such apps without expert knowledge of peer-to-peer communications. A few representative examples:
* [Private Home Surveillance with the WebRTC DataChannel](https://webrtchacks.com/private-home-surveillance-with-the-webrtc-datachannel/)
* [WebTorrent](https://webtorrent.io/)
* [ShareDrop.io](https://www.sharedrop.io/)
* [Snowflake pluggable WebRTC Transport](https://github.com/keroserene/snowflake)
* [Strive](https://docs.strivetech.io/flink_ott_platform/basics/webrtc/)
* [Pi.pe](https://pi.pe/)

**Comment by lgrahl** [comment]
I think the explainer is largely focussing on the aspect that

> [WebRTC is] a complex API designed for a very different use case

Which I agree is definitely not correct. IMO, it should say that WebRTC **1.0** is a complex high-level API whose scope is beyond data transmission whereas WebTransport is low-level and only targets data transmission.

That being said, AFAICT the P2P part of WebTransport is still very much a wish list because there's nothing in the spec so far that does anything like ICE.

**Comment by aboba** [comment]
@lgrahl There is a separate specification for P2P that leverages WebTransport and ICE:
https://w3c.github.io/webrtc-quic/

**Comment by jianjunz** [comment]
WebTransport and QUIC API for Peer-to-peer Connections(webrtc-quic) could be the potential solution for a couple of [WebRTC NV requirements](https://www.w3.org/TR/webrtc-nv-use-cases/#requirements*)(N11-N14, N17-N19). Not sure if WebTransport/webrtc-quic + WebCodecs will be considered as parts of WebRTC NV.

For WebRTC 1.0, webrtc-quic just sounds like an alternative of SCTP data channel.

**Comment by lgrahl** [comment]
@aboba Makes sense. Since that is built on top of WebTransport, I think the *WebRTC Data Channel* section of the explainer should just be removed altogether. If anything, it should be in the explainer of webrtc-quic.

**Comment by ivelin** [comment]
@lgrahl  & @aboba Thank you for the comments. Do you know what would be the correct place to take the discussion regarding browser fetch() API implementation over WebRTC Datachannel? It is clear that Web Transport is lower level API, but it is not clear what is the right level of abstraction below fetch and above WebRTC Datachannel.

**Comment by aboba** [comment]
@lgrahl The reference to WebRTC data channel is there because `RTCDataChannel` is actually being used as a client/server transport in cloud gaming services such as [parsec](https://parsecgaming.com/game-streaming-technology/).

**Comment by jan-ivar** [comment]
Peer-to-peer is out of scope of the [WebTransport charter](https://www.w3.org/2020/09/webtransport-wg-charter.html#Scope). Please consider opening an issue with the WebRTC WG.
