### ISSUE TITLE
arrayBuffer() should leave the stream locked

### ISSUE THREAD

**Issue by ricea** [w3c/webtransport#104]
For consistency with [Response arrayBuffer()](https://fetch.spec.whatwg.org/#concept-body-consume-body), IncomingStream arrayBuffer() should leave the stream locked after it has finished reading.

**Comment by vasilvv** [comment]
Discussed at the meeting today.  The conclusion is that we should not implement arrayBuffer() in the IncomingStream, and instead make sure that there is a uniform way to do .arrayBuffer()/.text()/.json() on any readably stream.  Currently, `new Response(stream).arrayBuffer()` is a way to do that, but it's unclear if it has same performance properties; if not, we should address that (on spec and/or implementation level as appropriate).

**Comment by jan-ivar** [comment]
See also https://github.com/whatwg/streams/issues/1019

**Comment by jan-ivar** [comment]
Consensus to remove the `incomingStream.arrayBuffer()`
