### ISSUE TITLE
Fallback support

### ISSUE THREAD

**Issue by aboba** [w3c/webtransport#107]
If QUIC is not available what happens? Does the WebTransport constructor return an error?  That's what happens in the current implementation. Or can a fallback transport be invoked?  What if some functionality is not available (e.g. no datagram support)? 

In general, the specification needs to be more clear about fallback (e.g. whether it is transparent or up to the application to handle).

Related: Issue https://github.com/w3c/webtransport/issues/164

**Comment by ekinnear** [comment]
Agreed that it needs to be more clear about fallback. I think we'd discussed the desire to have a fallback with the understanding that QUIC is not going to be available on all networks. That aligns well with work in other areas where we've seen that fallback to TCP-based protocols is workable, if not as nice as using QUIC -- and is certainly better than not having any connectivity for _most_ use cases.

**Comment by jan-ivar** [comment]
Based in the most recent IETF meeting, it sounds like fallback is coming back into favor. If fallback is left to web developers, the concern is a large number of them will settle on the lowest common denominator, e.g. some websocket-like calback-based API in a js library.

At the same time, apps would need to learn what they got. This might look like something like this:
```js
await transport.ready;
if (transport.mode = "http2") 
```

**Comment by aboba** [comment]
At IETF 110, we also discussed an optional argument in the constructor to indicate "QUIC only", so if the application would prefer to fail rather than fallback to HTTP/2, it can request that.

**Comment by vasilvv** [comment]
I'm not sure if checking a specific transport is a good idea, since that's not future proof.  We should instead allow querying for properties, e.g. "are datagrams unreliable".

**Comment by jan-ivar** [comment]
Agree. Also, pardon my ignorance, but when do we know QUIC is not available? E.g. should this be a static method, or does it depend on the server?

**Comment by aboba** [comment]
At the May 20, 2021 IETF WEBTRANS WG meeting, there was support for WebTransport over HTTP/2.  Meeting minutes, slides, etc. are [here](https://datatracker.ietf.org/meeting/interim-2021-webtrans-02/session/webtrans).

**Comment by yutakahirano** [comment]
I think this is out of Minimum Viable Product.

**Comment by jan-ivar** [comment]
Meeting:
- Enums are good. But location should be higher. Maybe `wt.reliability` = new | reliable | unreliable ?
- If you don't want it you write `if (wt.reliability != "unreliable") wt.close()` ? Too costly?
  - new hostname, you attempt toconnect using QUIC, host doesn't support or can't detect, it fails, then you fall back to H2.
  - User didn't want to waste time negotiation the H2 fallback.
  - So maybe declarative `new WebTransport({unreliableOnly})` in new issue?
