### ISSUE TITLE
Add compile step

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/webtransport#108]
Seems the generated spec and .bs file keeping falling out of sync. 

@cwilso, do you know how to set up the magic to keep them in sync through TravisCI?

**Comment by aboba** [comment]
This is causing problems because PRs that result in errors aren't being flagged prior to merge.

**Comment by aboba** [comment]
@dontcallmedom Any tips on integrating bikeshed with TravisCI?

**Comment by yutakahirano** [comment]
And if possible I'd love to have a preview system (e.g., https://github.com/whatwg/fetch/pull/1000).

**Comment by aboba** [comment]
@dontcallmedom Do we need to add Github actions in .github/workflows to handle validation and auto-publishing?

**Comment by dontcallmedom** [comment]
to get the preview system, you just need to add a [`.pr-preview.json` file](https://github.com/tobie/pr-preview#configuration-file) at the root of the repository

to get the bikeshed document automatically compiled, I think you would want to use two branches, one of the raw .bs, one for the compiled doc, and use https://github.com/w3c/spec-prod to have the second one automated (e.g. with https://github.com/w3c/spec-prod/blob/main/docs/examples.md#deploy-to-github-pages). Paging @ylafon as staff contact

**Comment by jan-ivar** [comment]
Closed as done.

**Comment by aboba** [comment]
Done.
