### ISSUE TITLE
Promise resolving/rejection unless done "synchronously" needs to happen from a task

### ISSUE THREAD

**Issue by annevk** [w3c/webtransport#112]
All communication between "threads" goes through tasks. (There was a suggestion for a while resolving a promise would implicitly queue a task, but that's no longer true.)

**Comment by jan-ivar** [comment]
@annevk I think we've got them all now, unless you see one. Can we close it or did you have a particular line in mind?

**Comment by ricea** [comment]
https://www.w3.org/TR/webtransport/#initialize-webtransport-over-http runs "in parallel" after step 3 and resolves a promise in step 11.

https://www.w3.org/TR/webtransport/#dom-webtransport-getstats also has this problem.

**Comment by yutakahirano** [comment]
Let me own this.

**Comment by annevk** [comment]
You want to upgrade to use "queue a global task" while you're at it.

**Comment by yutakahirano** [comment]
Yes, I'm proposing a shorthand at #274 and planning to use it.
