### ISSUE TITLE
extends EventTarget

### ISSUE THREAD

**Issue by Jxck** [w3c/webtransport#116]
WebTransport mixin or, QuicTransport/Http3Transport seems to be EventTarget.
I think WebTransport has onstatechange, so this should be

```diff
- interface mixin WebTransport {
+ interface mixin WebTransport: EventTarget {
```

seems fine.

**Comment by yutakahirano** [comment]
Actually I would like to remove onstatechange. Please see #92. The discussion has not been settled yet.

**Comment by yutakahirano** [comment]
We don't need this as we removed `.onstatechange` (see #292).
