### ISSUE TITLE
Relation to HTTP3, "upgrades"?

### ISSUE THREAD

**Issue by alexhultman-2fa** [w3c/webtransport#118]
Hello,

I thought I would ask this because I've read for a few hours and can't find a clear explanation.

If a browser uses the QuickTransport APIs to connect to a server, will that server have to implement HTTP3 and "upgrade" from HTTP3 to "QuickTransport", or is QuickTransport entirely and separately compatible with "raw" QUICK? Does QuickTransport in the browser equal QUICK on the server, so to speak?

In other words; could I take any QUICK-implementation and use that implementation and communicate with a modern web browser without having to implement any HTTP3, HTTP2 or HTTP1 whatsoever?

Comparing with WebSockets, in order to get a WebSocket connection you first have to send an HTTP upgrade request which means the server has to support HTTP (to some degree). There's no straight-to-WebSocket but you first need to have a working HTTP stack to get there.

I'm interested because I want to assess the work needed to support such an API.

Thanks

**Comment by alexhultman-2fa** [comment]
Okay I found a link to the draft that explains this from looking at the code of the Python implementation: https://tools.ietf.org/html/draft-vvv-webtransport-quic-01

Essentially, I understand it as QuickTransport is a thin protocol that builds on top of QUICK. They are not 1-to-1 but quite close. There should be no HTTP3 involved as I understand it.

**Comment by vasilvv** [comment]
> Essentially, I understand it as QuickTransport is a thin protocol that builds on top of QUICK. They are not 1-to-1 but quite close. There should be no HTTP3 involved as I understand it.

That's a good summary, and yes, the name is confusing (that's a known issue, we'd probably have to fix that at some point).

For the origin trial, we're experimenting with QuicTransport as described in the linked draft.  Longer term, we're currently debating (in IETF) whether the correct solution is to use the current approach or build a protocol on top of HTTP/3.

**Comment by jan-ivar** [comment]
> will that server have to implement HTTP3

With https://github.com/w3c/webtransport/issues/183 the answer is yes.
