### ISSUE TITLE
Should we expose stream reset codes to JavaScript?

### ISSUE THREAD

**Issue by vasilvv** [w3c/webtransport#123]
For QuicTransport, exposing it is trivial: since we own all of the reset code error space, we can do a 1-to-1 mapping.

For HttpTransport, it's less obvious since HTTP/2 and HTTP/3 have their own error codes.  We would have to figure something out there.

Given all of that (and also the fact that if we're not sufficiently generic, we may have problems adding new transports down the road), should we expose the ability to send/receive stream error codes?  WebSocket does have custom connection error codes that web developers do use, but it's not an exact equivalence (connection error vs stream error).

**Comment by wilaw** [comment]
@vasilvv  - is this covered by #213 ?

**Comment by yutakahirano** [comment]
@vasilvv - is this covered by #213 ?

**Comment by vasilvv** [comment]
Yes.
