### ISSUE TITLE
QuicTransport consider exposing stream ids 

### ISSUE THREAD

**Issue by npurushe** [w3c/webtransport#124]
For our particular use case of streaming media we need to know the ordering of different incoming streams. In our native implementation we used QUIC stream ids for this purpose and would like to do the same using `QuicTransport` on the web. Looks like this was removed as part of #74 but there could be other application level use cases for having access to the stream ids.

**Comment by LPardue** [comment]
This isn't strictly QuicTransport related but in H3, having the ability to determine the order that the client sent the requests in is a very useful capability. It is implemented via observing stream ID. On the receiver side, if for any reason the presentation of streams is ordered differently than how they were sent, the application can still use stream ID to determine the actual order.

**Comment by vasilvv** [comment]
I guess the main question I would ask is: do those have to be "real" IDs, as in, do those have to match on client and server, or is it only the ordering that is important?

QuicTransport, with its direct immediate connection, makes exposing matching IDs easy.  If we're doing any sort of pooling or proxying, it's fairly easy to get into a situation where the IDs end up not matching on different sides.  One way to address it is to make some sort of local stream numbering that preserves order but is not necessarily 1:1 with actual stream IDs.  If you use IDs in certain other ways (e.g. using them to reference data on one stream from another), we'd obviously have to come up with a scheme that keeps numbering consistent across proxies.

**Comment by LPardue** [comment]
Oooh that is a fun conundrum, if there are multiple QUIC connections at play it will be hard to determine the absolute send ordering across them.

**Comment by npurushe** [comment]
For our use case they wouldn’t have to be the actual stream ids a local id would suffice, its more the ordering that is important.

**Comment by kixelated** [comment]
As @LPardue mentioned, I think the stream ID is used in HTTP/3 in a few minor ways. It would be a minor disappointment if you couldn't fully implement HTTP/3 on top of QuicTransport.

In my opinion, exposing the low-level QUIC ID is confusing because of the encoding. For example, stream ID 3 may or may not have been created earlier than stream ID 1448. It's on the application to know that the low 2 bits are the stream type and the rest are the stream id for that corresponding type. This should be a tuple in Javascript at least.

If the only goal is to get the order of stream creation, then it should be enough to guarantee that `receiveStreams` returns streams in ID order. It would be pretty simple to use a counter to determine the creation order of streams of the same type.

**Comment by LPardue** [comment]
QUIC transport [draft 29 Section 3.2 ](https://tools.ietf.org/html/draft-ietf-quic-transport-29#section-3.2) says the following about receiver handling of streams:

> Before a stream is created, all streams of the same type with lower-
   numbered stream IDs MUST be created.  This ensures that the creation
   order for streams is consistent on both endpoints.

So using your example, stream ID 1448 is always created after 3. 

The question for the API is, if there is network reordering and stream ID 1448 is the first received stream, does `receiveStreams` return all valid streams between 0 and 1448. If not, then your counting risks getting broken.

**Comment by vasilvv** [comment]
> So using your example, stream ID 1448 is always created after 3.

I think that's only true if streams IDs are equal mod 4.

**Comment by LPardue** [comment]
ah yes got my maths messed up :D

**Comment by kixelated** [comment]
Case and point. 😃

And I love that passage in the QUIC RFC. We would know the stream order if QuicTransport maintained the same behavior.

**Comment by yutakahirano** [comment]
This idea has been abondoned.

Stream ID is per hop, so the client and the server may see different IDs for a stream.
