### ISSUE TITLE
Add web-platform-tests

### ISSUE THREAD

**Issue by yutakahirano** [w3c/webtransport#125]
@Hexcles's and I have introduced the QuicTransport server in https://github.com/web-platform-tests/wpt/. Please see https://github.com/web-platform-tests/wpt/tree/master/tools/quic. 

This is not enabled by default as of now. The most important roadblock is to finalize the server API design, and get consensus among the working/community group. We also need write a [wpt/RFC](https://github.com/web-platform-tests/rfcs/blob/master/README.md) describing the system and workflow.

Are y'all happy with the introduced system? Do you have any questions/comments?

**Comment by yutakahirano** [comment]
@annevk @youennf Do you have any opinions? Do you know people who have interest in Mozilla/Apple?

**Comment by annevk** [comment]
@ddragana, @agrover, and @jan-ivar can probably give input here.

**Comment by yutakahirano** [comment]
@ddragana, @agrover, @jan-ivar, @youennf do you have any opinions?

**Comment by annevk** [comment]
FWIW, I heard things are still in the early stages design-wise, so making progress in the standards group on that is probably more productive at this point.

**Comment by yutakahirano** [comment]
I think now is a good timing to start thinking about this more seriously. While writing tests too early is not a very good use of time, we have a prototype of the API, and making it testable helps us design it in more detail (e.g., #95).

Please see https://github.com/web-platform-tests/wpt/tree/master/tools/quic for the handlers.
https://github.com/web-platform-tests/wpt/blob/master/webtransport/quic/handlers/client-indication.quic.py is an example handler and https://github.com/web-platform-tests/wpt/blob/master/webtransport/quic/client-indication.sub.any.js uses it.

**Comment by jan-ivar** [comment]
Notes from WebTransport Wednesday:

* We're limited today wrt picking between server libraries, AIO Quic python library is available, updated frequently, and supports data grams.
* **Consensus** to proceed with a WPT server, will revisit in 6 months/1 year available server options at that time.
* Run tests for both transports.
* Most cases should be ambivalent to whether we use http or quic
* API remains sufficiently generic.
* Avoid tests specific to one transport or another at the moment

**Comment by yutakahirano** [comment]
@bashi has started a discussion at https://github.com/web-platform-tests/rfcs/pull/85. Feel free to jump in.

**Comment by jan-ivar** [comment]
Meeting:
-Chrome team is leading the task of creating the first deliverable which is an echo server.

**Comment by jan-ivar** [comment]
@yutakahirano What are next steps on this? Is there any update or anything we need to discuss at next meeting?

**Comment by bashi** [comment]
We have a [PR](https://github.com/web-platform-tests/wpt/pull/29727) to add the test server and a test. The PR is under review. I think we need some follow-up PRs to run the test in wpt.fyi. We also need some integrations with Chromium code base to run the server and tests.

**Comment by yutakahirano** [comment]
bashi@ wrote [a document](https://docs.google.com/document/d/1OBoZTcC9vDoLTgv_5WUznRFrmwXP0Gprj7V9oOzH9cU/edit) decribing how to enable the WebTransport over HTTP/3 servre on your local environment. Thank you!

**Comment by jan-ivar** [comment]
To be updated with links to web-platform-tests from [this spreadsheet](https://docs.google.com/spreadsheets/d/12li_cbmfkqAd0PS1upVY3m6ZSL-Nw2oH2qgZmvuaz2Q/edit#gid=778678726).

**Comment by jan-ivar** [comment]
Yes, WPT tests are up and running at https://wpt.fyi/webtransport. 🎉

Individual issues should be opened for any subsequent tests, and we should use the `Needs test` label for future spec changing PRs.

**Comment by dontcallmedom** [comment]
Shouldn't the instructions in https://docs.google.com/document/d/1OBoZTcC9vDoLTgv_5WUznRFrmwXP0Gprj7V9oOzH9cU/edit be included somewhere directly in the repo?
