### ISSUE TITLE
Zero copy support via BYOB (add an example)

### ISSUE THREAD

**Issue by aboba** [w3c/webtransport#131]
QUIC implementations such as [quant ](https://github.com/NTAP/quant) support zero-copy (via [warpcore](https://github.com/NTAP/warpcore)).  Via BYOB, zero-copy should be feasible for both readable and [writable streams](https://github.com/whatwg/streams/issues/495).

So it seems to me that zero-copy should be feasible in WebTransport via BYOB, in which case some examples should be provided to show how it works.

**Comment by DavidSchinazi** [comment]
Can you clarify what data exactly should not be copied and when? Our QUIC implementation lives in a different process from where JavaScript runs, so a copy will be necessary for security reasons.

**Comment by yutakahirano** [comment]
With Chromium implementation BYOB doesn't reduce copy but it does reduce the number of allocations, the pressure for the GC system and the peak memory usage.

The allocation CPU cost is real, from our experience in WebSocket.

**Comment by aboba** [comment]
Going over the current state of browser implementations, a WebTransport application using WebAssembly and Workers may require as many as a dozen memory copies on both the sending and receiving side.   There are copies for send and receive (C++/JS), for use of WebAssembly, as well as for use of data within a Transferrable Stream.

**Comment by yutakahirano** [comment]
Could you elaborate on a bit more please? We, the Streams API team in Google, want to help people write efficient applications by providing good APIs and implementation. cc:@ricea @domenic

**Comment by aboba** [comment]
One of the scenarios for WebTransport + WebCodecs is realtime communications in which portions of the pipeline (such as packetization or machine learning) are handled in WebAssembly. Currently, it appears that copies may exist at every stage in the pipeline (e.g. capture, machine learning, encode, packetization, send, receive, de-packetization, decode, more machine learning, render).  Several of these copies represent additional overhead not present in WebRTC (e.g. no additional copies for packetization/de-packetization).  This isn't solely a WebTransport problem; some of these copies are being worked on (support for zero-copy capture and zero-copy rasterization), some are due to [WASM](https://github.com/whatwg/streams/issues/495).

**Comment by aboba** [comment]
Is BYOB supported currently?  If I try this, last line produces an error. 

`let new_stream = transport.incomingUnidirectionalStreams.getReader();
const {value, done } = await new_stream.read();
let reader = value.getReader({mode: "byob"});`

**Comment by jianjunz** [comment]
BYOB support for WebTransport streams was merged just 10 days ago.

https://chromium-review.googlesource.com/c/chromium/src/+/3799089

**Comment by aboba** [comment]
Thanks! Will check it out in Canary.

**Comment by aboba** [comment]
@jianjunz Trying it out in M108, seems to be working very well.  Thank you!

**Comment by jianjunz** [comment]
Thanks for your feedback. BYOB support for datagrams ([CL](https://chromium-review.googlesource.com/c/chromium/src/+/3886069)) is not merged yet. One concern from Adam is it will lose the datagram boundaries. Feel free to add your comments if you have. Thanks.

**Comment by jan-ivar** [comment]
The streams spec has a [byob example](https://streams.spec.whatwg.org/#example-manual-read-bytes) we might want to crib.

**Comment by aboba** [comment]
I have included BYOB in the WebCodecs Echo sample (requires M108+).

**Comment by jan-ivar** [comment]
Once #487 is merged, we have BYOB for both datagrams and regular streams. So now's a good time to add some examples to show how it works.

**Comment by erights** [comment]
> With Chromium implementation BYOB doesn't reduce copy ...

Would proposed [Immutable ArrayBuffers](https://github.com/tc39/proposal-immutable-arraybuffer) help?

**Comment by domenic** [comment]
> Would proposed [Immutable ArrayBuffers](https://github.com/tc39/proposal-immutable-arraybuffer) help?

I believe no; IIRC, the Chromium copy comes from moving between different processes. (Namely, the network service process, where the bytes come off the wire, and the renderer process, where the JS engine lives.)

**Comment by erights** [comment]
Hi @domenic , thanks for the clear answer! I updated the list on the proposal with a link to your comment.

**Comment by erights** [comment]
Hi @domenic , What do you think of the point made at https://github.com/tc39/proposal-immutable-arraybuffer/issues/30#issuecomment-2652223749

> - Even when talking between different processes, each with their own address space, for a huge enough buffer it will be cheaper `O(logN)` to map it into both address spaces than to copy it `O(N)`. IOW, zero-copy even between address spaces.

**Comment by domenic** [comment]
That sounds pretty cool, but it's getting beyond my expertise to tell whether it's feasible to implement. My suspicion is that it's technically possible, but lift to make our generic IPC code use mechanisms like that (including deep integration into the JS engine's ArrayBuffer internals) would not pass the cost-benefit analysis.

I see you're already discussing with @syg; @ricea is another person who might have more insight than me.
