### ISSUE TITLE
Do we need QuicTransport when we have Http3Transport?

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webtransport#148]
Currently, the [constructor](https://w3c.github.io/webtransport/#webtransport-constructor) accepts two url schemes: `"quic-transport"` and `"https"`.

It seems to us that this will depend on which transport protocols the IETF eventually decides to actually standardize (QuicTransport and/or Http3Transport) and how they will interact with origin policy. cc @ddragana

Since Http3Transport runs over QUIC and adds support for pooling, why do we still need QuicTransport?

I noticed the use cases [spreadsheet](https://docs.google.com/spreadsheets/d/1Hsu_uYfFCvTUE3cYA7tofr78p178gxWQKQLPHXONdRM) has two extra columns since I [snapshoted](https://docs.google.com/presentation/d/1xx1MLjxY-ZiWQBxivJCITmvKrHdW3AMuz-DxDOrAcdw/edit#slide=id.g9c4aac119f_1_0) it into the slides a few days ago. @aboba did you add those? If so, could you clarify why the last column "Http3Transport" is missing a lot of ✅? - My understanding was that Http3Transport can do anything QuicTransport can.

**Comment by wilaw** [comment]
Here's a slide with a comparison - I believe this comes originally from Victor's IETF presentation.

![image](https://user-images.githubusercontent.com/2762250/96655285-f1517d80-12f1-11eb-8458-87da47fda929.png)

@jan-ivar  -  I was the one who added the extra columns to the my spreadsheet. I populated them based on feedback received during the use-cases presentation to the IETF.

**Comment by jan-ivar** [comment]
I believe this is still an open topic at the IETF, based on misc threads over the last few months in https://mailarchive.ietf.org/arch/browse/webtransport/ so I don't see both being standardized as a foregone conclusion.

Even if the IETF ends up standardizing both, we'll have a decision to make about what makes most sense to expose in browsers.

My understanding is an Http3Transport would be attached to an HTTP Connection but would present both raw datagram and raw streams interfaces, suggesting it can do everything QuicTransport can.

The debate around keeping QuicTransport seems more about: easier to implement server-side, vs. we already have H3 load balancers and don’t want to implement quic load balancers in front of it.

Since ✅s normally compare features across columns (e.g. Turbotax Premium will have the same ✅s as Turbotax Basic and more), I think we should present it that way if that's the case here.

@vasilvv can you expound on "Server can optimize" and "more stats"? Can we not get the same stats from Http3Transport?

**Comment by jan-ivar** [comment]
And sorry @aboba for attributing that to you.

**Comment by aboba** [comment]
I'd suggest that it's necessary to go through the use cases and think about their needs carefully.  For example, if a given use case would benefit from HTTP/3, we can consider whether it needs Http3Transport, or could be implemented with only HTTP/3.  For example, conventional streaming video (which today uses HLS or DASH) may not be motivated to adopt Http3Transport. Use cases which can be either client/server and P2P (such as Remote Desktop) will typically not want to use different transports for each mode, nor will they want to implement an HTTP/3 server on the client, so they may prefer QuicTransport.

**Comment by jan-ivar** [comment]
> Use cases which can be either client/server and P2P (such as Remote Desktop) will typically not want to use different transports for each mode, nor will they want to implement an HTTP/3 server on the client

Why would transports being the same matter to clients if the API surface is similar? Note p2p is out of scope in our [charter](https://www.w3.org/2020/09/webtransport-wg-charter.html#Scope).

**Comment by murillo128** [comment]
you may have native clients which are not browser based.

**Comment by jan-ivar** [comment]
WebTransport TPAC meeting notes:
* **ACTION** Will: Create a `usecases.md` document to edit and improve, to try to answer transport needs.
* Schedule an upcoming meeting to go over these use cases in more detail, and produce this feedback to IETF.

**Comment by aboba** [comment]
IETF WebTransport WG has consensus to focus on Http3Transport.  Should we remove references to QuicTransport in the API specification? However, until we have an Http3Transport implementation, it would seem premature to remove the QuicTransport tests.

**Comment by jan-ivar** [comment]
> Should we remove references to QuicTransport in the API specification?

I believe we said yes yesterday in https://github.com/w3c/webtransport/issues/183#issuecomment-772117691.

> However, until we have an Http3Transport implementation, it would seem premature to remove the QuicTransport tests.

Agree. I believe they test a common subset, so we should hopefully be able to make due until we have another implementation.
