### ISSUE TITLE
problem in testing maximum datagram sending speed

### ISSUE THREAD

**Issue by xujiasci** [w3c/webtransport#152]
I want to test the maximum datagram sending speed when using quic in web application, so I made an quic echo server and using the following script as client . here is the sending part.
```    
try {
        DatagramWriter = transport.sendDatagrams().getWriter();
        //await DatagramWriter.ready;
        startMill = (new Date()).getTime();
        var ii = 0;
        while (state != "stop" && ii++ < total) {
            let numdrawData = send_seq + rawData;
            numdrawData = numdrawData.substring(0, size);
            let data = encoder.encode(numdrawData);
            record[send_seq] = [(new Date()).getTime(), 0];
            await DatagramWriter.ready;
            DatagramWriter.write(data);
            send_seq++;
        }
    }
```
But it seems that a lot of packets event hasn`t being sent out. I wonder if it is casued by the sending buffer limit, Quic will drop some application data as the they are lost in the transmitting. How should I correct this ?

**Comment by xujiasci** [comment]
I suppose that when DatagramWriter.ready is resolved, the transport should actually have the ability to send my data using datagram frame, not drop them silently. And I will receive echo datagram from server, only not if the packet contain this frame has beening droped by the net.

**Comment by xujiasci** [comment]
When DatagramWriter.ready is rejected, I will get the reason it is caused by connection things or too much data.

**Comment by ricea** [comment]
> I suppose that when DatagramWriter.ready is resolved, the transport should actually have the ability to send my data using datagram frame, not drop them silently. And I will receive echo datagram from server, only not if the packet contain this frame has beening droped by the net.

I think your expectation is reasonable, but that's not how it currently works. Depending on the resolution of #93, it may work that way in future.

For now, you can wait for `transport.ready` before trying to send any datagrams.

The Chrome implementation currently drops more datagrams than is necessary. I expect to change it to have a certain amount of backpressure on the datagrams in future.

**Comment by jan-ivar** [comment]
This sounds like a Chrome issue. Sending datagrams is now [well-defined in the spec](https://w3c.github.io/webtransport/#writedatagrams) and does offer (sender-side) back pressure to producers of data to ensure a balance between throughput and timeliness with https://github.com/w3c/webtransport/pull/267.

**Comment by xujiasci** [comment]
@yutakahirano Hello, I'm a little confused about all your discussing, can you give me an example about the right way to use webtransport datagram, if I don't want any packet droped by browser. Looking forward to your reply.

**Comment by xujiasci** [comment]
It seems that the folloing code didn't work. I set a big number for each attributes by purpose. When I using a while loop to send 1000 * 1024B data, about 30% data are droped by browser.
```
 transport = new WebTransport(url);
 transport.datagrams.incomingMaxAge = 10000;
 transport.datagrams.outgoingMaxAge = 10000;
 transport.datagrams.incomingHighWaterMark = 10000;
 transport.datagrams.outgoingHighWaterMark = 10000;
  // transport.datagrams.writable.maxAge = 10000;
  // transport.datagrams.readable.maxAge = 10000;
  DatagramWriter = transport.datagrams.writable.getWriter();
```

**Comment by yutakahirano** [comment]
> @yutakahirano Hello, I'm a little confused about all your discussing, can you give me an example about the right way to use webtransport datagram, if I don't want any packet droped by browser. Looking forward to your reply.

Are you using [writer.ready](https://streams.spec.whatwg.org/#default-writer-ready)?
The "best" depends on requirements so there is no one best way, but the following code may be reasonable.

```js
const datagrams = ...;

datagrams.outgoingMaxAge = ...;

const writable = datgrams.writable;
const writer = writable.getWriter();
for (const datagram of datagrams) {
  await writer.ready;
  writer.write(datagram);
}
```
