### ISSUE TITLE
Datagrams always supported?

### ISSUE THREAD

**Issue by aboba** [w3c/webtransport#164]
Is it possible for a Webtransport object to be successfully constructed if datagrams are not supported in both directions? 

Related: Issue https://github.com/w3c/webtransport/issues/107

**Comment by ricea** [comment]
Currently there's no transport that doesn't support datagrams, so it's not an issue. How I'd like it to work is that datagrams are always supported, but over HTTP/2 they are emulated with unidirectional streams, and there's an attribute to tell you whether they are truly unreliable or not.

**Comment by aboba** [comment]
draft-vvv-webtransport-quic Section 5 says: 

"A QuicTransport endpoint MUST negotiate and support the DATAGRAM frame.  The datagrams provided by the application are sent as-is."

draft-vvv-webtransport-http3 Section 4.1 says: 

"If "http3_transport_support" is negotiated, support for the QUIC DATAGRAM extension MUST be negotiated."

draft-ietf-quic-datagram Section 3 says: 

"Support for receiving the DATAGRAM frame types is advertised by means  of a QUIC Transport Parameter (name=max_datagram_frame_size, value=0x0020)...   The max_datagram_frame_size transport parameter is a unidirectional
 limit and indication of support of DATAGRAM frames.  Application protocols that use DATAGRAM frames MAY choose to only negotiate and use them in a single direction."

[BA] The language could be more clear in draft-vvv-webtransport-quic and draft-vvv-webtransport-http3. 

It seems that the intent is for DATAGRAM support to always be advertised and negotiated in both directions. The client will always send the max_datagram_frame_size Transport Parameter, and if the server does not receive it, the connection will not be established. Similarly, if the client does not receive the max_datagram_frame_size Transport Parameter, then the WebTransport constructor will fail. This way, if the WebTransport constructor succeeds, the datagramReadable and datagramWritable attributes will always be defined, for either QuicTransport or Http3Transport.

This would seem to imply that failover to HTTP/2 is outside the scope of the WebTransport API. If failover to HTTP/2 can occur within the API, then it would be possible for the datagramReadable and datagramWritable attributes to be undefined, even if the WebTransport constructor succeeds (but only if an https:// URL is provided to the constructor).

**Comment by martinthomson** [comment]
We've discussed this several times and concluded that yes, we would insist on datagram support being present always.

**Comment by jan-ivar** [comment]
Is there anything left to do here, or can we close this?

**Comment by martinthomson** [comment]
The IETF working group needs to know, but they are on the hook here.  But [that seems to be OK](https://tools.ietf.org/html/draft-vvv-webtransport-http3-02#section-4.1).

**Comment by aboba** [comment]
I think we can close the issue. The WebTransport constructor currently initializes both the  [[ReceivedDatagrams]] and [[SentDatagrams]] internal slots, which is consistent with datagram support always being present. Just wanted to check if this was everyone's understanding.
