### ISSUE TITLE
Make transport.datagram a duplex stream?

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webtransport#181]
The streams spec defines a [duplex stream](https://streams.spec.whatwg.org/#other-specs-duplex) as a [`{readable, writable}`](https://streams.spec.whatwg.org/#example-both) pair. In light of that, would the following change be more ergonomic?
```js
-   const writer = transport.datagramWritable.getWriter();
+   const writer = transport.datagrams.writable.getWriter();

-   transport.datagramReadable.pipeTo(sink);
+   transport.datagrams.readable.pipeTo(sink);
```

This would allow [clever things](https://jsfiddle.net/jib1/uxeyrvk8/) like piping through a server processing step ([polyfill](https://jan-ivar.github.io/polyfills/datagrams.js)):
```js
new InputBox()
  .pipeThrough(new TextEncoderStream("utf-8"))
  .pipeThrough(transport.datagrams)
  .pipeThrough(new TextDecoderStream("utf-8"))
  .pipeTo(new WritableConsole());
```

**Comment by yutakahirano** [comment]
Sounds reasonable.

**Comment by jan-ivar** [comment]
I guess it should also be `datagrams` plural.

**Comment by aboba** [comment]
Using duplex streams has implications. From the [WHATWG Streams specification Section 9.4.1](https://streams.spec.whatwg.org/#other-specs-duplex): 

"The trickiest thing to consider when specifying duplex streams is how to handle operations like canceling the readable side, or closing or aborting the writable side. It might make sense to leave duplex streams "half open", with such operations one one side not impacting the other side. Or it might be best to carry over their effects to the other side, e.g. by specifying that your readable side’s cancelAlgorithm will close the writable side."

**Comment by jan-ivar** [comment]
Once we figure out https://github.com/w3c/webtransport/issues/197, I'd think _"half open"_ would make sense, since we can't assume all datagrams are request-response. This is also the behavior unless we specify something.
