### ISSUE TITLE
Call the streams algorithms

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webtransport#185]
The streams spec has a [Using streams in other specifications](https://streams.spec.whatwg.org/#other-specs) section with algorithms we're meant to call. But we don't appear to be calling them. We should probably do that.

We seem light on algorithms to describe the fundamentals someone would need to get right to implement this web compatibly: threading model, timing, type checking, and error handling, which I'm unable to glean from current prose.

Coming from WebRTC, I'd assume networking requires a similar model to that: data I/O largely off main thread, doing a lot of "in parallel" and queued tasks to communicate with (main or worker) JS. https://github.com/w3c/webtransport/issues/112

This came to mind while I was reviewing unrelated streams patches over in https://github.com/w3c/webrtc-insertable-streams/pull/51#discussion_r567910473

Similar to that patch, once we start calling the streams algorithms directly, this should unfurl how to answer these questions.

**Comment by jan-ivar** [comment]
Work seems to be happening in #266 for this. Closing.

**Comment by yutakahirano** [comment]
Reopening as we have more things to do here.
