### ISSUE TITLE
Rename 'master' branch to 'main' at W3C request

### ISSUE THREAD

**Issue by wilaw** [w3c/webtransport#186]
Dear Chairs,

The message was sent to team contacts for them to work on migrating the
'master' branches on GitHub.

If your Group is still using this branch name, you should expect to hear
from your team contacts in the upcoming weeks.

Thank you,

Philippe

[[

we'd like W3C to stop using the name 'master' for the GitHub branches by
the April 2021 AC meeting.

Dom added the repositories that are still using this name in one of
our reports:

https://urldefense.com/v3/__https://w3c.github.io/validate-repos/report.html?grouptype=workinggroup&filter=defaultbranchismaster__;!!GjvTz_vk!Br0rgtz1ZpGY1geB9af0Iu93M3nObS3xIR4_U1gHkNC_0A5hdXI2eyGnCuaD$
(this report is updated every 6 hours)

We recommend pre-announcing the move before doing so, so that anyone who
would have local copy, e.g. WG participants, will be alerted. See
Atsushi announcement to Immersive Web:

https://urldefense.com/v3/__https://lists.w3.org/Archives/Public/public-immersive-web-wg/2021Jan/0004.html__;!!GjvTz_vk!Br0rgtz1ZpGY1geB9af0Iu93M3nObS3xIR4_U1gHkNC_0A5hdXI2ey2yckxj$

You'll need to start by renaming the branch on the server (github.com)
side. See later in this message on how you can do that but make sure
to read this message entirely before starting any action. We recommend
using 'main'. This whole process could take from 2 minutes to a lot more
(if you're using CI, etc.).

Now, before you go and renaming things, understand the following 2
actions will need to be taken after the renaming is done:

1- if you are using some CI integration, those may rely on the branch
name 'master'. Check your .travis.yml, github actions, scripts, respec
config, etc and
update appropriately. I recommend looking for the keyword 'master' to
track those down, eg
https://urldefense.com/v3/__https://github.com/w3c/ttml2/search?q=master__;!!GjvTz_vk!Br0rgtz1ZpGY1geB9af0Iu93M3nObS3xIR4_U1gHkNC_0A5hdXI2e-GU3mg3$

2- local copies of the repositories (yours and WG participants) will
need an action as well:

https://urldefense.com/v3/__https://docs.github.com/en/github/administering-a-repository/renaming-a-branch*updating-a-local-clone-after-a-branch-name-changes__;Iw!!GjvTz_vk!Br0rgtz1ZpGY1geB9af0Iu93M3nObS3xIR4_U1gHkNC_0A5hdXI2e3KQIE8i$

Denis also provided:
[[
$ git checkout master
$ git branch -m master main
$ git fetch
$ git branch --unset-upstream
$ git branch -u origin/main
$ git symbolic-ref refs/remotes/origin/HEAD refs/remotes/origin/main
]]

  If you make sure that you don't have pending things on your side, an
easier way is to delete your local copy and clone the repositories.

To rename the branch in the repository on Github.com, you go into the
settings of your
repo, select "Branches", and you'll find the way to rename the branch
there. See also
  https://urldefense.com/v3/__https://github.com/github/renaming__;!!GjvTz_vk!Br0rgtz1ZpGY1geB9af0Iu93M3nObS3xIR4_U1gHkNC_0A5hdXI2e93TPrJ-$

Make sure things work as expected afterwards, including the github.io
URLs (GH may not
regenerate properly)

If you need assistance, please ask on the IRC channel #git,

Thank you,

Philippe

**Comment by martinthomson** [comment]
The `.github/workflows/pr-push.yml` file mentions the branch, but this should be trivial otherwise.

**Comment by martinthomson** [comment]
People who have clones can either re-clone or do this:

```sh
git branch -m master main
git fetch
git branch -u origin/main main
git symbolic-ref refs/remotes/origin/HEAD refs/remotes/origin/main
```

**Comment by wilaw** [comment]
Done. Also updated `.github/workflows/pr-push.yml `to use main instead of master.
Leaving open to allow any unintended consequences to be reported.
