### ISSUE TITLE
Specify how the underlying datagram queue should work

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webtransport#187]

**Comment by aboba** [comment]
Do we have a set of requirements for datagram queue management? For example, with a WebTransport writer, does backpressure from the receiver somehow propagate back to a datagram sender as it would for a reliable stream?

**Comment by jan-ivar** [comment]
> Are we restricting ourselves to the "unreliable datagram" case?

Seems reasonable to me.

> Do we have a universal set of requirements for datagram queue management?

I think the main requirement would be for the writer queue be tiny, just large enough to ensure performant throughput, yet small enough to still be near real-time, as I mention in https://github.com/w3c/webtransport/pull/179#issuecomment-772093452.

Since datagrams have no back channel, it means:
- Sender-side, back pressure is what keeps our queue small
- Receiver-side, back pressure causes our queue to grow (unless we prune it)

Regarding the reader queue, as long as JS keeps up, things should be real-time. But if it can't, this may be where we'd want to drop packets to keep the queue from growing out of control over time (unless we add some `flush` method and call it a feature?)

**Comment by aboba** [comment]
QUIC datagram receivers do not directly communicate available buffer space to senders.  [QUIC datagram Section 5.2](https://tools.ietf.org/html/draft-ietf-quic-datagram-01#section-5.2) says: 

"   DATAGRAM frames do not provide any explicit flow control signaling,
   and do not contribute to any per-flow or connection-wide data limit."

However, QUIC datagrams are subject to congestion control. [QUIC datagrams draft](https://tools.ietf.org/html/draft-ietf-quic-datagram-01#section-5.3) says: 

"5.3.  Congestion Control

   DATAGRAM frames employ the QUIC connection's congestion controller.
   As a result, a connection may be unable to send a DATAGRAM frame
   generated by the application until the congestion controller allows
   it [I-D.ietf-quic-recovery].  The sender implementation MUST
   either delay sending the frame until the controller allows it or drop
   the frame without sending it (at which point it MAY notify the
   application).

   Implementations can optionally support allowing the application to
   specify a sending expiration time, beyond which a congestion-
   controlled DATAGRAM frame ought to be dropped without transmission."

PR https://github.com/w3c/webtransport/pull/179 was an attempt to implement the suggestion in the last paragraph. 

What is "Just large enough to ensure performant throughput"?

Throughput ~ congestion window/RTT, so the size of the send buffer required for a given throughput will vary with the round-trip time.  As an example, if the send queue is 10 packets (~ 15000 bytes), and the RTT is 100 ms, then the maximum throughput will be ~ 1.2 Mbps, not sufficient for game streaming.

**Comment by jan-ivar** [comment]
I think this is in good shape now. Closing,
