### ISSUE TITLE
Problems with Example 14.6

### ISSUE THREAD

**Issue by aboba** [w3c/webtransport#193]
Example 14.6 in PR https://github.com/w3c/webtransport/pull/182 does not run. 

Errors include: 
Syntax error: addToEventLog(`Error while reading from stream #${number": ${e}`, 'error');

Error while reading datagrams: TypeError: transport.datagramReadable is not async iterable
Error while accepting streams TypeError: transport.incomingUnidirectionalStreams is not async iterable
Error while reading from stream #1": TypeError: stream.readable.pipeThrough(...).getReader(...) is not a function or its return value is not async iterable
stream.readable.pipeThrough(...).getReader(...) is not a function or its return value is not async iterable

**Comment by ricea** [comment]
> Error while reading datagrams: TypeError: transport.datagramReadable is not async iterable
> Error while accepting streams TypeError: transport.incomingUnidirectionalStreams is not async iterable

These two are because the async iteration feature is not yet implemented in Chrome. I don't think it's worth making the examples more complex just to work around a deficiency in Chrome. It can be polyfilled quite easily.

**Comment by jan-ivar** [comment]
There's also a typo that I've fixed in https://github.com/w3c/webtransport/pull/192, but we can do a separate PR if that one doesn't stick. 
```diff
-    for await (const chunk of stream.readable.pipeThrough(decoder).getReader()) {
+    for await (const chunk of stream.readable.pipeThrough(decoder)) {
```

**Comment by jan-ivar** [comment]
> > Error while reading datagrams: TypeError: transport.datagramReadable is not async iterable
> > Error while accepting streams TypeError: transport.incomingUnidirectionalStreams is not async iterable
> 
> These two are because the async iteration feature is not yet implemented in Chrome. I don't think it's worth making the examples more complex just to work around a deficiency in Chrome. It can be polyfilled quite easily.

Agreed, but `incomingUnidirectionalStreams` appears to work in Canary for me in https://github.com/w3c/webtransport/issues/40#issuecomment-766871115 FWIW.

**Comment by wilaw** [comment]
`Syntax error: addToEventLog(Error while reading from stream #${number": ${e}, 'error');` was a typo that was fixed in https://github.com/w3c/webtransport/pull/325

**Comment by jan-ivar** [comment]
I think the examples are in working shape now.
