### ISSUE TITLE
Maybe we shouldn't hog overly generic interface names?

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webtransport#199]
This spec grabs a few generic-sounding interface names that do not seem generic at all, like [SendStream](https://w3c.github.io/webtransport/#sendstream), [ReceiveStream](https://w3c.github.io/webtransport/index.html#receivestream), and [BidirectionalStream](https://w3c.github.io/webtransport/#bidirectionalstream), none of which have constructors. They're visible on `window`; other specs wouldn't be able to reuse them.

Compare to e.g. [RTCRtpScriptTransform](https://w3c.github.io/webrtc-insertable-streams/#scriptTransform) in other specs.

Should we perhaps prefix these? What prefix would we use? `WebTransportSendStream`? `WTSendStream`?

**Comment by yutakahirano** [comment]
I tend to agree. Given the name doesn't matter for people other than spec writers and spec readers, maybe prefixing with `WebTransport` is better than prefixing with `WT`.

**Comment by jan-ivar** [comment]
Meeting:
- Go with `WebTransportBidirectionalStream`
