### ISSUE TITLE
Acknowledgements section is wrong

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webtransport#200]
Just noticed https://w3c.github.io/webtransport/#acknowledgements seems copied from WebRTC. We should probably fix that.

**Comment by aboba** [comment]
@jan-ivar Can we close this issue now?

**Comment by jan-ivar** [comment]
@aboba Yes. In the future, `s/Fixes Issue #200/Fixes #200/` in the PR description should close the Issue automatically (hover over the word "Fixes" to reveal an underline to check its working).
