### ISSUE TITLE
Remove remaining "For QUIC" and quic-transport references

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webtransport#204]
Even after https://github.com/w3c/webtransport/pull/196, I count 7 references to _"For QUIC, "_ and 2 to _" quic-transport"_ that should be removed.

**Comment by aboba** [comment]
The [QUIC-TRANSPORT] reference points to the document defining QUIC, rather than to the 'QuicTransport' protocol specification (which didn't exist when the WebTransport specification was first created).  Maybe we should rename the reference to [QUIC] in order to avoid confusion.

**Comment by aboba** [comment]
@jan-ivar Can we close this issue now?

**Comment by yutakahirano** [comment]
There is one occurrence but I have a PR to remove it, so I think we can close this.
