### ISSUE TITLE
UnidirectionalStream could be simpler

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webtransport#210]
Conceptually, bidirectional streams ([1](https://w3c.github.io/webtransport/#dom-bidirectionalstreamstransport-createbidirectionalstream), [2](https://w3c.github.io/webtransport/#dom-bidirectionalstreamstransport-incomingbidirectionalstreams)) are inherent [duplex streams](https://streams.spec.whatwg.org/#other-specs-duplex), but unidirectional streams ([1](https://w3c.github.io/webtransport/#dom-unidirectionalstreamstransport-createunidirectionalstream), [2](https://w3c.github.io/webtransport/#dom-unidirectionalstreamstransport-incomingunidirectionalstreams)) are not. They're conceptually just [writable streams](https://streams.spec.whatwg.org/#ws-class) on sending, and just [readable streams](https://streams.spec.whatwg.org/#rs-class) on reception.

So it feels like I should be able to write:
```js
const wt = new WebTransport(url);
await readableStreamOfTextData
  .pipeThrough(new TextEncoderStream("utf-8"))
  .pipeTo(await wt.createUnidirectionalStream());
```
...instead of:
```js
const wt = new WebTransport(url);
await readableStreamOfTextData
  .pipeThrough(new TextEncoderStream("utf-8"))
  .pipeTo((await wt.createUnidirectionalStream()).writable); // clunky
```

Similarly on reception, it feels more natural to guess I would need to write:
```js
for await (const stream of wt.incomingUnidirectionalStreams) {
    await stream
     .pipeThrough(new TextDecoderStream("utf-8"))
     .pipeTo(createWritableStreamForTextData());
}
```
...instead of:
```js
for await (const stream of wt.incomingUnidirectionalStreams) {
    await stream.readable // why?
     .pipeThrough(new TextDecoderStream("utf-8"))
     .pipeTo(createWritableStreamForTextData());
}
```

A counter-argument might be symmetry with bidirectional streams — that I may want to drop in one for the other, or not care which one I used. But this seems like false symmetry. I think I'd rather have a TypeError if I did that, to catch either why no data is being received, or being dropped because I'm not handling it.

The precedent in the streams spec are duplex and [transform streams](https://streams.spec.whatwg.org/#ts-model), versus readable and writable streams, which are all called _"streams"_, even though the former have `readable` and `writable` members, whereas the latter _are_ those members. They're two classes of inherently incompatible (duck) types: the former accepted by `pipeThrough` (which returns a readable stream), the latter by `pipeTo` (which returns a promise) as `this` or input. Asymmetry abounds.

I think we should follow that same conceptual model to avoid confusion: Have them be [OutgoingStream](https://w3c.github.io/webtransport/#outgoingstream) on sending, or [IncomingStream](https://w3c.github.io/webtransport/#incomingstream) on reception.

A second counter-argument might be that _OutgoingStream_ and _IncomingStream_ have other methods on them. But that's [not a problem](https://github.com/w3c/webtransport/pull/192#discussion_r576887367) according to @domenic.

This would be a breaking change.

**Comment by yutakahirano** [comment]
> A second counter-argument might be that OutgoingStream and IncomingStream have other methods on them. But that's not a problem according to @domenic.

Can you elaborate on this? I think I don't understand why that's not a problem. IIUC @domenic was talking about putting readable/writable members at the same level with other methods, but this proposal seems to put ReadableStream methods at the same level with other methods.

**Comment by domenic** [comment]
Although @yutakahirano's read of my previous comment is correct, I'm sympathetic to the OP.

Putting ReadableStream/WritableStream methods on the same level as other methods is done through subclassing. The example we have so far on the platform is https://wicg.github.io/file-system-access/#api-filesystemwritablefilestream .

IMO if something is called a "stream" then it should either be a ReadableStream/WritableStream or a subclass. (Or a duplex or transform stream; those are a special case.) It sounds like the current spec uses the name "stream" for something that is actually a stream container, i.e. has a `.readable` or `.writable` property.

So I'd suggest either: using a ReadableStream/WritableStream subclass, to implement the semantics from the OP. Or, renaming the containers to not use the word "stream", e.g. renaming `incomingUnidirectionalStreams` to something like `incomingUnidirectionalStreamContainers` or `incomingUnidirectionalTransports` or similar.

**Comment by jan-ivar** [comment]
@ricea Any concerns with doing this? This would be a breaking change.

**Comment by ricea** [comment]
I have no concrete objections.

I worry that subclassing may come back to bite us in future, but it's just a feeling. There used to be implementation problems in Blink which made subclassing hard to implement. @jorendorff, could you comment on whether subclassing ReadableStream is easy or hard in Firefox?

**Comment by jan-ivar** [comment]
Meeting: no objections.

@jorendorff any concerns with subclassing streams in Firefox?
