### ISSUE TITLE
Defining error codes

### ISSUE THREAD

**Issue by martinthomson** [w3c/webtransport#213]
When we abort reading or writing, there is an *optional* parameter that includes the error code.  This is fully generic in the sense that we don't rely on the transport protocol providing any particular error reporting scheme.  However, it's not entirely generic, because the API still inherently assumes that there is a numeric value that can be sent/received.  And we set a default.

If WebTransport is not defining an application protocol and we believe that users of the protocol are responsible for doing that, this choice of default denies them the ability to define their own error codes.

I say this because QUIC reserved 0 once and we decided it was a bad idea for that reason.

Why not just accept that this is QUIC and that aborting requires an error code?  Then we don't need to define a default value, just a definition for the type of the code.

**Comment by jan-ivar** [comment]
> Why not just accept that this is QUIC and that aborting requires an error code? 

Not 100% sure I follow. Are you suggesting making the `code` member of [StreamAbortInfo](https://w3c.github.io/webtransport/#dictdef-streamabortinfo) `required`? E.g.
```js
wt.createUnidirectionalStream().abortWriting(); // TypeError?
```

If so, what error code would the following produce?
```js
wt.createUnidirectionalStream().writable.abort(); // what error code?
```
The [Protocol mappings](https://w3c.github.io/webtransport/#protocol-mapping) say
> Method | QUIC Protocol Action
> -- | --
> abortWriting | send RESET_STREAM with code
> writable.abort() | send RESET_STREAM

...but I'm not sure what the latter means, whether QUIC inserts a default code (0?) for the latter or not, or whether it's distinctly absent.

Also, remind me why we have `abortWriting` again? The streams spec [supports an optional code already](https://streams.spec.whatwg.org/#writablestream), so this should work, no?
```js
wt.createUnidirectionalStream().writable.abort(1); // RESET_STREAM with 1
```

**Comment by ricea** [comment]
> Also, remind me why we have `abortWriting` again? The streams spec [supports an optional code already](https://streams.spec.whatwg.org/#writablestream), so this should work, no?
> 
> ```js
> (await wt.createUnidirectionalStream()).writable.abort(1); // RESET_STREAM with 1
> ```

Because it may be useful to reset the stream after closing, to achieve unreliable semantics. WHATWG Streams semantics don't support abort-after-close.

**Comment by martinthomson** [comment]
So QUIC insists on RESET_STREAM having an error code.  That makes `writeable.abort()` tricky, because whatever the browser decides might not be appropriate for the protocol that has been negotiated.  Can we insist on the reason argument being mandatory, even if `WritableStream` makes it optional.

`abortWriting(100)` rather than `abortWriting({ code: 100})` is easy.

**Comment by ricea** [comment]
> Can we insist on the reason argument being mandatory, even if `WritableStream` makes it optional?

We could make `abort()` return a rejected promise, but it still has to abort the stream somehow, because otherwise it would leak. I suggest just picking a default code.

**Comment by LPardue** [comment]
I had kind of assumed that RESET_STREAM application error codes were bound to the negotiated ALPN, meaning that we still need to use HTTP/3's error code space for the H3-based protocol even if some streams are repurposed via semantic extension. To me, that means the protocol should coin an H3 error code space for the equivalent of WebTransport No Error which could be used as a sensible default.

**Comment by martinthomson** [comment]
Good point.  Of course this needs to borrow from h3.  That means it can define 1 code for use by the API itself and N codes for the WebTransport protocol.  I can see the single code being a small-ish one (2 bytes) and the other being larger (4 bytes perhaps) so that the space can be a bit larger.

**Comment by jan-ivar** [comment]
> Can we insist on the reason argument being mandatory, even if WritableStream makes it optional?

I don't think it would help, because it may be called upstream.

**Comment by jan-ivar** [comment]
Meeting:
- Seems like we should reserve an error code (out of 0-255) for when streams error without an application-provided WebTransport error codes. @vasilvv mentioned there is an IETF issue for that (link?)
- Would also like clarity from IETF on whether 0 means no error

**Comment by jan-ivar** [comment]
Meeting:
- 0 is now the default error code.
- Errors seem in order now.
