### ISSUE TITLE
Error codes that don't fit

### ISSUE THREAD

**Issue by martinthomson** [w3c/webtransport#214]
We need text when the error code value doesn't fit in the protocol.  2<sup>62</sup> would not fit in the protocol, but it is a valid value for `unsigned long long`.

**Comment by jan-ivar** [comment]
Take the lower bits?

**Comment by martinthomson** [comment]
I was thinking `throw`, but whatever works.

**Comment by yutakahirano** [comment]
close() and abort() are cleanup operations - for example they are often called in catch clauses. I think such functions shouldn't throw whenever possible. I prefer defaulting to 0.

**Comment by jan-ivar** [comment]
As @ricea mentioned in https://github.com/w3c/webtransport/pull/288#discussion_r657531877 I think this boils down to us deciding between `[EnforceRange]` and `[Clamp]`.

**Comment by jan-ivar** [comment]
Meeting:
- Go with `[Clamp]`

**Comment by yutakahirano** [comment]
At https://github.com/w3c/webtransport/pull/288#discussion_r657531877 suggested `[Clamp]` because we used `octet` there. Now we need a wider range, and we cannot use `[Clamp]`.

I'm going to introduce a custom `[Clamp]`-like logic. @ricea, please let me know if I'm wrong.

**Comment by ricea** [comment]
IIUC, `[Clamp]` will work for any integer type. https://heycam.github.io/webidl/#Clamp

**Comment by yutakahirano** [comment]
But it doesn't have arguments - we cannot set min/max.

In this case we want to define a custom range - [0, 2 ** 62), so we cannot use `[Clamp]`.

(Moreover, 2 ** 62 is not valid as `unsigned long long` - we need to use bigint).

My proposal is the following.

```
[Exposed=(Window,Worker), SecureContext]
interface WebTransportError : DOMException {
  constructor(optional WebTransportErrorInit init = {});

  readonly attribute (unsigned long long or bigint)? applicationProtocolCode;
};

dictionary WebTransportErrorInit {
  ([Clamp] unsigned long long) or bigint applicationProtocolCode;
  DOMString message;
};
```

Things that are not clear to me:

 - Is it better to have `WebTransportError.applicationProtocolCode` as `(unsigned long long or bigint)?` or `bigint?`?

cc: @yuki3 as a WebIDL expert.

**Comment by ricea** [comment]
Oh, I see. sgtm.

**Comment by yuki3** [comment]
> Is it better to have `WebTransportError.applicationProtocolCode` as `(unsigned long long or bigint)?` or `bigint?`?

The former is not possible as `unsigned long long` and `bigint` are not [distinguishable](https://heycam.github.io/webidl/#dfn-distinguishable).  `unsigned long long` is a numeric type, and numeric types are not distinguishable from bigint.

**Comment by yutakahirano** [comment]
Thank you!
