### ISSUE TITLE
Interaction with tooling

### ISSUE THREAD

**Issue by vasilvv** [w3c/webtransport#22]
I was thinking about it, and there's a bunch of tooling on the web that assumes you have a URL for your resource (for example, so that an extension could filter those). Do we want to define URL for WebTransport?  Do we want it to be something we expose in the API or something we only use in tooling?  If a single server is reachable via multiple transports, do we want them to have same URL, or just one URL per transport?

Probably should be discussed once we move to WICG, filing here so we don't forget.

**Comment by jan-ivar** [comment]
@vasilvv I'm having trouble parsing this issue. Don't we have a URI scheme already that a server sees? Is there any remaining work here for this WG?
