### ISSUE TITLE
Editorial: Define internal slots outside of algorithms

### ISSUE THREAD

**Issue by yutakahirano** [w3c/webtransport#222]
Pointed out by @annevk in https://github.com/w3c/webtransport/pull/217.

> It seems bad to define internal slots inside an algorithm... They should be defined under the object they belong to.

I agree with that. I'm imagining something like https://streams.spec.whatwg.org/#rs-internal-slots.

**Comment by yutakahirano** [comment]
Do you have any opinions? If there're no objections in this week I'll make a PR.

**Comment by ricea** [comment]
Yes, I'd prefer to see them defined in one place outside the algorithm so that I know the shape of the class before looking at the algorithms.

**Comment by annevk** [comment]
One thing @domenic sometimes points out is that he regrets the style in Streams and prefers "associated thing" over "internal slot [[thing]]". That's probably much more up to editor discretion than not defining them inside the algorithm though.

**Comment by yutakahirano** [comment]
Thank you. I'm fine with that style too.

**Comment by ricea** [comment]
I prefer the internal slot style, otherwise you end up with prose like "set body's body to body" with only formatting to distinguish what each "body" is referring to.

**Comment by yutakahirano** [comment]
> I prefer the internal slot style, otherwise you end up with prose like "set body's body to body" with only formatting to distinguish what each "body" is referring to.

As I'm planning to remove most of "internal slot" words from the text, (#223) that means square brackets matter for readability (e.g., transport's connection vs. transport's [[connection]]). Is my understanding correct?

**Comment by ricea** [comment]
> As I'm planning to remove most of "internal slot" words from the text (#223), that means square brackets matter for readability (e.g., transport's connection vs. transport's [[connection]]). Is my understanding correct?

Yes. For me at least, the square brackets are a much more obvious indicator of what kind of thing we're talking about.

**Comment by yutakahirano** [comment]
Thank you!

**Comment by yutakahirano** [comment]
Created a PR: #244
