### ISSUE TITLE
Editorial: "internal slot"

### ISSUE THREAD

**Issue by yutakahirano** [w3c/webtransport#223]
The term "internal slot" is used very much in the current spec, but in various ways.

1. An internal slot is a slot on which a value is stored. This is the most formal use I think.
   - "Let _stream_ have a __\[[Writable]]__ internal slot initizlied to a new `WritableStream`."
   -  "On getting it MUST return the value of the `IncomingStream`'s __\[[Readable]]__ slot."
   - "Return the value of the __\[[ReceivedStreams]]__ internal slot."
2. Sometimes it means the value stored in it.
   - "Remove the stream from the _transport_’s __\[[OutgoingStreams]]__ internal slot."
3. Sometimes "internal slot" is missing.
   - "If _transport_’s __\[[WebTransportState]]__ is `"closed"` or `"failed"`, then abort these steps.

I prefer the third way - given we enclose every internal slot name with "\[[]]", and we are interested in values rather than slots (except for definition - please see also #222), we can remove "internal slot" occurrences except for internal slot definitions, and the spec will be less repetitive and more readable I think.

Just for reference, the streams spec defines a lot of internal slots (e.g., https://streams.spec.whatwg.org/#rbs-controller-internal-slots) but they are called without "internal slot" (e.g., "Let _stream_ be this.__\[[stream]]__." in https://streams.spec.whatwg.org/#rbs-controller-private-pull).

**Comment by yutakahirano** [comment]
Do you have any opinions? If there're no objections in this week I'll make a PR.

**Comment by ricea** [comment]
I also like option 3.
