### ISSUE TITLE
Garbage collection

### ISSUE THREAD

**Issue by yutakahirano** [w3c/webtransport#225]
WebSocket has [a section for garbage collection](https://html.spec.whatwg.org/multipage/web-sockets.html#garbage-collection-2). The user agent must not collect a WebSocket object when its connection is active and it has active event listeners.

We should have a section too. Given WebTransport doesn't have event listeners the rule should be different from WebSocket.

We have some options.

1. A WebTransport cannot be garbage collected as long as its state is `connecting` or `connected`.
1. A WebTransport cannot be garbage collected as long as its state is `connecting`.
1. A WebTransport can be garbage collected like usual objects.

Thoughts?

**Comment by ricea** [comment]
I think option 3. is the same as saying nothing. However, in Blink I think we have implemented 1. because it is easiest for us. Perhaps we should standardise that behaviour.

**Comment by yutakahirano** [comment]
Even when we choose 3, I think that's worth noting because that is different from WebSocket.

I think 1. is too leaky and I prefer 3, although it has some confusing behaviors (holding the `ready` promise doesn't prevent garbage collection, for example).

**Comment by yutakahirano** [comment]
I propose the following.

```

Unlike WebSocket, WebTransport can be garbage collected in the same manner with usual objects.

Note: As all the streams, datagram.readable, datagram.writable and the WebTransport object
are mutually linked, if one of them is not eligible for garbage collection, all of them are not egigible
for garbage collection.

When a WebTransport object transport is garbage collected and its [[State]] is "connected", then in parallel,
terminate transport’s [[Session]] with TBD.

```

What do you think? If there is no objection in a week I'll make a PR.

**Comment by ricea** [comment]
Writing something in the standard that we can't actually implement in Blink worries me. People reading the standard might reasonably assume they can create and discard WebTransport objects and the browser will take care of cleaning them up. But in Blink they will just leak.

**Comment by yutakahirano** [comment]
Regarding Blink implementation I think we want to make WebTransport an ActiveScriptWrappable and have its HasPendingActivities() return true when one of its streams has pending pull, write or close request.

**Comment by ricea** [comment]
Although this is very Blink-specific, I've had problems in the past with the garbage collector trying to collect objects that own a Mojo interface causing "use after poison" errors.

**Comment by yutakahirano** [comment]
Option1 is acceptable to me. If we choose it, the sentence would be quite simple.

Other opinions are welcomed too!

**Comment by ricea** [comment]
My preference is for option 1.

**Comment by jan-ivar** [comment]
Meeting:
- Go with option 1.
