### ISSUE TITLE
Decide on allowPooling default value

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webtransport#228]
From meeting: It's still unclear what the best default here is long-term.

**Comment by jan-ivar** [comment]
From a server's perspective, pooling is a way to conserve resources. Having to rely on every client setting this to true explicitly, may be an obstacle to servers being able to conserve resources.

**Comment by jan-ivar** [comment]
Since pooling isn't yet implemented by anyone, having it default to true would be difficult in practice.

The spec currently [says](When set to true) _"When set to true"_, which implies default of `false` was the intent, but we should be explicit about it.

**Comment by yutakahirano** [comment]
There is an explicit step in https://w3c.github.io/webtransport/#webtransport-constructor.

> 5. Let allowPooling be options's allowPooling if it exists, and false otherwise.

**Comment by yutakahirano** [comment]
I noticed this doesn't have to be resolved before the first release. I changed the milestone. As
 - pooling is not supported in the first release,
 - we agree on the default value, and
 - the normative logic is already consistent with the agreement,

we don't need to fix this soon.

**Comment by jan-ivar** [comment]
With Chrome shipping MVP, we'd most likely want `allowPooling` to default to `false` for web compat. Closing.
