### ISSUE TITLE
New connection throttling

### ISSUE THREAD

**Issue by ricea** [w3c/webtransport#230]
New connections should be throttled to avoid being a DoS vector. Maybe we will just have some language in the standard to permit and encourage throttling, and leave the details to browsers. Possibly that text belongs in the RFC rather than here.

**Comment by martinthomson** [comment]
This is probably a protocol specification thing, yeah.

**Comment by wilaw** [comment]
Transferred to IETF issue list https://github.com/ietf-wg-webtrans/draft-ietf-webtrans-http3/issues/50
