### ISSUE TITLE
Error codes for stream reset and connection close

### ISSUE THREAD

**Issue by vasilvv** [w3c/webtransport#235]
We have `WebTransportCloseInfo` and `StreamAbortInfo` that were closely modeled on the corresponding QUIC concepts.  It turns out that replicating those context in HTTP/3 setting is not trivial (ietf-wg-webtrans/draft-ietf-webtrans-http3#40, ietf-wg-webtrans/draft-ietf-webtrans-http3#41), so we should consider which of those do we actually need to provide.

**Comment by martinthomson** [comment]
We'll take 256 values and work around the holes for greasing.  Victor will make a proposal for dealing with closing strings, the protocol people will manage that.

**Comment by jan-ivar** [comment]
Since been fixed.
