### ISSUE TITLE
mixin interfaces can't inherit

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webtransport#239]
#233 made `Outgoingstream` inherit  from `WritableStream` and `IncomingStream` inherit from `ReadableStream` but [WebIDL doesn't allow inheritance for mixin interfaces](https://heycam.github.io/webidl/#prod-MixinRest).

**Comment by jan-ivar** [comment]
Doh! Well, we were going to remove the mixins anyway. I'll take care of it for these three.
