### ISSUE TITLE
Rename abortWriting() and remove abortReading()?

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webtransport#242]
I find it hard to distinguish [abortWriting](https://w3c.github.io/webtransport/#dom-outgoingstream-abortwriting) from [abort](https://streams.spec.whatwg.org/#ws-abort) or intuit [what it does differently](https://github.com/w3c/webtransport/issues/213#issuecomment-789411510) or how they overlap (if they do):

```js
const writable = await wt.createUnidirectionalStream();
// ...
writable.abort(1);
writable.abortWriting({errorCode: 1});
```
We should clarify the difference in the spec, and explain any overlap. The [mappings table](https://w3c.github.io/webtransport/#protocol-mapping) doesn't say whether `1` is used.

It's also a naming problem, since "writing" doesn't add much context. `abortSending()`, `stopSending()`, `abruptAbort()`?

Ditto [abortReading](https://w3c.github.io/webtransport/#dom-incomingstream-abortreading) and [cancel](https://streams.spec.whatwg.org/#rs-cancel):
```js
const {readable} = await wt.createBidirectionalStream();
// ...
readable.cancel(0);
readable.abortReading({errorCode: 0});
```
Here I don't actually know what the difference is. @ricea? `abortReceiving()`, `stopReceiving()`? Remove it?

**Comment by ricea** [comment]
Yeah, I actually prefer `reset()` personally. Or maybe `drop()` since it may drop data.

**Comment by jan-ivar** [comment]
@ricea You mean instead of `abortWriting()`? `reset()` might be confusing, since `abort()` also [resets](https://w3c.github.io/webtransport/#protocol-mapping), and neither is a subset of the other. I like `drop()`.

Can we remove *abortReading* then?

**Comment by ricea** [comment]
> @ricea You mean instead of `abortWriting()`? `reset()` might be confusing, since `abort()` also [resets](https://w3c.github.io/webtransport/#protocol-mapping), and neither is a subset of the other. I like `drop()`.

Yes, instead of `abortWriting()`.

> Can we remove _abortReading_ then?

I don't know of any interesting semantics that _abortReading_ has that can't be done with `cancel()`, but maybe someone else here does?

**Comment by aboba** [comment]
@ricea I like `reset()` as well.  In fact, as I recall that was the original name of the method.

**Comment by martinthomson** [comment]
`reset(code : u64, direction : { "read", "write", "both" })` ?
