### ISSUE TITLE
Invalid IDL for OutgoingStream and IncomingStream

### ISSUE THREAD

**Issue by foolip** [w3c/webtransport#243]
https://w3c.github.io/webtransport/#outgoing-stream was updated in https://github.com/w3c/webtransport/pull/233 and currently looks like this:
```
[ Exposed=(Window,Worker) ]
interface mixin OutgoingStream : WritableStream /* of Uint8Array */ {
  readonly attribute Promise<StreamAbortInfo> writingAborted;
  undefined abortWriting(optional StreamAbortInfo abortInfo = {});
};
```

An interface mixin can't inherit from anything. It's like a partial definition and only adds members the interfaces through includes like `SendStream includes OutgoingStream`.

The language "An OutgoingStream *is* a WritableStream of Uint8Array" makes it seem like perhaps this isn't supposed to a mixin any longer but a concrete interface, but I'm not sure what's intended.

**Comment by foolip** [comment]
Just making a guess, but maybe it's `SendStream` that should inherit from `WritableStream` and `ReceiveStream` should inherit from `ReadableStream`?

**Comment by yutakahirano** [comment]
Thank you for filing this! #239 is the same problem, I'm closing this.
