### ISSUE TITLE
Is it a good idea to define WebTransport "session"?

### ISSUE THREAD

**Issue by yutakahirano** [w3c/webtransport#250]
Hi,

Currently we have "connection" in our spec but we don't have "session".  We're going to specify datagrams and streams in more details, and I think "session" is useful concept for various reasons:

 1. We'll be able to group together many protocol related actions and notifications.
 2. "session" is a key concept in the protocol, and having the corresponding concept here will help developers who read both specs.
 3. Without the concept we always need to think about "session ID" which is purely tiresome for both readers and writers.

What do you think?

**Comment by yutakahirano** [comment]
@vasilvv

**Comment by jan-ivar** [comment]
@yutakahirano Would this be a rename or distinct from connection?

**Comment by yutakahirano** [comment]
They're distinct concepts, I believe. We can create multiple sessions on the same connection.

**Comment by yutakahirano** [comment]
I'd like to talk about this in tomorrow's meeting.
