### ISSUE TITLE
Add datagrams.setSendQueueExpiration(long duration)?

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webtransport#251]

**Comment by yutakahirano** [comment]
I have some naming preferences. What do people think?

- Is it better to keep the suffix "Duration"?
- I slightly prefer "Outgoing" to "SendQueue" (With "Outgoing" I think we don't need "Queue").
- I can make them attributes.

**Comment by yutakahirano** [comment]
A PR is available at #267.

**Comment by ricea** [comment]
How about `setOutgoingMaxAge()`?

**Comment by yutakahirano** [comment]
setOutgoingMaxAge/setIncomingMaxAge SGTM.
