### ISSUE TITLE
Add custom error property for Application Protocol Error Codes?

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webtransport#252]
From https://github.com/w3c/webtransport/pull/248#issuecomment-828363738:
> Reg: remoteReset, I think we can add properties to the exception with which closed is rejected, instead of introducing remoteReset. What do you think about the idea?

@yutakahirano Normally, I wouldn't be a fan of overloading errors with application-properties, but it might streamline (no pun intended) error handling, since we are indeed exposing an (application-specific) [server error code](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#name-application-protocol-error-) to JS here, and our current approach of trying to avoid defining a custom error for this I think misses that we still need to surface an error downstream.

This might be a good time to review our error strategy vis-a-vis with streams spec.

Even though the streams spec allows `any` "reason", my guess is best practice is to create error (DOMException) objects, just like we do for throwing things?

Similarly, calling streams methods with error code numbers to reset a QUIC stream [seems a bit off](https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/248.html#protocol-mapping):

Method | QUIC Protocol Action
---- | ----
 writable.abort(42) | send RESET_STREAM with 42

Might it be better to do something like this?
```js
writable.abort(new WebTransportError({errorCode: 42}))
```

This would also let us streamline the the wt.[closed](https://w3c.github.io/webtransport/#dom-webtransport-closed) attribute by rejecting instead of resolving on error:
```js
try {
  await wt.closed;
  // success!
} catch (e) {
  if (e.name != "WebTransportError") throw e;
  console.log("Server error: e.errorCode); // 42
}
```
vs. today:
```js
const info = await wt.closed;
if (info.errorCode == 0) {
  // success!
} else {
  console.log("Server error: info.errorCode); // 42
}
```

**Comment by jan-ivar** [comment]
@ricea Thoughts?

**Comment by ricea** [comment]
I seem to recall reading somewhere that we should try to avoid adding new exception types to the platform, but I can't find a reference to it now. @domenic ?

When `Error`s are transferred, only the `message` and `name` properties are cloned. `DOMException` is a special case, and it's possible that `WebTransportError` could be a special case too.

Requiring the user to pass a `WebTransportError` object to `abort()` to customise the `errorCode` seems a little strict. For `WebSocketStream` I made `abort({code: 4200})` work, which seems like a good compromise.

You're right that platform APIs should only error streams with some kind of exception type, but I think it's okay for users not to follow this rule.

**Comment by yutakahirano** [comment]
We talked about providing more information to Errors at whatwg/fetch#526, and I got the impression that it was not prohibitive.

**Comment by domenic** [comment]
> I seem to recall reading somewhere that we should try to avoid adding new exception types to the platform, but I can't find a reference to it now. @domenic ?

It's more that we don't have a good infrastructure for doing so, and we'd need to do some bindings/Web IDL work before specs did so.

I could swear we had a proposal to make this general by adding some kind of extra info or code to `DOMException` itself. Like `new DOMException(message, name, { info })` or something. But I can't find it on the Web IDL bug tracker at least.

Another alternative is to just mint new `DOMException` names. That's what [Web Serial](https://wicg.github.io/serial/) did: "BufferOverrunError", "BreakError", "FramingError", "ParityError". It sounds like that doesn't work here though.

The one thing you really should not do is define a new `interface` type, e.g. `WebTransportError` and use that as an exception type. Exceptions have different behavior than most interfaces. If we went that route we'd want to generalize Web IDL's current definition of `DOMException` into something which you could reuse, e.g. `[Exception] interface WebTransportError { ... }`. I'm willing to help with that if that's the right path.

> Requiring the user to pass a WebTransportError object to abort() to customise the errorCode seems a little strict. For WebSocketStream I made abort({code: 4200}) work, which seems like a good compromise.
> 
> You're right that platform APIs should only error streams with some kind of exception type, but I think it's okay for users not to follow this rule.

Hmm. What I worry about is that `wt.closed` really should reject with a proper exception object. If `WebSocketStream` does not do this currently, that's unfortunate.

It'd be kind of nice indeed if users could pass something like `{ code: 4200 }` or just `4200` and get that converted into an appropriate error type, but streams currently doesn't have such machinery...

**Comment by jan-ivar** [comment]
> The one thing you really should not do is define a new interface type, e.g. WebTransportError and use that as an exception type.

@domenic How does that square with https://github.com/w3c/webrtc-pc/issues/2082? We have [RTCError](https://w3c.github.io/webrtc-pc/#idl-def-rtcerror) and [OverconstrainedError](https://w3c.github.io/mediacapture-main/getusermedia.html#idl-def-overconstrainederror) that both do this (though implementation is still [poor](https://jsfiddle.net/jib1/pz5pynyf/73/)).

**Comment by ricea** [comment]
Hmm. What I worry about is that wt.closed really should reject with a proper exception object. If WebSocketStream does not do this currently, that's unfortunate.

WebSocketStream's `wss.closed` promise resolves with a `WebSocketCloseInfo` dictionary if the connection close was clean, and rejects with a `DOMException` otherwise. This is a compromise which loses some info, as we may still have received a useful `code` and `reason` even if the close wasn't clean. The ability to add extra info to a DOMException would be handy here.

**Comment by jan-ivar** [comment]
> > The one thing you really should not do is define a new interface type, e.g. WebTransportError and use that as an exception type.
> 
> @domenic How does that square with [w3c/webrtc-pc#2082](https://github.com/w3c/webrtc-pc/issues/2082)? We have [RTCError](https://w3c.github.io/webrtc-pc/#idl-def-rtcerror) and [OverconstrainedError](https://w3c.github.io/mediacapture-main/getusermedia.html#idl-def-overconstrainederror) that both do this (though implementation is still [poor](https://jsfiddle.net/jib1/pz5pynyf/73/) — Correction: `RTCError` [appears implemented](https://wpt.fyi/results/webrtc/RTCError.html) in Chrome)

@domenic Note I plan to propose a `WebTransportError` subclass of DOMException today at the meeting. I understand you had reservations about this, so I'm open to hear better ideas. If such ideas take time, that's fine, and we can improve it later. I think we just need a placeholder to mark that we need a new `code` member for WebTransport Application Protocol Errors, and I don't see another way to do it.

I believe this would be used solely for promise rejections, not in throw statements if that makes any difference (I couldn't tell from what you mentioned about `[Exception]`).

**Comment by domenic** [comment]
Subclassing `DOMException` helps in some ways (it means you get `Error` in your prototype chain, which is not possible in any other way currently). But it is a bit strange in others, because now you have a `code` and `name` property. What do you intend to set those to?

**Comment by jan-ivar** [comment]
@domenic  name to `WebTransportError` and `code` (or similar name if `code` is taken) to the 8-bit application-specific protocol error code [errorcode](https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/248.html#dom-streamabortinfo-errorcode).

**Comment by jan-ivar** [comment]
Oh sorry, I see [code](https://developer.mozilla.org/en-US/docs/Web/API/DOMException/code) is taken in DOMException and has existing meaning. Maybe `appCode` then?

**Comment by jan-ivar** [comment]
Meeting:
- May be two types of errors: transport errors and application errors.
- Maybe ready for PR

**Comment by jan-ivar** [comment]
Meeting:
- `applicationCode`
- Reserve some error codes for user agent.
- IETF is also looking at peer-provided error message string.
- No objection to this general direction.

**Comment by yutakahirano** [comment]
Here are tables for session termination and stream closure/error.

### session termination
|  Cause  |  transport.closed | Note |
| ---- | ---- | --- |
| Got CONNECTION_CLOSE(0x1c, _code_) | rejected with WebTransportError(_code_) ||
| Got CONNECTION_CLOSE(0x1d, _code_) |  rejected with WebTransportError(PROTOCOL_VIOLATION) | This shouldn't happen. |
| transport.close(_info_) where _info_.errorCode == 0 | resolved with WebTransportError(_info_) | normal closure |
| transport.close(_info_) where _info_.errorCode != 0 | rejected with WebTransportError(_info_.errorCode) ||
| Got RESET_STREAM(_code_) on the CONNECT stream | rejected with WebTransportError(_info_.errorCode) ||
| Got FIN on the CONNECT stream | resolved with WebTransportCloseInfo(0, "") | normal closure |

### ReceiveStream closure/error

|  Cause  |  reader.closed | Note |
| ---- | ---- | --- |
| Got FIN | resolved with undefined | normal closure |
| Got RESET_STREAM(_code_) | rejected with WebTransportError(_code_) ||
| cancel({_code_}) | resolved with undefined | send STOP_SENDING(_code_), normal closure | 

### SendStream closure/error

|  Cause  |  writer.closed | Note |
| ---- | ---- | --- |
| close() | resolved with undefined | normal closure |
| abort(_e_) where _e_ = WebTransportError(_code_)) | rejected with _e_ |  send RESET_STREAM(_code_) |
| Got STOP_SENDING(_code_) | rejected with WebTransportError(_code_) |  |


As discussed in the WG meeting, WebTransportError is too overloaded. For example, when reader.closed is rejected with a WebTransportError(9), it can mean
 - It received RESET_STREAM(9),
 - transport.close({errorCode: 9}) is called, 
 - The CONNECT stream received RESET_STREAM(9), or
 - The connection received CONNECTION_CLOSE(0x1c, 9).

We should have more properties on WebTransportError, or we should have multiple error types.
