### ISSUE TITLE
SecureContext whole API? or Disable serverCertificateFingerprints for insecure contexts?

### ISSUE THREAD

**Issue by ricea** [w3c/webtransport#256]
Currently you can use the _serverCertificateFingerprints_ option even when the page was loaded over HTTP. This feels risky. Maybe it should be disallowed?

On the other hand, maybe we should ban WebTransport in insecure contexts altogether?

**Comment by jan-ivar** [comment]
I think we should mark the whole API `SecureContext`. This seems like an omission.

**Comment by jan-ivar** [comment]
Meeting:
- Reasonable to make this `SecureContext` until someone complains.
- Meeting agreement to make it so.
- @vasilvv to check and come back with a use case if there is a problem with doing this.
