### ISSUE TITLE
Should writable.close wait for all the data to be sent to the peer?

### ISSUE THREAD

**Issue by yutakahirano** [w3c/webtransport#259]
According to [QUIC#section-3.1](https://datatracker.ietf.org/doc/html/draft-ietf-quic-transport#section-3.1), after the sender sends a STREAM frame with FIN, the stream enters the "Data Sent" state and it will only retransmits stream data as necessary.

Whether the promise returned by `writer.close()` should wait for [re]transmission of all the data needs to be specified. We have a few options I think.

1. The promise is fulfilled as soon as the STREAM+FIN frame is queued in an internal queue (or, we can say that the promise is fulfilled immediately).
2. The promise is fulfilled as soon as the stream enters the "Data Sent" state (i.e., the STREAM+FIN frame is sent to the network once).
3. The promise is fulfilled as soon as the stream enters the "Data Recvd" state.
4. We can think of a two-way closing handshake, similar to WebSocket. The promise is fulfilled as soon as the handshake finishes.

**Comment by yutakahirano** [comment]
cc: @ricea @vasilvv 

Observations:

For 1. and 2., network errors after the promise is fulfilled are lost, so
  - we need to create another way to detect such errors, or
  - we need to ask application developers to verify whether the peer saw end-of-stream.

2 is somewhat good to achieve "unreliable streams" with `await writer.close(); writable.reset();`.

3 is intuitive and we don't lose network errors on [re]transmission.

**Comment by jan-ivar** [comment]
> 3 is intuitive and we don't lose network errors on [re]transmission.

Seems like a winner.

**Comment by yutakahirano** [comment]
>> 3 is intuitive and we don't lose network errors on [re]transmission.

> Seems like a winner.

Agreed. This will also allow us to remove `reset()` (with whatwg/streams#1015), as the stream state stays in the "writable" state until all the data is acked and hence we can reset the stream with `abort()`.

**Comment by vasilvv** [comment]
I generally don't like exposing the ack state through the API (see #23 for discussion of that), but given that this allows us to handle resets correctly, option 3 sounds like the best approach here.

**Comment by yutakahirano** [comment]
https://github.com/w3c/webtransport/pull/283 contains this (option 3).
