### ISSUE TITLE
What to do with SendStreamParameters?

### ISSUE THREAD

**Issue by ricea** [w3c/webtransport#277]
The [SendStreamParameters](https://www.w3.org/TR/webtransport/#send-stream-parameters) dictionary is empty. Unless we are going to add something to it in the near future, I propose removing it. We can always add it back if we find a use for it.

**Comment by yutakahirano** [comment]
+1

**Comment by aboba** [comment]
The original purpose was to enable things like support for partial reliability,

**Comment by vasilvv** [comment]
I think we should just remove them, until we have any parameters to add.

**Comment by yutakahirano** [comment]
No objections in two seeks, so I made a PR: #303
