### ISSUE TITLE
Should WebTransport streams handle Uint8Array or BufferSource?

### ISSUE THREAD

**Issue by yutakahirano** [w3c/webtransport#284]
Brought up at https://github.com/w3c/webtransport/pull/283#discussion_r652628020.

> In Blink we allow any `BufferSource` type here. Is there a reason to be more restrictive?

I don't have a strong opinion, I just wanted to be consistent with [fetch()](https://fetch.spec.whatwg.org/#incrementally-read-loop).

Do we want to allow only `Uint8Array` objects as chunks of `SendStream` and datagrams, or do we want to allow `BufferSource`s?

**Comment by ricea** [comment]
See also https://github.com/heycam/webidl/issues/989.

**Comment by jan-ivar** [comment]
Meeting:
- See no reason not to accept BufferSource

**Comment by jan-ivar** [comment]
Hold on, [Uint8Array](https://heycam.github.io/webidl/#idl-Uint8Array) is already a _"A view on to an ArrayBuffer"_, so is there maybe a way to allow the same flexibility of `ArrayBufferView or ArrayBuffer` without losing the strict type? I'm generally for stricter typing here since we're sending and receiving bytes.

**Comment by yutakahirano** [comment]
> Hold on, [Uint8Array](https://heycam.github.io/webidl/#idl-Uint8Array) is already a _"A view on to an ArrayBuffer"_, so is there maybe a way to allow the same flexibility of `ArrayBufferView or ArrayBuffer` without losing the strict type? 

I'm against accepting `ArrayBuffer` **only**, as we cannot set offset, and its length is fixed at the allocation timing.
It is acceptable for me to accept only `Uint8Array` **only**. When we have an `ArrayBufferView` _v_, we can create a `Uint8Array` wrapping the same bytes as `new Uint8Array(v.buffer, v.byteOffset, v.byteLength)`.

(To be clear, I'm fine with accepting `BufferSource` as well).

> I'm generally for stricter typing here since we're sending and receiving bytes.

All the `ArrayBufferView` types are for accessing bytes, and an `ArrayBuffer` is ["a generic, fixed-length raw binary data buffer"](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer) so all the `BufferSource` types are suitable for "sending and receiving bytes".

**Comment by jan-ivar** [comment]
Meeting:
- Go with `BufferSource`
