### ISSUE TITLE
SendStream abort reason

### ISSUE THREAD

**Issue by yutakahirano** [w3c/webtransport#294]
Given `writer.closed` is rejected with the argument of `writer.abort()` ("abort reason"), and https://www.w3.org/2001/tag/doc/promises-guide#reasons-should-be-errors, I believe we should encourage web developers to pass an `Error` as abort reason.

Hence the existing example `writer.abort(errorCode)` should be fixed.

**Comment by yutakahirano** [comment]
@ricea do you have any thoughts as a Streams expert?

**Comment by ricea** [comment]
Are you saying that unless users write `writer.abort(new WebTransportError(errorCode))` then `errorCode` will not be sent to the remote server? I don't know how I feel about it. On the one hand, it encourages good practice as you say. On the other hand, it seems like a lot of boilerplate and easy to forget.

**Comment by yutakahirano** [comment]
> Are you saying that unless users write writer.abort(new WebTransportError(errorCode)) then errorCode will not be sent to the remote server? 

I'm saying the default error code will be used when the abort reason is not a WebTransportError.

Currently https://w3c.github.io/webtransport/#sendstream-abort says

> Let code be TBD.

I'm proposing changing the step to:

> Let _code_ be 0.
> If _reason_ is a WebTransportError, set _code_ to _reason_.[[[AppProtocolCode]].

**Comment by ricea** [comment]
A benefit of requiring a WebTransportError object that I hadn't thought of earlier is that we can provide a meaningful diagnostic if `errorCode` is out-of-range.

**Comment by jan-ivar** [comment]
Meeting:
- SGTM
