### ISSUE TITLE
WebTransport.maxDatagramSize bikeshedding

### ISSUE THREAD

**Issue by yutakahirano** [w3c/webtransport#301]
1. Should it be part of WebTransport or DatagramDuplexStream?
1. Should it be "maxDatagramSize" or "maxOutgoingDatagramSize"?
1. Is `unsigned short` enough?
1. Should it be a Promise? According to the [spec](https://datatracker.ietf.org/doc/html/draft-ietf-quic-datagram#section-3) the value is a transport parameter, so it is not available when the transport is contructed.

**Comment by ricea** [comment]
If we put it on the DatagramDuplexStream, can we leave out the word "Datagram"? Then we would have "maxSize" or "maxOutgoingSize".

**Comment by yutakahirano** [comment]
> 4. Should it be a Promise? According to the spec the value is a transport parameter, so it is not available when the transport is contructed.

I think having it as a Promise is not ergonomic. I prefer having it as an integer - when it's not ready it returns 0.

**Comment by jan-ivar** [comment]
> If we put it on the DatagramDuplexStream, can we leave out the word "Datagram"? Then we would have "maxSize" or "maxOutgoingSize".

I agree with this direction, but would apply the same logic to go further, as I do in https://github.com/w3c/webtransport/issues/305.

> I prefer having it as an integer - when it's not ready it returns 0.

Let's make it nullable then like we did for [incomingMaxAge](https://w3c.github.io/webtransport/#dom-datagramduplexstream-incomingmaxage).

**Comment by jan-ivar** [comment]
Meeting:
- Make it non-nullable and initialized to best estimate based on user agent limitations (value can change later anyway).
- Value can change at point of connection established
- Value may change later when path migration occurs (and one other case). Is a pathmigration event needed?

**Comment by yutakahirano** [comment]
I think it's better to include "datagram" in order to prevent confusion between the maximal queue size and maximal chunk size. At #311 I chose "DatagramDuplexStream.maxDatagramSize".
