### ISSUE TITLE
Datagrams readiness

### ISSUE THREAD

**Issue by yutakahirano** [w3c/webtransport#302]
As described at https://datatracker.ietf.org/doc/html/draft-ietf-quic-datagram#section-3, we must not send a datagram until the transport parameter exchange is done.

We need to choose one from the following:

 1. There are two readiness, one for WebTransport over HTTP/3 and the other for datagrams.
 2. There are only one readiness. When both of the CONNECT response and the datagram transport parameters arrive at the client, the transport is ready.

Which do you prefer?

**Comment by yutakahirano** [comment]
@vasilvv @DavidSchinazi Is the above understanding correct?

**Comment by vasilvv** [comment]
I think one readiness promise should be sufficient.

I think we currently cannot send a CONNECT request before receiving SETTINGS from the peer (at least that's true in Chrome implementation), so the specific scenario suggested here probably can't occur.  However, in the new DATAGRAM draft, there's a gap between receiving CONNECT headers and receiving datagram context registration, which would leave us in a similar situation.

During the last IETF interim, we decided to allow sending streams and datagrams before the session is fully ready, to avoid having to wait a round-trip before sending any data.  I wonder if ready state matters as much, and whether we should rethink it.

**Comment by yutakahirano** [comment]
Thank you!

I'm not talking about `.ready` property (or `.[[Ready]]` internal slot), but the internal state (i.e., `.[[State]]`). 

For example, 

> The user agent SHOULD run receiveDatagrams for any WebTransport object whose [[State]] is `"connected"` as soon as reasonably possible whenever the algorithm can make progress.

and

> (createBidirectionalStream)
> 1. Wait for transport’s [[State]] to be "connected".
> 1. Let internalStream be the result of creating a bidirectional stream with transport’s [[Session]].

The former is about datagrams, so we need to wait for datagram transport parameter from the server. The latter is for streams, so we have a choice.

One readiness is simpler and I prefer that. In that case the latter example needs to wait for the datagram parameters from the server.

> During the last IETF interim, we decided to allow sending streams and datagrams before the session is fully ready, to avoid having to wait a round-trip before sending any data.

Interesting! I failed to find the discussion in [the meeting notes](https://datatracker.ietf.org/doc/minutes-interim-2021-webtrans-02-202105200930/): Can you tell me where it is?

**Comment by jan-ivar** [comment]
Meeting:
- Not have different states for streams and datagrams
- Wait until both handshakes are ready
- Might still want to support sending ahead of handshake (added to protocol in April)

**Comment by yutakahirano** [comment]
I think this has already been covered by a note.

> Note: This step also contains the transport parameter exchange specified in [QUIC-DATAGRAM].
