### ISSUE TITLE
Agree on wt.datagrams.outgoingMaxAge vs wt.datagrams.writable.maxAge

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webtransport#305]
https://github.com/w3c/webtransport/pull/267#discussion_r639254538 got merged with unfinished discussion. This is fine in the interest of iteration, but I think we need WG consensus on API. Here's what got merged, along with `maxOutgoingSize` which is being proposed in https://github.com/w3c/webtransport/issues/301:

```js
wt.datagrams.incomingMaxAge = 300;
wt.datagrams.incomingHighWaterMark = 20;
wt.datagrams.outgoingMaxAge = 800;
wt.datagrams.outgoingHighWaterMark = 10;
wt.datagrams.maxOutgoingSize = 1500;
```
Here's what I propose(d) instead:
```js
wt.datagrams.readable.maxAge = 300;
wt.datagrams.readable.highWaterMark = 20;
wt.datagrams.writable.maxAge = 800;
wt.datagrams.writable.highWaterMark = 10;
wt.datagrams.writable.maxSize = 1500;
```
Organizing properties around natural objects we already expose seems cleaner and easier for web developers to understand, and seems better for encapsulation as well, versus relying on naming conventions to attempt to achieve the same correlation. In fact, having both seems discordant.

The argument that was raised against this [was](https://github.com/w3c/webtransport/pull/267#discussion_r639419357) _"avoid [subclassing] without a clear benefit"_. This seems like an implementation concern which would be lower on the [priority of constituencies](https://www.w3.org/TR/html-design-principles/#priority-of-constituencies) compared to web developer ergonomics.

**Comment by jan-ivar** [comment]
> "avoid [subclassing] without a clear benefit"

@ricea I'd like to understand the argument against subclassing, since we have existing examples of _"[subclassing] without a clear benefit"_:
```webidl
[Exposed=(Window,Worker), SecureContext]
interface SendStream : WritableStream /* of Uint8Array */ {
};

[Exposed=(Window,Worker), SecureContext]
interface ReceiveStream : ReadableStream /* of Uint8Array */ {
};
```

**Comment by ricea** [comment]
Yes, `SendStream` and `ReceiveStream` should be replaced with just `WritableStream` and `ReadableStream` now that they have no additional members.

Subclassing creates implementation complexity and technical debt through excessive coupling.  This leads to implementations being inflexible and fragile, which ultimately hurts users by leading to an unstable and unpredictable platform.

There's also a real cost in terms of memory usage and startup time in adding more symbols to the global object. The cost for each individual symbol is small, but given the rate of evolution of the web platform the cumulative effect is large.

**Comment by yutakahirano** [comment]
Filed #306 for SendStream and ReceiveStream.

**Comment by jan-ivar** [comment]
Meeting
- Revisit next meeting.
- Group prefers no change, except rename to queueLength?
- Do we pick incomingMaxAge or maxIncomingAge?
- Do we pick outgoingMaxSize or maxOutgoingSize?

**Comment by jan-ivar** [comment]
Closing for lack of interest.
