### ISSUE TITLE
WebTransportError.ApplicationProtocolCode naming

### ISSUE THREAD

**Issue by yutakahirano** [w3c/webtransport#328]
https://github.com/w3c/webtransport/pull/327#discussion_r687780678
From @martinthomson 

> ApplicationProtocolCode might be a poor choice of name as that is a term QUIC uses for the 62-bit value. What about WebTransportProtocolErrorCode? (It's long, I know.)

**Comment by yutakahirano** [comment]
I don't have a strong opinion. A simple ErrorCode might be OK.

I'd like to have a consensus at the next meeting.

**Comment by vasilvv** [comment]
I'd probably go with something like `webApplicationErrorCode`.

**Comment by yutakahirano** [comment]
I failed to get a consensus today. Let's continue discussing.

> I don't have a strong opinion. Simple `errorCode` might be OK.

`errorCode` or `code` is NOT OK because we already have `DOMException.code`.

How about `webTransportErrorCode`?

**Comment by jan-ivar** [comment]
Meeting bikeshed:
- Prefer `streamErrorCode`
