### ISSUE TITLE
Stream prioritization

### ISSUE THREAD

**Issue by steveanton** [w3c/webtransport#33]
The QUIC IETF specification has a section on stream prioritization: https://tools.ietf.org/html/draft-ietf-quic-transport-16#section-2.4

The summary is that the application is responsible for instructing the QUIC implementation how to prioritize stream data. Which means that this API should have a way for Web developers to indicate the relative priority of streams.

**Comment by Atrius** [comment]
Depending on how datagram support works, we should also consider how to prioritize datagrams vs. streams, and datagrams vs. other datagrams.

If the application gets a callback whenever the transport is ready to send another datagram, but the applications *also* uses streams, what happens first?
 - the transport sends queued stream data
 - the transport calls the application for another datagram

And if the application hands datagrams to the transport, and the transport queues them to be sent at an appropriate moment, it seems fairly apparent we'd want some mechanism to say which streams and/or datagrams should go first.

**Comment by LPardue** [comment]
You might be interested in the individual Internet-Draft https://datatracker.ietf.org/doc/html/draft-pardue-masque-dgram-priority-01
