### ISSUE TITLE
Need to specify what happens if sending bytes fails

### ISSUE THREAD

**Issue by ricea** [w3c/webtransport#333]
> Send bytes on stream’s [[InternalStream]] and wait for the operation to complete.

can fail if
1. STOP_SENDING is received, or
2. a network error occurs, or
3. wt.close() is called

It doesn't look like we handle failure.

**Comment by yutakahirano** [comment]
I think the entire connection should fail in that case. Probably we should have a step similar to https://w3c.github.io/webtransport/#receivestream-pull-bytes.

> If the previous step failed, abort the remaining steps.
>
> Note: We don’t reject promise here because we handle network errors elsewhere, and those steps error stream and reject the result of this read operation.

**Comment by yutakahirano** [comment]
> I think the entire connection should fail in that case.

This was wrong.

> 1. STOP_SENDING is received, or

We should abort the stream in this case.

> 2. a network error occurs, or

The entire connection should fail in this case.

> 3. wt.close() is called

The session will be terminated.
