### ISSUE TITLE
Do we want to store the code and reason for session closure in WebTransportError?

### ISSUE THREAD

**Issue by yutakahirano** [w3c/webtransport#338]
When a session is closed, all the streams on it are aborted, which means we create a `WebTransportError` and [error](https://streams.spec.whatwg.org/#readablestream-error) the ReadableStreams and [abort](https://streams.spec.whatwg.org/#abort-a-writable-stream) the WritableStreams with it.

I thought we would store the `code` and `reason` in the session closure handshake, but I'm now not sure if it's a good idea to allow the server or client to set the `message` property. Quoting texts in Web IDL:

> An ___exception___ is a type of object that represents an error and which can be thrown or treated as a first class value by implementations. Web IDL does not allow exceptions to be defined, but instead has a number of pre-defined exceptions that specifications can reference and throw in their definition of operations, attributes, and so on. Exceptions have an __error name__, a DOMString, which is the type of error the exception represents, and a ___message___, which is an optional, user agent-defined value that provides human readable details of the error.
>
> https://heycam.github.io/webidl/#idl-exceptions

The reason text may not be a "user agent-defined value that provides human readable details of the error".

What do you think?

**Comment by yutakahirano** [comment]
We have several options.

### 1.  Do not store `code` and `reason` to the error.

This option is simple as long as web developers don't access `code` and `reason`. The user agent can put some meaningful message to the error (e.g., "The session is closed cleanly by the server."). If they want to access the information, they need to write some code.

```js
try {
  await stream_reader.closed;
} catch (e1) {
  // The stream is errored!
  if (e1.source === 'stream') {
    // The stream is reset. the code is e1.applicationProtocolCode and there is no reason text.
  } else if (e1.source == 'session') {
    assert_equals(e1.applicationProtocolCode, null);
    try {
      const close_info = await transport.closed;
      // The session is closed cleanly. close_info.code is the code and close_info.reason is the reason text.
    } catch (e2) {
      // The session is closed uncleanly. Neither code nor reason text is provided in this case.
    }
  } else {
    NOTREACHED();
  }
}
```

This is not trivial but not super complex.

### 2. Store only `code` to the error.

With this option, the code is stored to `.applicationProtocolCode` but in order to get the reason string you need to access `transport.closed`, you need to write the above code.

This option is a bit more web developer friendly than the first option, but a bit more inconsistent.

### 3. Store `code` and `reason` to the error.

With this option, the code is stored to `.applicationProtocolCode` and the reason text is stored in `.message`.

**Comment by jan-ivar** [comment]
> ```
> // The session is closed cleanly. close_info.code is the code and close_info.reason is the reason text
> ```
@yutakahirano  DOMException's [`code`](https://heycam.github.io/webidl/#dom-domexception-code) MUST be 0 for `WebTransportError`. I assume you mean [`errorCode`](https://w3c.github.io/webtransport/#dom-webtransportcloseinfo-errorcode)?

**Comment by yutakahirano** [comment]
Yes, thank you for the correction.

**Comment by jan-ivar** [comment]
> With this option, the code is stored to .applicationProtocolCode

It won't fit. The code from the session closure handshake is 64 bits I think, and [`applicationProtocolCode`](https://w3c.github.io/webtransport/#dom-webtransporterror-applicationprotocolcode) is an octet.

> but in order to get the reason string you need to access transport.closed, you need to write the above code.

My preference would be to stick with this for now since it works, and we don't need two ways to do something.

DOMException's `message` field is dedicated to "human readable details of the error", which for web compat means we must avoid reasons for JS to compare it against known values, so we should avoid putting non-deterministic content in it.

**Comment by yutakahirano** [comment]
>> With this option, the code is stored to .applicationProtocolCode

> It won't fit. The code from the session closure handshake is 64 bits I think, and applicationProtocolCode is an octet.

This is being discussed I'm open to change the type of `applicationProtocolCode` if needed.

> My preference would be to stick with this for now since it works, and we don't need two ways to do something.

Sorry, which option do you prefer? Sounds like you prefer 1. but "this" seems pointing 2.

To be clear, my preference is 1.

**Comment by jan-ivar** [comment]
My preference is 1 as well, unless we add a 64-bit `closeCode` to `WebTransportError`...

**Comment by jan-ivar** [comment]
Meeting:
- Prefer option 1

**Comment by yutakahirano** [comment]
Done by #335
