### ISSUE TITLE
Forward error correction?

### ISSUE THREAD

**Issue by AndrewMD5** [w3c/webtransport#34]
One of the lacking features of WebRTC data channels is that there is no native FEC under the hood, forcing developers to use JS or Web Assembly based alternatives. If FEC could be enabled and negotiated by both sides, this would allow for high-performance real-time data applications on more unreliable networks without retransmission.

**Comment by enygren** [comment]
Opened #109 which would make it easier to build FEC applications on top of WebTransport.

**Comment by jan-ivar** [comment]
This seems like an IETF issue, and IETF has not addressed FEC. Let's leave applications to do it, and if someone does something great, we can fold it in.
