### ISSUE TITLE
WebTransportCloseInfo.errorCode bikeshedding

### ISSUE THREAD

**Issue by yutakahirano** [w3c/webtransport#342]
Sorry for the last-minute bikeshedding.

Is `errorCode` a good name for the property? We distinguish WebTransportCloseInfo from WebTransportError, so perhaps `code` or `closeCode` is a better name?

(On the other hand we call it "error code" at https://github.com/ietf-wg-webtrans/draft-ietf-webtrans-http3/pull/60).

**Comment by jan-ivar** [comment]
Meeting:
- `closeCode`
