### ISSUE TITLE
serverCertificateFingerprints bikeshedding

### ISSUE THREAD

**Issue by letitz** [w3c/webtransport#350]
Given the negative implications of fingerprinting, it might be a good idea to rename `serverCertificateFingerprints` to something else that does not have that baggage.

cc @mikewest

**Comment by jan-ivar** [comment]
Talking about "fingerprints" in relation to certificates seems common. E.g. https://w3c.github.io/webrtc-pc/#rtcdtlsfingerprint

**Comment by martinthomson** [comment]
In WebRTC that's a call-out to the SDP attribute.  We can retain the idea, but s/Fingerprints/Hash/ would also be fine.

**Comment by jan-ivar** [comment]
Meeting:
- `serverCertificateHashes`
