### ISSUE TITLE
RTCDtlsFingerprint values are strings

### ISSUE THREAD

**Issue by martinthomson** [w3c/webtransport#355]
This makes sense in WebRTC as the expected source of this information is SDP.  But parsing and validating this string is annoying.  And the most natural form for a fingerprint (ahem hash) is binary data.  I suggest we move to a new dictionary:

```webidl
dictionary WTHash {
  DOMString algorithm;
  BufferSource hash;
}
````

Now, I'm not sure what the convention is for taking binary inputs.  [`BufferSource`](https://heycam.github.io/webidl/#BufferSource) might work here.  I was concerned that maybe the lack of a clear endianness would be an issue here, but it seems like WebCrypto uses that with no issue, so I'm going to assume that this is the right answer.

**Comment by yutakahirano** [comment]
Just to make sure, @martinthomson, are you fine with accepting both of `BufferSource` and `DOMString`, or do you want to exclude `DOMString`?

**Comment by martinthomson** [comment]
I think that the DOMString thing is an unnecessary hazard, but I could accept it, provided that the processing model was sufficiently clearly specified (it is NOT good enough in WebRTC based on my last reading).

**Comment by vasilvv** [comment]
I think we should go with `BufferSource`, as that would save us serializing hashes into ASCII where it's not necessary.

**Comment by yutakahirano** [comment]
Created #358. @martinthomson, are you happy with that change? I want to get an agreement on the next WG meeting but you may not be there so I would like your feedback.

Thanks!
