### ISSUE TITLE
Is notifications a use case?

### ISSUE THREAD

**Issue by foolip** [w3c/webtransport#360]
First, https://github.com/w3c/webtransport/blob/main/explainer.md is a great explainer, very clear and to the point. This is just the small issue that I noticed, with no bearing on the overall picture. This use case is listed:

> Receiving messages pushed from server (such as notifications)

That receiving messaged pushed from the server is a use case generally I can see, but doesn't notification delivery need to be reliable? Or is the point that WebTransport can also serve these use cases which are already served via WebSockets?

**Comment by ricea** [comment]
Messages received as streams can be reliable. In this case you'd write code something like
```js
for await (const stream of wt.incomingUnidirectionalStreams) {
  // This will be cleaner if `stream.arrayBuffer()` is implemented. See 
  // https://github.com/whatwg/streams/issues/1019#issuecomment-587358358
  onNotification(await new Response(stream).arrayBuffer());
}
```
