### ISSUE TITLE
Examples in explainer need to be updated

### ISSUE THREAD

**Issue by foolip** [w3c/webtransport#361]
In https://github.com/w3c/webtransport/blob/main/explainer.md#example-of-sending-unreliable-game-state-to-server-using-quic-datagrams there's a `transport.datagramWritable.getWriter()` call which won't work because there is no `datagramWritable` attribute in the spec. Perhaps it should be `transport.datagrams.writable.getWriter()`?

It's likely there are other things in the examples that also need updating.

**Comment by yutakahirano** [comment]
Thank you for filing this, this is the same problem as #353 so I'm closing this.
