### ISSUE TITLE
Session closure without close info

### ISSUE THREAD

**Issue by yutakahirano** [w3c/webtransport#366]
1. When a client close a WebTransport session __without__ providing WebTransportCloseInfo, Do we want to send a CLOSE_WEBTRANSPORT_SESSION capsule (with the default value)? Or do we close the CONNECT stream without sending a CLOSE_WEBTRANSPORT_SESSION capsule?
 1. When a server closes the CONNECT stream without sending a CLOSE_WEBTRANSPORT_SESSION capsule, do we want to resolve the `.closed` promise with an empty object, or do we want to resolve it with `{closeCode: 0, reason: ""}`?

**Comment by jan-ivar** [comment]
Meeting:
- Should send capsule. If not received and stream closed gracefully, should treat it as having received the default capsule.
- Resolve with `{closeCode: 0, reason: ""}` as minimum (never empty object)
