### ISSUE TITLE
Add server-to-client multicast datagrams as a use case

### ISSUE THREAD

**Issue by GrumpyOldTroll** [w3c/webtransport#371]
Brief presentation explaining the intent in the TPAC 2021 session:
https://docs.google.com/presentation/d/1SG1FUvn9UKGx_gAqWnCzPHlsIXkDUXctZPs7blfqS5k/edit#slide=id.gf938c1e392_0_0
See also: https://w3c.github.io/multicast-cg/multicast-cg-charter.html

**Comment by wilaw** [comment]
This use-case is dependent on browser implementers expressing an interest for supporting multicast. Chrome has stated that they have no intent to support multicast. Mozilla have not expressed interest. We are therefore closing this issue until such time as a browser vendor is willing to support the multicast datagrams as a core feature.
