### ISSUE TITLE
Per-stream stats

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webtransport#372]
At TPAC I proposed [per-stream stats](https://docs.google.com/presentation/d/1SG1FUvn9UKGx_gAqWnCzPHlsIXkDUXctZPs7blfqS5k/edit?pli=1#slide=id.gf66ea8b320_2_16). Discuss.
```js
const stats = await stream.getStats();
```
If `stream` is readable, `stats` would be
```idl
dictionary WebTransportReceiveStreamStats {
  DOMHighResTimeStamp timestamp;
  unsigned long long bytesReceived;
  unsigned long long packetsReceived;
};
```
If `stream` is writable, `stats` would be
```idl
dictionary WebTransportSendStreamStats {
  DOMHighResTimeStamp timestamp;
  unsigned long long bytesSent;
  unsigned long long packetsSent;
  DOMHighResTimeStamp minRtt;
};
```
We could reuse this for datagrams:
```js
const incomingStats = await wt.datagrams.readable.getStats();
const outgoingStats = await wt.datagrams.writable.getStats();
```

**Comment by martinthomson** [comment]
I realize in looking at this again that - at the receiver - tracking the received bytes is fiddly.  It is easy to track the maximum offset into the stream that has been received, but annoying to count the number of bytes that have been received.  If there are gaps in what you receive, you have to walk through all the gaps, which is annoying.

You can also count the number of bytes received without accounting for redundancy (if you receive the first byte multiple times, you can count it each time), but I'm not sure that that is useful information.

**Comment by jan-ivar** [comment]
Meeting:
- Leaning toward wt.getStats() for aggregate values + connection level stats
- And outgoingStream.getStats() for long-lived streams, to avoid tracking short-lived streams (e.g. stream per videoFrame).

**Comment by jan-ivar** [comment]
Here's my bikeshed attempt at pulling @martinthomson's https://github.com/w3c/webtransport/issues/372#issuecomment-953353869 into a concrete proposal.
```idl
dictionary WebTransportSendStreamStats {
  DOMHighResTimeStamp timestamp;
  unsigned long long bytesPassedIn;
  unsigned long long bytesSentProgress;
  unsigned long long bytesSentAndAcknowledged;
  unsigned long long networkBytesSent;
};

dictionary WebTransportReceiveStreamStats {
  DOMHighResTimeStamp timestamp;
  unsigned long long bytesReceivedProgress;
  unsigned long long bytesHandedOut;
  unsigned long long networkBytesReceived;
};
```
If you can't tell which is which of the members, then I've failed.

bytesPassedIn >= bytesSentProgress >= bytesSentAndAcknowledged
networkBytesSent >= bytesSentProgress
networkBytesReceived >= bytesReceivedProgress >= bytesHandedOut

(Read backwards as "can't be more than")

**Comment by jan-ivar** [comment]
> Maybe consider s/bytesPassedIn/bytesWritten/ and s/bytesHandedOut/bytesRead/.

Winner. Let me edit my comment above immediately.

> networkBytes*

From my perspective, it's whatever health metric we decide to expose that isn't a stream progress counter. Happy to bikeshed.

**Comment by martinthomson** [comment]
For "networkBytes" I was trying to get at what you wanted to measure first.  Naming follows that decision.

If this is a count of the number of bytes of QUIC frames (or HTTP/2 frames) that were sent or received, then we might have a metric that can be produced.  The other metrics are far less possible.

I also wanted to caution that QUIC and HTTP/2 will behave very differently here; we'd want to be comfortable with that.

**Comment by jan-ivar** [comment]
Meeting:
- Some confusion over names. Maybe bytesWritten/bytesRead was less clear than hoped. Maybe the original bytesPassedIn/bytesHandedOut or bytesWrittenTo/bytesReadFrom ??
- Unclear if all three first ones are "Progress" conters, then why does only one of them have "progress" in the name.
- On networkBytes, do we need it at the streams level? Maybe not. Maybe if you're billing something? network "cost". also we won't have these numbers for HTTP/2. We could drop it on HTTP/2.
- Unconventional, not the way things are. bytesRetransmitted, and others. bytesTimeout.

**Comment by jan-ivar** [comment]
New bikeshed iteration:
```idl
dictionary WebTransportSendStreamStats {
  DOMHighResTimeStamp timestamp;
  unsigned long long amountWrittenTo;
  unsigned long long sentProgress;
  unsigned long long acknowledgedProgress;
};

dictionary WebTransportReceiveStreamStats {
  DOMHighResTimeStamp timestamp;
  unsigned long long amountReadFrom;
  unsigned long long receivedProgress;
};
```
They're all stream progress counters, in bytes, which is what the API streams vend. By intentionally avoiding "bytes" in the name, my hope is to avoid confusion over what layer "bytes" are measured (we don't expose any deeper measurements of underlying network traffic at this level).

amountWrittenTo >= sentProgress >= acknowledgedProgress
receivedProgress >= amountReadFrom

**Comment by jan-ivar** [comment]
Meeting:
- Agree with last meeting, modulo no progress on To/From bikeshedding

**Comment by jan-ivar** [comment]
@martinthomson does this LGTY, or should we keep bikeshedding?
