### ISSUE TITLE
Break out stats on retransmits

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webtransport#373]
At TPAC I proposed we [break out stats numbers from retransmits](https://docs.google.com/presentation/d/1SG1FUvn9UKGx_gAqWnCzPHlsIXkDUXctZPs7blfqS5k/edit?pli=1#slide=id.gf66ea8b320_2_4). Discuss.

[bytesSent](https://w3c.github.io/webtransport/#dom-webtransportstats-bytessent) today: _“The number of bytes sent on the QUIC connection, including retransmissions. Does not include UDP or any other outer framing.”_

### Proposal:
```idl
partial dictionary WebTransportStats {
  unsigned long long bytesRetransmit;
  unsigned long long packetsRetransmit;
};
```
...and either
- A: Exclude them from bytesSent, or
- B: Still include them in bytesSent

Any preference?

**Comment by martinthomson** [comment]
WFM

**Comment by jan-ivar** [comment]
Meeting:
- On naming: maybe just `packetsLost` since the networkBytes* pattern in per-stream stats didn't pan out.
