### ISSUE TITLE
Block source (incoming) ports

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webtransport#376]
Follow-up to https://github.com/w3c/webtransport/issues/229#issuecomment-976698856.

**Comment by jan-ivar** [comment]
@ricea could you help clarify the issue here around "source" ports? I'm not sure I captured it well in the meeting notes what the specific attack vector here is.

**Comment by jan-ivar** [comment]
Meeting:
- Is this an attack on the router?

**Comment by ricea** [comment]
Sorry I didn't respond before the meeting. The attack consists of tricking the router into automatically creating a port forward, which can then be used by a host on the Internet to attack hosts on the internal network.

**Comment by DavidSchinazi** [comment]
Unlike destination ports, source ports aren't under control of the JavaScript. Is the assumption here that JavaScript would open many WebTransport sessions in the hope that one of them would eventually land on a source port that a router would react poorly to?

**Comment by ricea** [comment]
> Unlike destination ports, source ports aren't under control of the JavaScript. Is the assumption here that JavaScript would open many WebTransport sessions in the hope that one of them would eventually land on a source port that a router would react poorly to?

Yes, although our connection throttling will make this quite time-consuming.

**Comment by DavidSchinazi** [comment]
Given that we have connection throttling, do we need to do anything more?

**Comment by ricea** [comment]
> Given that we have connection throttling, do we need to do anything more?

I'd like to say "no", but hackers are very persistent. Maybe they'll use DNS to tie up the rest of the sockets. Or WebRTC. Or something else I don't know about.

**Comment by DavidSchinazi** [comment]
Mitigating this sounds reasonable to me, but it applies to all HTTP/3 connections, not just WebTransport. I don't think anything needs to be done for WebTransport specifically.

**Comment by ricea** [comment]
> Mitigating this sounds reasonable to me, but it applies to all HTTP/3 connections, not just WebTransport. I don't think anything needs to be done for WebTransport specifically.

I'm very much in favour of delegating this to the HTTP/3 standard if that is an option!

**Comment by LPardue** [comment]
The H3 spec is in AUTH48 now, too late to consider adding considerations like this. 

Furthermore, this problem doesn't even sound specific to H3 but any application that uses QUIC. The applicability draft just went to IETF last call, it already contains a section on source port selection - https://datatracker.ietf.org/doc/html/draft-ietf-quic-applicability-14#section-8.1. If there's a consideration to capture, that section seems most appropriate to me.

**Comment by jan-ivar** [comment]
Meeting
- Martin: No-one creates a connection with a source port < 1024? Anything in that range is straightforward to block
- Are some > 1024? It's going to be hard to avoid those in the ephemeral range in implementations.
- David: some OSes give non-ephemeral ports 1024-16k might be registered by IANA?
- Attack isn't specific to WebTransport. Maybe we don't need to say anything?
- Lean on UDP aspects of fetch block list?
- Conclusion: group seems to think there's nothing unique to WebTransport here. Maybe just reference fetch in the security considerations.
- Maybe track an issue on the fetch spec.

**Comment by jan-ivar** [comment]
@ricea at last meeting someone suggested we should open an issue on the fetch spec, but I also see LPardue suggesting this is related to QUIC not HTTP/3. Do you agree this could be dealt with in the fetch spec, and if so can you open an issue there? Thanks.

**Comment by jan-ivar** [comment]
@ricea friendly ping ^

**Comment by ricea** [comment]
Sorry I didn't respond, I'm not actually sure what the right answer is. My current thinking is that non-browser QUIC clients probably do not need to implement port blocking. So we can put it in the fetch spec.

**Comment by jan-ivar** [comment]
@ricea has an issue been opened on the fetch spec, do you know? Can we close this?

**Comment by nidhijaju** [comment]
I think https://github.com/whatwg/fetch/issues/1268 covers this for the fetch spec already, so we can probably close this issue.
