### ISSUE TITLE
WPT's echo server not available for webplatform tests run by wpt.live 

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webtransport#381]
Tracking issue.

**Comment by yutakahirano** [comment]
@bashi FYI

**Comment by aboba** [comment]
Question: have there been any protocol changes recently?  Am having problems bringing up a WebTransport connection with the aioquic server (for counter or echo tests).

**Comment by yutakahirano** [comment]
I'm not sure if this is related but there was a change in WebTransport support of aioquic. Please see https://github.com/aiortc/aioquic/pull/251 and https://github.com/GoogleChrome/samples/pull/764 for the context.

**Comment by jan-ivar** [comment]
The issue here is that tests fail when run in the local browser. E.g.  https://wpt.live/webtransport/connect.https.any.html
```
promise_test: Unhandled rejection with value: object "WebTransportError: Opening handshake failed."
```

**Comment by yutakahirano** [comment]
webtransport server has never been available on wpt.live. That should be different from "any protocol changes" @aboba mentioned above.

**Comment by aboba** [comment]
FWIW, there is an echo server running on https://webrtc.internaut.com:6161/echo

**Comment by jan-ivar** [comment]
Multiple other servers are available for testing at this point, so this situation has improved to where this isn't an issue.
