### ISSUE TITLE
Cap on 1024 bytes in closeInfo.reason risks clipping multi-byte UTF8 sequence

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webtransport#382]
From https://github.com/w3c/webtransport/pull/379/files#r764122061

**Comment by yutakahirano** [comment]
We have a test case[1] for this. The test expects implementations to send a valid utf-8, and I think we need to fix the spec text accordingly.

1: https://github.com/web-platform-tests/wpt/blob/master/webtransport/close.https.any.js#L54

**Comment by annevk** [comment]
I wonder if this requires some kind of abstraction for https://encoding.spec.whatwg.org/#dom-textencoder-encodeinto. The U+FFFD replacement technique in the test cannot really be used as that would not allow for having an actual U+FFFD at the end. Though maybe you could compensate for that by checking the actual bytes?

**Comment by yutakahirano** [comment]
I was imagning something more implicit, such as:

> Let |reasonString| be the maximal [=code unit prefix=] of |closeInfo|.{{WebTransportCloseInfo/reason}} where the [=byte sequcne/length=] of the [=UTF-8 encoded=] prefix doesn't exceed 1024.
> Let |reason| be |reasonString|, [=UTF-8 encoded=].

**Comment by annevk** [comment]
I think that works. Maybe just make it a loop?

**Comment by yutakahirano** [comment]
Sure. I'd like to avoid loop, given the implicit definition is clear enough.
