### ISSUE TITLE
Is connection pooling off the right default?

### ISSUE THREAD

**Issue by martinthomson** [w3c/webtransport#393]
This came up during the last meeting.  In a discussion about the long-term defaults, @yutakahirano asked whether the decision to not pool connections by default was the right answer.

This is an issue that might be important to resolve now, because while we have a small number of early adopters, a change to the defaults might be possible.

There are perhaps two ways of thinking about this:

1. WebTransport is just an HTTP request that unlocks new capabilities.  In that context, pooling by default makes sense.
2. The way people will use WebTransport is closer to how WebSockets are used, which generally involves little of the infrastructure of HTTP and tends toward dedicated connections.  In that view, pooling is rarely wanted and so disabling it by default is better.

There are probably a few practical issues to consider here, such as whether regular HTTP connections are created with the various extensions (datagrams, connect-protocol) enabled.  My view there is that things will likely work better if clients advertise these capabilities always, but I realize that might not be a widely held viewpoint.

To answer for Mozilla, we're likely OK with either outcome, but our intent was to implement as currently specified: with pooling disabled by default.  That's part of the implementation we haven't built yet, so we might be flexible.  /cc @ddragana

**Comment by aboba** [comment]
Comments below.

> On Mar 2, 2022, at 15:19, Martin Thomson ***@***.***> wrote:
> There are probably a few practical issues to consider here, such as whether regular HTTP connections are created with the various extensions (datagrams, connect-protocol) enabled. My view there is that things will likely work better if clients advertise these capabilities always, but I realize that might not be a widely held viewpoint.
> 
[BA] Requiring ordinary HTTP connections to support QUIC datagrams is likely to cause interop issues. 
> To answer for Mozilla, we're likely OK with either outcome, but our intent was to implement as currently specified: with pooling disabled by default. That's part of the implementation we haven't built yet, so we might be flexible. /cc @ddragana
> 

[BA] The currently specified behavior is safest, IMHO.

**Comment by jan-ivar** [comment]
Meeting:
* connection pooling off is likely the way most people will deploy
