### ISSUE TITLE
Q: When does writer.write() resolve?

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webtransport#402]
[Write](https://w3c.github.io/webtransport/#webtransportsendstream-write) says: _"[Send](https://w3c.github.io/webtransport/#stream-send) bytes on stream.[[[InternalStream]]](https://w3c.github.io/webtransport/#dom-webtransportsendstream-internalstream-slot) and wait for the operation to complete."_
[Close](https://w3c.github.io/webtransport/#webtransportsendstream-close) says: _"[Send](https://w3c.github.io/webtransport/#stream-send) FIN on stream.[[[InternalStream]]](https://w3c.github.io/webtransport/#dom-webtransportsendstream-internalstream-slot) and wait for the operation to complete."_

But when is "the operation" "complete"? [Section 2.2](https://datatracker.ietf.org/doc/html/draft-ietf-quic-transport#section-2.2) doesn't say AFAIK. Is it when:
 1. The data has been handed off to some lower-level network queue for sending?
 2. The data has left the network card (once)?
 3. An ACK for this data has been received?

I can reason myself to an answer:
 - when it can no longer fail (3)

But we should perhaps write this down.

**Comment by jan-ivar** [comment]
Meeting:
- For datagrams the answer (in Chrome) appears to be 1
- For streams, we're not sure yet.

**Comment by jan-ivar** [comment]
Meeting:
- For write, the answer seems to be 1. The data has been handed off to some lower-level network queue for sending
- For close the algorithm also waits on _"Wait for stream.[[[InternalStream]]](https://w3c.github.io/webtransport/#dom-webtransportsendstream-internalstream-slot) to enter the "Data Recvd" state"_

**Comment by aboba** [comment]
After removing the `await` before `writer.write(chunk)` in the WebCodecs echo sample, latency went down and reordering was observed on the receiver.  This is consistent with handoff to a lower-level network queue, but it is also indicates that `await writer.write()` is sub-optimal. We should demonstrate the recommended approach in examples and sample code.

**Comment by ricea** [comment]
As a general rule it's better to `await writer.ready` rather than `await writer.write()` but I'm not sure how much difference it will make here.

**Comment by aboba** [comment]
In practice, it seems to make a substantial difference. `await writer.write` or even `await writer.close()` appears to preclude concurrency (the interleaving of sends on multiple streams).

**Comment by jan-ivar** [comment]
I think this is expected. `writer.ready` is expected to resolve ahead of `writer.write`. The former is the one producers are meant to use for back pressure. I don't think this necessarily indicates any problem with our `writer.write` algorithm.

**Comment by jan-ivar** [comment]
The problem here was `await`ing `write()` (instead of `.ready`). We should update [Example 4](https://w3c.github.io/webtransport/#example-sending-stream) to not `await` `write()`.

The [streams spec](https://streams.spec.whatwg.org/#example-manual-write-dont-await) also cautions not to await write.
