### ISSUE TITLE
Review Framework for Accessibility in the Specification of Technologies (FAST) checklist

### ISSUE THREAD

**Issue by wilaw** [w3c/webtransport#405]
Checklist is available at https://w3c.github.io/apa/fast/checklist.html

**Comment by wilaw** [comment]
Co-chair call notes:
1. For [10], agree that we do not need labels as we do not create DOM objects. 
2. For [17], the API does not create structured content.
3. For [18], we expose a transport protocol to applications. Our protocol operates on bytes, so any content would need to be application encoded and decoded.

**Comment by ruoxiran** [comment]
Quick confirmation from APA WG, are you referring to this document https://w3c.github.io/webtransport/ ?

**Comment by wilaw** [comment]
@ruoxiran  - yes, we are referencing https://w3c.github.io/webtransport/

**Comment by ruoxiran** [comment]
no comment or request from APA WG.
