### ISSUE TITLE
Rewrite the text of the specification to be independent of the underlying transport

### ISSUE THREAD

**Issue by vasilvv** [w3c/webtransport#408]
Currently, we refer quite a bit to specific QUIC operations.  In order to support both H/2 and H/3, we should switch to referencing <https://www.ietf.org/archive/id/draft-ietf-webtrans-overview-04.html#name-transport-features>

**Comment by nidhijaju** [comment]
Filed https://github.com/ietf-wg-webtrans/draft-ietf-webtrans-overview/issues/12 and https://github.com/ietf-wg-webtrans/draft-ietf-webtrans-http2/issues/95 to update IETF documents needed to be able to replace the rest of the protocol-specific language in our spec.
