### ISSUE TITLE
"QUIC Protocol Action" in #protocol-mapping is misleading

### ISSUE THREAD

**Issue by yutakahirano** [w3c/webtransport#410]
In https://w3c.github.io/webtransport/#protocol-mapping, we have a table with "QUIC Protocol Action" column. For example, the table maps "writable.abort(errorCode)" to "send RESET_STREAM with errorCode". This is misleading because we have an error code conversion logic at https://datatracker.ietf.org/doc/html/draft-ietf-webtrans-http3/#section-4.3, and QUIC protocol sees the converted number.

**Comment by jan-ivar** [comment]
Meeting:
- Don't use same "errorCode" name on both sides
