### ISSUE TITLE
Abort reason should be serialized

### ISSUE THREAD

**Issue by noamr** [w3c/webtransport#412]
Currently in https://w3c.github.io/webtransport/#webtransportreceivestream-create we:
Let cancelAlgorithm be an action that [cancels](https://w3c.github.io/webtransport/#webtransportreceivestream-cancel) stream with reason, given reason, and [Set up with byte reading support](https://streams.spec.whatwg.org/#readablestream-set-up-with-byte-reading-support) stream with [pullAlgorithm](https://streams.spec.whatwg.org/#readablestream-set-up-with-byte-reading-support-pullalgorithm) set to pullAlgorithm and [cancelAlgorithm](https://streams.spec.whatwg.org/#readablestream-set-up-with-byte-reading-support-cancelalgorithm) set to cancelAlgorithm.

However, in the [stream spec](https://streams.spec.whatwg.org/#other-specs-rs-create) the reason is never passed from `cancelAlgorithmWrapper `. Maybe this should be fixed in the streams spec?

See https://github.com/whatwg/fetch/pull/1343

**Comment by ricea** [comment]
Yes, it appears to be a bug in the streams spec.

**Comment by jan-ivar** [comment]
Meeting:
- We don't think we need to do anything on the WebTransport side. Please comment and we can reopen if this is not the case.
