### ISSUE TITLE
Samples

### ISSUE THREAD

**Issue by aboba** [w3c/webtransport#416]
Would be useful to have a directory with samples.

**Comment by wilaw** [comment]
It would also be useful to have a page which links to hosted versions of the various samples. This we could mount either as part of our readme, or use the wiki functionality of github to host a samples reference page?

**Comment by aboba** [comment]
I added links on the Readme page.

**Comment by aboba** [comment]
Do we consider this to be resolved now?

**Comment by wilaw** [comment]
Chairs consider resolved. Thank you for your sample additions.
