### ISSUE TITLE
Consider aligning WebTransportError with upcoming guidance

### ISSUE THREAD

**Issue by domenic** [w3c/webtransport#425]
In https://github.com/whatwg/webidl/pull/1211, we're attempting to give guidance on how to subclass DOMException, in a similar way to what WebTransportError does. However, our guidance differs from what you've done in the constructor signature, which it suggests would be `(message, options)` instead of putting `message` inside `options`.

We also have some shorthands which can let you avoid creating your own "set up" and "create" operations, which might be nice.

Is it too late to change the constructor signature for WebTransportError? It's a small surface thing, so I don't really want to cause people to do a lot of compat work if it's already shipping and being used extensively. But I thought it'd be worth asking...

**Comment by jan-ivar** [comment]
@ricea does this SGTY?

**Comment by jan-ivar** [comment]
> ```js
> writable.abort(new WebTransportError({streamErrorCode: WT_CODE}));
> ```
> 
> will create a `WebTransportError` object with a `message` of `"[object Object]"` and a null `streamErrorCode`.

Won't it throw, since `{streamErrorCode: WT_CODE}` isn't a DOMString?

**Comment by ricea** [comment]
> Won't this be `TypeError`, since `{streamErrorCode: WT_CODE}` isn't a DOMString?

Almost anything is convertible to DOMString: https://webidl.spec.whatwg.org/#es-DOMString

**Comment by jan-ivar** [comment]
Meeting:
- @jan-ivar leaning towards fixing it.

**Comment by jan-ivar** [comment]
I suggest we make a decision on this at next meeting.

**Comment by jan-ivar** [comment]
Meeting:
- No objections
