### ISSUE TITLE
Do we need to specify default send behavior for web compat?

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webtransport#428]
At TPAC, I presented [slides](https://docs.google.com/presentation/d/141lSOntrraY3FACjIMqad0NlrYgKjEzrK-txxY2JpjI/edit#slide=id.g1532c26172c_1_8) that asked if we need to specify default send behavior. Here's that issue:
> Today the UA decides which writables to send from next to the server
> 
> Here’s a [simple file upload fiddle](https://jsfiddle.net/jib1/z965juL7/). If I pick two equally sized files, it shows Chrome
giving equal time (flow) to each upload stream:
> 
> <img width="618" alt="image" src="https://user-images.githubusercontent.com/3136226/196797670-a5c4d1f2-04f3-417f-b5c9-06e6c27ab62b.png">
> 
> Add a third file (send-stream) and it reduces all send-rates to be equal AFAICT.
This reasonable behavior is [implementation-defined](https://infra.spec.whatwg.org/#implementation-defined), which seems nuts. A poor foundation to build JS-setable priorities on top of? — Should we specify this?

Logically, use cases probably fall in one of 3 categories:
1. My use case works regardless of how UAs prioritize sending of my multiple streams
2. My use case requires new APIs to control priorities https://github.com/w3c/webtransport/issues/62
2. My use case relies on the default behavior as observed in Chrome right now

It sounds like it'll be a while until we address 2, but what about 3?

As pointed out in https://github.com/w3c/webtransport/issues/426, apps may come to rely on browsers' send behaviors, and even deadlock over them.

**Comment by pthatcher** [comment]
I think we should say something like "streams of equal priority are sent at equal rates", and the default (if priority is unset) is that streams have equal priority.

**Comment by jan-ivar** [comment]
I like that, although there's a subtlety about whether that means:
1. streams of equal priority are sent at equal rates, and the default (if priority is unset) is that steams are sent at equal rates with other streams regardless of priority
2. streams of equal priority are sent at equal rates, and the default (if priority is unset) is 0 (or some other constant)

I touch on this in https://github.com/w3c/webtransport/issues/431#issuecomment-1323753217 which would favor 1 if we go with that.

**Comment by aboba** [comment]
The default algorithm may have side effects.  In the diagrams below, both charts were created with an average bandwidth target of 1 Mbps, using AV1 @ full-hd resolution.  

In the [WebCodecs echo sample,](https://webrtc.internaut.com/wc/wtSender8/) here is the frame RTT chart when using `await writer.close()`: 

![image](https://user-images.githubusercontent.com/808811/203343709-6e9d8791-083a-4e4e-804f-2bf379c79a55.png)

[In a modified sample](https://webrtc.internaut.com/wc/wtSender7/), here is the frame RTT chart when using `writer.close().then()`: 

![image](https://user-images.githubusercontent.com/808811/203344503-6ca8f88b-d0b2-4fad-952e-c88f0db149f8.png)

The frame RTT steadily grows until it exceeds 2000+ ms. At the maximum frame RTT, this implies that there are 60+ open streams (2 x 30 fps). How does the default algorithm deal with that? By restricting the bandwidth of a new open stream to 1/60 of the available bandwidth??

**Comment by jan-ivar** [comment]
Meeting:
- streams of equal priority that have data to send.
