### ISSUE TITLE
Draining WebTransport connections

### ISSUE THREAD

**Issue by aboba** [w3c/webtransport#432]
Within the API, how does a peer learn that creating new streams is no longer wanted (and possibly that they should move to a new connection to do that)? 

Related: https://github.com/ietf-wg-webtrans/draft-ietf-webtrans-http3/pull/79

**Comment by jan-ivar** [comment]
https://github.com/ietf-wg-webtrans/draft-ietf-webtrans-http3/pull/79 says: "Both endpoints can continue sending data on existing streams and datagram flows," so how does this drain anything?

It continues: _"but SHOULD attempt to gracefully terminate the session as quickly as possible."_ but how? What does that mean?

**Comment by wilaw** [comment]
What API surface would make sense here? An event on the WebTransport connection perhaps? Or if the client is going to initiate the drain, then there also needs to be a drain() method against the WT connection.

**Comment by jan-ivar** [comment]
Can more than one DRAIN_WEBTRANSPORT_SESSION be sent or received?

**Comment by pthatcher** [comment]
Should we simply add "transport.draining" just like we have "transport.closed", which is a promise that resolves when the transport is being drained?

(I like .goingAway or .goingToClose or .closing more, but we should probably match the naming of the IETF spec).

**Comment by jan-ivar** [comment]
Meeting:
- matching the IETF spec suggests "draining"

**Comment by aboba** [comment]
Note: IETF WEBTRANS Editors discussed https://github.com/ietf-wg-webtrans/draft-ietf-webtrans-http3/pull/79 . It appears that the term "endpoint" was not meant to apply to the browser, but to the application. 

The consensus seemed to be that the browser should not prevent the application from opening new streams; in frame/stream transport this would prevent sending.
