### ISSUE TITLE
Client initiated drain

### ISSUE THREAD

**Issue by wilaw** [w3c/webtransport#436]
As noted in #432 , per [IETF](https://github.com/ietf-wg-webtrans/draft-ietf-webtrans-http3/pull/79
)  a client may send a DRAIN_WEBTRANSPORT_SESSION signal to a server, to indicate that the server SHOULD NOT initiate new WebTransport streams or datagram flows.

Do we need a wt.drain() method to initiate this signal? 

Would write() and stream creation methods work after drain() has been called?

**Comment by wilaw** [comment]
With the existing API, the client can stop accepting incoming streams. However it cannot stop the server from sending data across existing streams. The client can close() the existing streams of course, but then it risks losing data in flight.

**Comment by aboba** [comment]
This sounds like a "graceful shutdown" use case, where the client is asking the server to finish the existing work but not initiate new work, so that the client can take care of the data in flight (e.g. write it to stable storage) and then close the session. 

It does lead me to wonder how quickly the server is expected to wrap things up.  Should the server stop sending immediately, or can it continue to a logical break point (e.g. finish sending the current video, but don't keep sending more videos after that)?

**Comment by wilaw** [comment]
The IETF definition is intentionally vague on the timing question, with a SHOULD to "gracefully terminate the session as quickly as possible". 

> To drain a WebTransport session, either endpoint can send a DRAIN_WEBTRANSPORT_SESSION capsule. An endpoint SHOULD NOT initiate new WebTransport streams or datagram flows after sending or receiving a DRAIN_WEBTRANSPORT_SESSION capsule. Both endpoints can continue sending data on existing streams and datagram flows, but SHOULD attempt to gracefully terminate the session as quickly as possible.

We could use similar language and guidance if we do want to implement a drain() method.

**Comment by aboba** [comment]
@vasilvv Do you have an opinion on this?

**Comment by aboba** [comment]
Section 4.6 of WebTransport over HTTP/3 (https://www.ietf.org/archive/id/draft-ietf-webtrans-http3-04.html#name-interaction-with-http-3-goa) now covers the HTTP/3 GOAWAY frame. When sent from the server -> client this indicates that client attempts to construct additional WebTransport objects will fail. 

Does receipt of a GOAWAY frame need to be indicated to the application, or can it just deal with a (future) constructor error? 

Neither the WebTransport over HTTP/3 nor the WebTransport over HTTP/2 specifications discuss additional draining signals. 

So I'm left wondering what specification changes we need, if any.

**Comment by jan-ivar** [comment]
So questions:
- Is this just a synchronous `drain()` method that sends the capsule each time?
  - If called a million times does it send 1) one time, 2) a million times? Up to UA?
- Is the method idempotent or throw if called again?
- Should we add a new state called "draining"?
- Should this "draining" state block new stream creation?

**Comment by vasilvv** [comment]
> Is this just a synchronous drain() method that sends the capsule each time?

We only handle incoming DRAIN capsule once, so it would make to send one only once. We could make it return a promise, but I am not sure what users would do with it.

> Is the method idempotent or throw if called again?

Idempotent should have better ergonomics.

> Should we add a new state called "draining"?

Unlike HTTP, we don't really alter connection behavior upon draining signal, so I'm not sure that's necessary.

> Should this "draining" state block new stream creation?

HTTP does that. I think we should avoid that, since that makes some assumptions about how the application works that are not necessary.

**Comment by jan-ivar** [comment]
This seems like something that would be nice but not necessary, but It exists in IETF so we should probably expose it.

**Comment by jan-ivar** [comment]
> We only handle incoming DRAIN capsule once, so it would make to send one only once. ...

If DRAIN is only sent once, what guarantee is there that the server received it?

**Comment by jan-ivar** [comment]
Meeting:
- Drain is over the control stream which is reliable.
- Ready for PR

**Comment by jan-ivar** [comment]
Based on https://github.com/w3c/webtransport/issues/436#issuecomment-1325589571 and _"either endpoint can send a DRAIN_WEBTRANSPORT_SESSION capsule"_ the likely API need here is something like:
```js
wt.drain();
await wt.draining; // will resolve in the next task
// we are now in "draining" state.
```
...probably with something like:
- If transport.[[[State]]](https://w3c.github.io/webtransport/#dom-webtransport-state-slot) is "closed" or "failed", return a new [rejected](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-promise-objects) promise with an [InvalidStateError](https://webidl.spec.whatwg.org/#invalidstateerror).

@nidhijaju do you have cycles to add something like this? Or we can reassign.

**Comment by ekinnear** [comment]
>> Should we add a new state called "draining"?

> Unlike HTTP, we don't really alter connection behavior upon draining signal, so I'm not sure that's necessary.

>> Should this "draining" state block new stream creation?

> HTTP does that. I think we should avoid that, since that makes some assumptions about how the application works that are not necessary.

It feels weird that we don't block new stream creation upon `draining`. I know in the IETF spec we said this was "up to the application", which I guess is fine, but did we mean the website itself or did we mean the browser/JS layer here?

If we mean the actual website itself, why can't it just send its own message to signal draining, i.e. why specify a capsule/JS API at all?

**Comment by aboba** [comment]
| It feels weird that we don't block new stream creation upon draining. I know in the IETF spec we said this was "up to the application", which I guess is fine, but did we mean the website itself or did we mean the browser/W3C spec here?

In this case, I think we're talking about the Javascript application. 

| If we mean the actual website itself, why can't it just send its own message to signal draining, i.e. why specify a capsule/API at all?

The application could send its own message. Assuming that the proposed API has no effect on UA behavior (e.g. no blocking of new stream creation), they seem equivalent.  Perhaps this is about convenience? (e.g. saving the JS client application from needing to write their own drain() method, supporting a node application receiving a [DRAIN_WEBTRANSPORT_SESSION](https://www.w3.org/TR/webtransport/#session-signal-drain_webtransport_session) frame.

**Comment by martinthomson** [comment]
I'm with @ekinnear here.  HTTP has a GOAWAY frame because HTTP is an application protocol and people use HTTP directly.  However, we didn't add that capability to QUIC, so why would we add it here?  (CONNECTION_CLOSE is not a graceful shutdown mechanism, it's an abrupt termination signaling mechanism, for error conditions.)

That line of thinking is making me less than enthusiastic about DRAIN_WEBTRANSPORT_SESSION.  If the intermediate stack layers (the browser) can't act on the signal in a meaningful way, then it's not a useful signal at that layer.

**Comment by aboba** [comment]
Opened https://github.com/ietf-wg-webtrans/draft-ietf-webtrans-http3/issues/167

**Comment by jan-ivar** [comment]
Meeting:
- No strong interest in this meeting
- Might a use cases be proxies, need a way to reboot? Folks to reach out to @afrind

**Comment by jan-ivar** [comment]
Someone with a use case should reopen this.
