### ISSUE TITLE
Is WebTransport compatible with Node.js QUIC?

### ISSUE THREAD

**Issue by ArckyPN** [w3c/webtransport#439]
Hi,
I am trying to establish a connection between a server running the QUIC implementation on Node.js [v15.0.0pre ](https://github.com/nodejs/quic) and a client using WebTransport.
Right now I am basically using the example code from the QUIC [repo](https://github.com/nodejs/quic/blob/master/doc/api/quic.md) and similarily the example code of [WebTransport](https://web.dev/webtransport/#connecting-to-a-server) and atm I am just waiting for the "ready" state and then log a message that the client is connected.
However, the connect is always refused. In Wireshark I can see that the client tries to connect a few times and eventually the message that the host in unreachable.
I have a feel if might have something to do with the ALPN option on the server, but I can't seem to figure it out.

**Comment by aboba** [comment]
This is a repository relating to the WebTransport API, not the WebTransport protocol (or implementations of it). 

To understand what is going wrong, you might want to look at the [WPT tests of the WebTransport API,](https://github.com/web-platform-tests/wpt/tree/master/webtransport) which are based on the aioquic python module.
