### ISSUE TITLE
Possible new wording for the implementation / testing criteria

### ISSUE THREAD

**Issue by ylafon** [w3c/webtransport#444]
Following https://lists.w3.org/Archives/Public/public-new-work/2022Oct/0000.html ,
Mozilla would like to amend the current text we have in the [charter](https://www.w3.org/2020/12/webtransport-wg-charter.html#success-criteria):
>In order to advance to [Proposed Recommendation](https://www.w3.org/Consortium/Process/#RecsPR), each specification is expected to have [at least two independent implementations](https://www.w3.org/Consortium/Process/#implementation experience) of each feature defined in the specification.
>
>Each specification should contain a section detailing any [known security and privacy implications](https://www.w3.org/TR/security-privacy-questionnaire/), and suggested mitigation strategies for implementers, web authors, and end users. The group should not publish a specification if acceptable mitigation strategies cannot be found.
>
>There should be testing plans for each specification, starting from the earliest drafts.
>
>To promote interoperability, all changes made to specifications after implementations emerge should have [tests](https://www.w3.org/2019/02/testing-policy.html).

With the following
> In order to advance to Proposed Recommendation, each normative
specification must have at least two independent interoperable
implementations of every feature defined in the specification, where
interoperability can be verified by passing open test suites, and two or
more implementations interoperating with each other. In order to advance to
Proposed Recommendation, each normative specification must have an open
test suite of every feature defined in the specification.

Which leads to the definition of what `interoperating` means in the case of this specification, and what the Working Group want to see being tested, the relationship with testing the IETF specification this spec rely on, etc...

Note that the possible new wording might appear in the status section of the specification (which is the scope of this issue).

**Comment by wilaw** [comment]
At meeting https://www.w3.org/wiki/WebTransport/Meetings#WebTransport_Bi-weekly_Virtual_Meeting_.2352_early_-_Dec_20.2C_2022, group agreed that we will leave charter language as-is, and will define web platform tests that test the interoperability between two or more different implementations communicating via a common relay server.

**Comment by jan-ivar** [comment]
The chairs have discussed adding a mention of this agreement in the spec itself, under SOTD.

**Comment by wilaw** [comment]
We will amend the next charter to reflect this language instead of modifying the spec.
