### ISSUE TITLE
Handling of negative values and 0 for incomingMaxAge

### ISSUE THREAD

**Issue by zcorpan** [w3c/webtransport#450]
https://w3c.github.io/webtransport/#dom-webtransportdatagramduplexstream-incomingmaxage says

> The setter steps are:
>
> 1. Let value be the given value.
> 2. If value is null or value > 0:
>    1. Set [this](https://webidl.spec.whatwg.org/#this).[[[IncomingDatagramsExpirationDuration]]](https://w3c.github.io/webtransport/#dom-webtransportdatagramduplexstream-incomingdatagramsexpirationduration-slot) to value.

So if value is 0, or negative, or NaN, the setter does nothing.

I would expect instead:

* 0 to be converted to null
* negative values and NaN throw

Similarly, https://w3c.github.io/webtransport/#dom-webtransportdatagramduplexstream-incominghighwatermark says

> 2. If value ≥ 0:
>    1. Set [this](https://webidl.spec.whatwg.org/#this).[[[IncomingDatagramsHighWaterMark]]](https://w3c.github.io/webtransport/#dom-webtransportdatagramduplexstream-incomingdatagramshighwatermark-slot) to value.

So negative and NaN are silently ignored (should throw?).

@jan-ivar also mentioned this:

> This is also interesting: "+∞ is explicitly allowed as a valid [high water mark](https://streams.spec.whatwg.org/#high-water-mark). It causes [backpressure](https://streams.spec.whatwg.org/#backpressure) to never be applied."
> So we may want `unrestricted double`  as well on the highWaterMark at least
> Maybe we should use RangeError too

**Comment by jan-ivar** [comment]
Makes sense to me.

**Comment by jan-ivar** [comment]
After pondering what to coerce 0 into, I decided to open https://github.com/w3c/webtransport/issues/463.

**Comment by wilaw** [comment]
Closed by #464
