### ISSUE TITLE
IncomingStreams pullUnidirectionStream algorithm

### ISSUE THREAD

**Issue by jesup** [w3c/webtransport#452]
Right now it states "1. If transport.[[[State]]](https://w3c.github.io/webtransport/#dom-webtransport-state-slot) is "connecting", then return the result of performing the following steps [upon fulfillment](https://webidl.spec.whatwg.org/#upon-fulfillment) of transport.[[[Ready]]](https://w3c.github.io/webtransport/#dom-webtransport-ready-slot):

        1. Return the result of [pullUnidirectionalStream](https://w3c.github.io/webtransport/#pullunidirectionalstream) with transport."

I think we need to state that we're returning a promise which will resolve (or be rejected) by running this again after we reach Ready OR rejected if state goes to FAILED or CLOSED

**Comment by jesup** [comment]
Same for pullBidirectionalStream

**Comment by jan-ivar** [comment]
> ... OR rejected if state goes to FAILED or CLOSED

I'm not sure this is necessary. These pull algorithms are [set up](https://streams.spec.whatwg.org/#readablestream-set-up) to be a ReadableStreamDefaultController's [[[pullAlgorithm]]](https://streams.spec.whatwg.org/#readablestreamdefaultcontroller-pullalgorithm), which is called by [streams machinery](https://streams.spec.whatwg.org/#readable-stream-default-controller-call-pull-if-needed), not direct JS API methods. Upon rejection, that machinery appears to [error the stream](https://streams.spec.whatwg.org/#readable-stream-default-controller-error) and little else.

Wherever we transition to "failed", our [cleanup](https://w3c.github.io/webtransport/#webtransport-cleanup) algorithm already [errors](https://streams.spec.whatwg.org/#readablestream-error) all the streams, so we shouldn't need to also detect and reject on that state transition here.

**Comment by ricea** [comment]
If the state transitions from "connecting" to "connected" to "closed" before we can perform the "upon fulfillment" steps, the promise returned from _pullAlgorithm_ will never resolve. However, as far as I can tell it won't make any observable difference.

Maybe just to be unambiguous it would be good to add an extra check on the state and reject the promise if the state is not "connected"?
