### ISSUE TITLE
The cleanup procedure is onconsistent with regards to arguments (closeInfo...)

### ISSUE THREAD

**Issue by jesup** [w3c/webtransport#454]
https://w3c.github.io/webtransport/#webtransport-procedures states that the cleanup procedure takes  "reason, error and a boolean abruptly", but it references "if closeInfo is given".  
This procedure is invoked in https://w3c.github.io/webtransport/#web-transport-termination via "[Cleanup](https://w3c.github.io/webtransport/#webtransport-cleanup) transport with error and closeInfo."   
In https://w3c.github.io/webtransport/#webtransport-constructor it's "[Cleanup](https://w3c.github.io/webtransport/#webtransport-cleanup) transport with error, error and true." and "[Cleanup](https://w3c.github.io/webtransport/#webtransport-cleanup) transport with error."    
https://w3c.github.io/webtransport/#webtransport-methods invokes it with 'error' or with "AbortError and closeInfo".

**Comment by jesup** [comment]
Also, cleanup says it takes reason, error, and abruptly, but it only uses error (and the non-referenced closeInfo)

**Comment by jesup** [comment]
And the 'error' above should be linked to WebTransportError (nit)

**Comment by jesup** [comment]
Related: close() says "9. [Cleanup](https://w3c.github.io/webtransport/#webtransport-cleanup) transport with [AbortError](https://webidl.spec.whatwg.org/#aborterror) and closeInfo."   Is AbortError here a WebTransportError (and if so, session or stream - I presume the code would be ABORT_ERR), or a plain DOMException?

**Comment by jan-ivar** [comment]
Thanks for spotting this. It's the result of a merge error from #391 that clobbered parts of #380.

See https://github.com/w3c/webtransport/commit/e3f77e5fd0ce9d2275631ad1d585c010354326f0#diff-5e793325cd2bfc452e268a4aa2f02b4024dd9584bd1db3c2595f61f1ecf7b985R902 (click "Load diff").

I'll draft a PR to restore #380.
