### ISSUE TITLE
WebTransportError setup algorithm incorrectly calls DOMException constructor

### ISSUE THREAD

**Issue by saschanaz** [w3c/webtransport#458]
https://w3c.github.io/webtransport/#webtransporterror-set-up

>2. Run [new DOMException(message, name)](https://heycam.github.io/webidl/#dom-domexception-domexception) constructor steps with error, message and "WebTransportError".

The constructor has two parameters but this passes three arguments.

**Comment by wilaw** [comment]
Fixed by #460
