### ISSUE TITLE
WebTransportError & DOMExceptions

### ISSUE THREAD

**Issue by jesup** [w3c/webtransport#459]
From Kagami when reviewing my patches to implement the cleanup/etc procedures:

The spec doesn't seem to pass source to DOMException constructor, and it seems name should be WebTransportError instead of the source name. https://w3c.github.io/webtransport/#webtransporterror-set-up

BTW the spec is wrong as it's passing 3 arguments when the constructor only have two parameters.

**Comment by wilaw** [comment]
Fixed by #460
