### ISSUE TITLE
Accept ∞ for incoming/outgoingHighWaterMark and incoming/outgoingMaxAge for consistency

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webtransport#463]
This [spec](https://w3c.github.io/webtransport/#duplex-stream) defines:
```idl
attribute long incomingHighWaterMark;
attribute long outgoingHighWaterMark;
```
Compare to the [streams](https://streams.spec.whatwg.org/#qs-api) spec, which uses:
```idl
unrestricted double highWaterMark;
```
...and [notes](https://streams.spec.whatwg.org/#qs-abstract-ops): _"+∞ is explicitly allowed as a valid [high water mark](https://streams.spec.whatwg.org/#high-water-mark). It causes [backpressure](https://streams.spec.whatwg.org/#backpressure) to never be applied."_

This seems consistent throughout streams APIs involved with backpressure, like [desiredSize](https://streams.spec.whatwg.org/#writablestreamdefaultwriter). Allowing ∞ to mean "never apply backpressure" seems useful — the workaround (a really high number) seems poor — and having consistency with the streams spec seems desirable.

Similarly, [this spec](https://w3c.github.io/webtransport/#duplex-stream) overloads nullable to mean "never expires" in two adjacent APIs:
```js
wt.datagrams.incomingMaxAge = null; // means ∞
wt.datagrams.outgoingMaxAge = null; // means ∞
```
...when it would seem natural to instead just express:
```js
wt.datagrams.incomingMaxAge = ∞;
wt.datagrams.outgoingMaxAge = ∞;
```
∞ would also be the default values for the latter two attributes.

This would also help solve what 0 should be coerced to #450.

**Comment by vasilvv** [comment]
I just noticed this.

> Similarly, [this spec](https://w3c.github.io/webtransport/#duplex-stream) overloads nullable to mean "never expires" in two adjacent APIs:
> wt.datagrams.incomingMaxAge = null; // means ∞
> wt.datagrams.outgoingMaxAge = null; // means ∞

This is incorrect.  The spec used to define incomingMaxAge/outgoingMaxAge set to null as "implementation-defined value", not "never expire".  In fact, the text for [sendDatagrams](https://w3c.github.io/webtransport/#senddatagrams) still says "If duration is null, then set duration to an implementation-defined value".

**Comment by jan-ivar** [comment]
I must have wrongly assumed the default was ∞. Thanks for catching that! I'll make them nullable again.
