### ISSUE TITLE
Use nested steps instead of "Return promise and run the remaining steps in parallel" pattern

### ISSUE THREAD

**Issue by saschanaz** [w3c/webtransport#466]
IMO it's harder to see which steps are in parallel at a glance, and per @domenic specs generally are getting away from that pattern.

**Comment by nidhijaju** [comment]
Agreed, I have some proposed text here: https://github.com/nidhijaju/webtransport/commit/7181ea5d3ee932d1f76598c04d5d4f4d854f08bd. I can start a PR, if that sounds good.

**Comment by saschanaz** [comment]
LGTM.
