### ISSUE TITLE
API behavior when opening a new stream is blocked

### ISSUE THREAD

**Issue by vasilvv** [w3c/webtransport#469]
Our current behavior that is specified in the draft is that whenever the stream limit is exceeded, the API returns a promise that is blocked until we receive a new MAX_STREAMS, upon which the stream is opened and the promise is resolved.

Chrome's current implementation apparently does not do that (it immediately rejects a promise).  I was working on fixing that, but then I realized that we probably should not allow the JS code to request infinitely many streams (in our implementation, this is problematic since the requests get buffered on the more privileged side of the stack).

I think the correct answer is to allow *some* amount of pending promises (1x currently open streams? 2x?), after which we should start rejecting new streams immediately.

**Comment by jesup** [comment]
So if I have 1 stream open, and need to open 5 more because someone just hit 'play', I can't, and have to pace myself to open them 1 (or a couple) at  time? I think that's going to cause all sorts of heartache.   And worse, a setup that work may suddenly fail to open streams because we closed a stream earlier.

**Comment by jesup** [comment]
If this only kicks in at (say) 100 open streams, it's far less of an issue, of course (it wasn't clear from the above; it seems to state this limit based on open streams applies independent of the server stream limit).

Video with stream-per-frame could create quite a few streams in a short period (though probably not more than hundreds, even for high-framerate video).   I'd also note that the cases where we'd hit this are pretty much edge-cases, and if the resources required to allow it aren't all that large, I'd err on the high side.

**Comment by ricea** [comment]
I don't think we should change the standard to work around the limitations in Chrome's implementation. Instead, Chrome should queue stream requests on the unprivileged side.

**Comment by ekinnear** [comment]
On the QUIC side, we've also been pushing to ensure that streams are generally "cheap", and that does seem to have been especially valuable for a number of media use cases. So even if you attempt to open 100 streams all at the same time, is it actually a problem if those promises don't resolve for a while?

**Comment by wilaw** [comment]
> So even if you attempt to open 100 streams all at the same time, is it actually a problem if those promises don't resolve for a while?

For a client sending frame-per-stream media at 30fps, if stream creation takes > 33ms, or even some meaningful fraction of that, it is going to fall behind. Especially true if user-agent has say a 100ms RTT to server and has to negotiate an increase in max streams before it can authorize new stream creation. We can anticipate media at 120fps which further exacerbates the consequences of any delay in stream creation.

**Comment by martinthomson** [comment]
I'm generally against doing anything here, similar to @ekinnear or @ricea.  Browsers don't generally do much to protect against memory exhaustion by JavaScript, but there are general mechanisms that would limit the ability of a site to obtain a gazillion promises.  We should lean on those.

To @wilaw's point, there are problems with stream limits and promise resolution performance, but those are orthogonal.  Ensuring that the request for a stream doesn't block unnecessarily is why we have #446.

**Comment by aboba** [comment]
Agree with Martin here. In frame/stream mode, a 1x or 2x restriction could restrain stream creation to the point of preventing effective use of QUIC. For example, consider an application that wants to be able to send an I-frame (30 packets in size) along with up to five P-frames (3 packets each). If you only permit 1x, this will only allow a single P-frame to be sent simultaneously along with the I-frame.  2x would only permit two P-frames to be sent simultaneously along with the I-frame.

**Comment by jan-ivar** [comment]
Meeting:
- do nothing
- performance will tank, which is #446
