### ISSUE TITLE
Reliability is always supports-unreliable

### ISSUE THREAD

**Issue by jesup** [w3c/webtransport#472]
There's currently no way for reliability to end up as anything other than "supports-unreliable" (step 17.4 sets it to that always when we're connected)

**Comment by jan-ivar** [comment]
Something like "If the connection is not an HTTP/3 connection, and the user agent supports HTTP/2 fallback (as specified in [IETF link goes here], set this to "reliable-only".

**Comment by ekinnear** [comment]
If we're matching the datatracker link we used for H3, that would be https://datatracker.ietf.org/doc/html/draft-ietf-webtrans-http2/
