### ISSUE TITLE
Rate control privacy considerations

### ISSUE THREAD

**Issue by martinthomson** [w3c/webtransport#478]
It is not immediately obvious, but exposing details of rate control has privacy implications.  Some of these are preexisting in ways that are probably not in scope for us to fix, even if we could.  We should at least be prepared to acknowledge them.

None of this is new information.  Sites can measure network capacity already, sometimes with very high fidelity.  All that needs is fetch, WebRTC, or any of the many other things we do with networking.  But we are providing an API with real-time (or close to it) performance and precision.  That could make measurements easier to take and more reliable.

## Details

The fundamental problem is that the available send rate is a resource that is shared between mutually distrustful entities.  Within a browser, there are multiple origins that each access the network.  In many situations, the available upstream and downstream capacity at the scope of a household (which approximates a user in many cases) is a relatively fixed resource where multiple applications compete for access.

Firstly, revealing the approximate total available capacity and RTT could be used as a fingerprint.

This is not a particularly reliable or good fingerprint, because we only provide the *current* available capacity.  On the other hand, network use tends to be sporadic and so sites might be able to assume exclusive use of the shared resource and thereby consider the value they get to be a reasonable approximation of the total.

Second, providing information about *current* available capacity also provides information about active use.  This provides sites with a means to correlate user activity across origins.

Let's say that you have two sites with independent user databases.  The sites want to learn which of the users of site A correspond to users of site B.  One site can coordinate to observe link capacity for multiple users and then have the other generate a spike of network load for certain users.  Any users with a corresponding reduction in capacity likely correspond with those users that were tested.

This sort of trick might work less well if the network bottleneck is close to a user.  For instance, it might not be possible to distinguish people from the same household who share an Internet connection.  Some network configurations will therefore never produce anything that is truly useful for correlation purposes.  But for the most part, network bottlenecks tend to be close to people, so many people will be susceptible to this.  Also, reducing the candidate set size is of some value as it opens up options for more targeted cross-site correlation tricks, like navigation tracking.

## Recommendations

I suggest that we write something about how exposing rate control information has these properties.  Referencing existing text would also be fine.  That text would go in security/privacy considerations.

Furthermore, as the problems here arise from concurrent access to the API from multiple sites, we might make some recommendations about removing or degrading access to sites that are not currently in the foreground or focus.

**Comment by jan-ivar** [comment]
@martinthomson would you like a stab at the copy?

**Comment by pthatcher** [comment]
The PR I wrote had a section on privacy that covered this issue to some amount of detail.  I'm sure it could be improved, but it was already there.

**Comment by pthatcher** [comment]
In my newest PR, I just left the value undefined when pooling is used: https://github.com/w3c/webtransport/pull/494

I know that doesn't resolve all of the issues you brought up, but I thought you'd like to know.
