### ISSUE TITLE
Clarify whether spec supports BYOB readers for Datagrams

### ISSUE THREAD

**Issue by jesup** [w3c/webtransport#480]
The spec includes no text supporting the use of BYOB readers for Datagrams (while it does have BYOB text for WebTransportReceiveStreams, which are byte-streams).   Datagrams always traffic in Uint8Arrays, not bytes, so BYOB readers should not work with them, I presume.   Note also that the current Datagram WPT tests use BYOB readers....

If they somehow should be supported, there will need to be  number of spec changes I think.

**Comment by ricea** [comment]
Sorry, this was a serious oversight by us (Chromium). We shipped BYOB support for datagrams without standardising the feature. We will prepare a PR for the spec ASAP.

**Comment by jan-ivar** [comment]
> Datagrams always traffic in Uint8Arrays, not bytes, so BYOB readers should not work with them, I presume

The streams [model](https://streams.spec.whatwg.org/#model) says they _can be_ byte streams (_"a byte stream might contain chunks consisting of 16 KiB [Uint8Array](https://tc39.es/ecma262/#sec-typedarray-objects)s"_, but they [aren't](https://w3c.github.io/webtransport/#webtransport-constructor): _"20. [Set up](https://streams.spec.whatwg.org/#readablestream-set-up) incomingDatagrams ..."_ calls [set up](https://streams.spec.whatwg.org/#readablestream-set-up), not [set up with byte reading support](https://streams.spec.whatwg.org/#readablestream-set-up-with-byte-reading-support)...

> (Chromium) ... shipped BYOB support for datagrams ...

One concern is whether "[byte reading](https://streams.spec.whatwg.org/#example-manual-read-bytes)" semantics gel with preserving datagram boundaries.

But looking at the [WPT/webtransport/datagrams.https.any.js](https://github.com/web-platform-tests/wpt/blob/6ed09904d89a672406b28360081ee48f6fefca51/webtransport/datagrams.https.any.js#L145), it looks like too-small BYOB buffers reject, which is good:
```js
  // Write datagrams of size 10, but only 1 byte buffer is provided for BYOB
  // reader. To avoid splitting a datagram, stream will be errored.
  const buffer = new ArrayBuffer(1);
  const [error, _] = await Promise.all([
    reader.read(new Uint8Array(buffer)).catch(e => {
      controller.abort();
      return e;
    }),
    write_large_datagrams(writer, signal)
  ]);
  assert_equals(error.name, 'RangeError');
}, 'Reading datagrams with insufficient buffer should be rejected.');
```

But in a real world case, how would a client know the max size of incoming datagrams?

Is JS expected to write fallback code on rejection to read without BYOB to get the length of the too-large datagram, and use that size going forward? If so, an example might be good.

> We will prepare a PR for the spec ASAP.

Thanks, looking forward to seeing how it specifies this!

**Comment by jan-ivar** [comment]
> `  // reader. To avoid splitting a datagram, stream will be errored.`

> Is JS expected to write fallback code on rejection to read without BYOB to get the length of the too-large datagram, and use that size going forward?

Hang on, if `wt.datagrams.readable` is [errored](https://streams.spec.whatwg.org/#readablestream-error), how would JS recover?

**Comment by martinthomson** [comment]
> But in a real world case, how would a client know the max size of incoming datagrams?

The QUIC datagram specification is enabled by [each endpoint specifying how large a datagram they can receive](https://datatracker.ietf.org/doc/html/rfc9221#name-transport-parameter).  So presumably we can expose an interface that sets this parameter (probably not a good idea) or at least reads it.

**Comment by LPardue** [comment]
In my experience, endpoints set the DATAGRAM max frame size value to the maximum (65535) because the effective maximum DATAGRAM frame size is always bounded by the QUIC packet size. 

which makes me wonder if WebTransport API already expose reaqding the the QUIC sending Path MTU size and/or the peer's max_datagram_frame_size? There seems an opportunity to offer some symmetry

**Comment by martinthomson** [comment]
A 64k BYOB reader buffer isn't an unbearable amount of data to reserve in a browser.  Though maybe web browsers could set a lower limit than 64k and avoid forcing the larger allocation.

**Comment by ricea** [comment]
> Hang on, if `wt.datagrams.readable` is [errored](https://streams.spec.whatwg.org/#readablestream-error), how would JS recover?

There's currently no way to recover except to open a new WebTransport connection. We could in principle add a `reset()` method to replace the streams with ones that are not errored, however in practice it is simpler for people just to use 64K buffers.

**Comment by ricea** [comment]
Thanks. @nidhijaju is going to take this on.
