### ISSUE TITLE
Final API shape of rate control feedback

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webtransport#481]
Last meeting we decided to merge https://github.com/w3c/webtransport/pull/421 with two open alternatives for final API shape, #470 and #471.

To compare them, looking at JS instead of WebIDL might help, so I filed this issue to discuss.

The only difference is where the periods go. #421:
```js
const wt = new WebTransport(url);
await wt.ready;
console.log(wt.rateControlFeedback.sendRate);
console.log(wt.rateControlFeedbackMinInterval);
wt.rateControlFeedbackMinInterval = 500;

await new Promise(r => wt.onratecontrolfeedback = r);
console.log(wt.rateControlFeedback.sendRate);
```
#470:
```js
const wt = new WebTransport(url);
await wt.ready;
console.log(wt.rateControlFeedback.sendRate);
console.log(wt.rateControlFeedback.minInterval);
wt.rateControlFeedback.minInterval = 500;

await new Promise(r => wt.onratecontrolfeedback = r);
console.log(wt.rateControlFeedback.sendRate);
```
#471:
```js
const wt = new WebTransport(url);
await wt.ready;
console.log(wt.rateControlFeedbackSendRate);
console.log(wt.rateControlFeedbackMinInterval);
wt.rateControlFeedbackMinInterval = 500;

await new Promise(r => wt.onratecontrolfeedback = r);
console.log(wt.rateControlFeedbackSendRate);
```

**Comment by jan-ivar** [comment]
How about shorter names? 
```js
const wt = new WebTransport(url);
await wt.ready;
console.log(wt.sendRate);
console.log(wt.sendRateFeedbackInterval);
wt.sendRateFeedbackInterval = 500;

await new Promise(r => wt.onsendratefeedback = r);
console.log(wt.sendRate);
```

**Comment by martinthomson** [comment]
`sendRateEstimate` and `sendRateInterval` perhaps?

**Comment by martinthomson** [comment]
More bike shed: s/interval/throttle/ ?

**Comment by jan-ivar** [comment]
Meetings:
- leaning toward short names and `sendRateEstimate` and `sendRateInterval`
- or `wt.sendRate.estimate` and `wt.sendRate.interval` and maybe `sendRate.onchange`?
- mt: value may update after every ACK
- why is sendRate not part of getStats?
- can stats include predictions? it is a form of estimate based on past data
- conclusion: change it to include sendRateEstimate in getStats()
-

**Comment by wilaw** [comment]
Closing in favor of #484
