### ISSUE TITLE
Add sendRateEstimate to getStats()

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webtransport#484]
From https://github.com/w3c/webtransport/issues/481#issuecomment-1449126622
> conclusion: change it to include sendRateEstimate in getStats()

**Comment by wilaw** [comment]
Implementation should address questions raised in #476

**Comment by pthatcher** [comment]
Do we really want major app behaviors like rate control to be based on stats?  I don't really care so much about whether it is or not; I just care about the value being in there at all.  But it does seem inconsistent with the general purpose of "stats".

BTW, Did I miss a meeting where this was discussed and decided on?

**Comment by jan-ivar** [comment]
This was discussed and decided at the [Feb 28 meeting](https://www.w3.org/wiki/WebTransport/Meetings2023#WebTransport_Bi-weekly_Virtual_Meeting_.2355_late_-_Feb_28.2C_2023) (minutes and recording). But we can discuss it at again next meeting if you'd like.

I think the general sentiment was that the app could poll for these metrics. Can you elaborate on the difference from stats? E.g. WebRTC stats has [targetBitrate](https://www.w3.org/TR/2020/CR-webrtc-stats-20200114/#dom-rtcoutboundrtpstreamstats-targetbitrate).

**Comment by pthatcher** [comment]
I have a PR: https://github.com/w3c/webtransport/pull/494
