### ISSUE TITLE
Request to add possibility to send messages within streams

### ISSUE THREAD

**Issue by lgrahl** [w3c/webtransport#49]
### Rationale

`DatagramTransport` only works for transports with a strict limitation of datagram's sizes. This doesn't work well for a revamp of e.g. `RTCDataChannel` and `WebSocket` which can transport messages of (virtually) arbitrary size. `DatagramTransport` also does not allow to send datagrams/messages within particular streams. Therefore, I'd like to propose a couple of changes (depends and leans on #46).

### Proposal

Boring boilerplate first:

```
interface UnidirectionalMessageStreamsTransport {
    Promise<SendMessageStream> createSendMessageStream (optional SendMessageStreamParameters parameters);
    ReadableStream<ReceiveMessageStream> receiveMessageStreams ();
};

interface BidirectionalMessageStreamsTransport {
    Promise<BidirectionalMessageStream> createBidirectionalMessageStream ();
    ReadableStream<BidirectionalMessageStream> receiveBidirectionalMessageStreams ();
};
```

```
[Exposed=Window]
interface BidirectionalMessageStream : WebTransportStream {
};

BidirectionalMessageStream includes OutgoingMessageStream;
BidirectionalMessageStream includes IncomingMessageStream;
```

```
interface SendMessageStream : WebTransportStream {
};

SendMessageStream includes OutgoingMessageStream;

interface ReceiveMessageStream : WebTransportStream {
};

ReceiveMessageStream includes IncomingMessageStream;
```

```
[Exposed=Window]
interface mixin OutgoingMessageStream {
    readonly attribute WritableStream<OutgoingMessage> writable;
    readonly attribute Promise<StreamAbortInfo> writingAborted;
    void abortWriting (StreamAbortInfo abortInfo);
};

[Exposed=Window]
interface mixin IncomingMessageStream {
    readonly attribute ReadableStream<IncomingMessage> readable;
    readonly attribute Promise<StreamAbortInfo> readingAborted;
    void abortReading (StreamAbortInfo abortInfo);
};
```

The interesting part comes with the definition of `OutgoingMessage` and `IncomingMessage`:

```
[Exposed=Window]
interface OutgoingMessage : WritableStream<Uint8Array> {
};

[Exposed=Window]
interface IncomingStream : ReadableStream<Uint8Array> {
};
```

Note: Abort reading/writing a message does not necessarily mean aborting the stream, but depending on the implementation, it might also abort the stream.

An alternative would be to use the [body mixin](https://fetch.spec.whatwg.org/#body-mixin):

```
[Exposed=Window]
interface OutgoingMessage : Body {
    void abort (DOMString reason);
};

[Exposed=Window]
interface IncomingStream : Body {
    void cancel (DOMString reason);
};
```

### Example Use Case: RTCDataChannelStream

Now, these interfaces could be used to improve `RTCDataChannel` in the following way:

```
partial interface RTCPeerConnection {
    Promise<RTCDataChannelStream> createDataChannelStream (USVString label, optional RTCDataChannelInit dataChannelDict);
    ReadableStream<RTCDataChannelStream> receiveDataChannelStream ();
}

[Exposed=Window]
interface RTCDataChannelStream {
    <relevant fields from RTCDataChannel here>
};

RTCDataChannelStream includes BidirectionalMessageStream;
```

I'd imagine this would work similarly well for `WebSocket`.

### Discussion

Following this terminology, it would make sense to rename `SendStream` to `SendByteStream`, `ReceiveStream` to `ReceiveByteStream`, `OutgoingStream` to `OutgoingByteStream`, `IncomingStream` to `IncomingByteStream`, `SendStreamParameters` to `SendByteStreamParameters`, etc. and the various method names correspondingly. That being said, I think it makes sense to incorporate the *type of stream* into the interface in general to avoid confusion in a dynamically typed language (*what kind of stream is this? a stream of bananas?*), so this is IMO a good idea to implement regardless of this proposal.

Using the body mixin for `OutgoingMessage`/`IncomingMessage` would be a more flexible API but might introduce more complexity, too. I also do not particularly like that it's a `ReadableStream` for both roles (when reading and when writing) and I don't really know if that would be an ergonomic approach for sending (at least when it comes to terminology, it's awkward). I'm also concerned that it would make piping harder. All of these concerns should be discussed before going with the latter suggestion.

Thoughts? I realise these changes and additions are quite substantial... if you think there's an easier way to achieve the same, let's discuss it.

/cc @ricea

**Comment by pthatcherg** [comment]
You can send messages one of two ways:

- One message per stream (something like https://github.com/w3c/webrtc-quic/blob/master/examples/quic-ws.js)

- By adding some framing inside of one stream (something like https://chromium.googlesource.com/openscreen/+/refs/heads/master/osp/go/messages.go#58)

Either way, this is something that can be done in JS on top of the existing API.  There is no need to bake the choice into the browser.

**Comment by lgrahl** [comment]
I don't want to go with either of these options and neither would it fully leverage the potential of the underlying transports of SCTP or WebSocket where message framing is being done by the transport.

**Comment by pthatcherg** [comment]
We already have APIs for SCTP and WebSocket that leverage the potential of the underlying transports.  If you want to make one message-based API that works for all of them, you can do so with a JS library on top of all of (WebSocket, RTCDataChannel, WebTransport).    There's really no need to bake it into the browser.

**Comment by lgrahl** [comment]
The current APIs for message-based transports we have are lacking. We have discussed this in length in https://github.com/w3c/webrtc-pc/issues/1732. The main issues are a lack of receiver-side flow control, significant memory pressure with large messages and bad throughput. None of these issues are fixable with a JS library on top of them.

**Comment by pthatcherg** [comment]
Oh, so what you want is to describe some mixins like WebTransport has that are implemented by the websocket protocol and SCTP, but not by QUIC (kind of like how the websocket protocol would not implement the datagram mixin)?

I suppose that could be an interesting idea, but it seems like it would only ever be applicable to WebSocket and SCTP, and WebSocket already has WebSocketStream and it is much more limited in what it can do than SCTP.   So it sound like this whole idea collapses down to proposing a better API for SCTP.

**Comment by lgrahl** [comment]
> Oh, so what you want is to describe some mixins like WebTransport has that are implemented by the websocket protocol and SCTP, but not by QUIC (kind of like how the websocket protocol would not implement the datagram mixin)?

Yep.

> I suppose that could be an interesting idea, but it seems like it would only ever be applicable to WebSocket and SCTP, and WebSocket already has WebSocketStream and it is much more limited in what it can do than SCTP.

All that's needed to support this interface is a message-based transport. `WebSocketStream` would probably only need wiring some API bits together once it does support full message-based transportation. As with the change from a custom API to WHATWG streams, the win, again, is platform consistency.

> So it sound like this whole idea collapses down to proposing a better API for SCTP.

My intend is to establish an abstract message-based transport interface that we can **also** use for a better data channel API.

**Comment by lgrahl** [comment]
> I think this is more relevant to [WebSocketStreams](https://docs.google.com/document/d/1La1ehXw76HP6n1uUeks-WJGFgAnpX2tCjKts7QFJ57Y/edit#) which are streams of message. I talked to Adam Rice about it and he said they may consider doing something like that (streams of messages and each message has a stream).

Agree it is more relevant for `WebSocketStreams` than for QUIC. But I think it would be a missed opportunity to not integrate this use case from the beginning as it requires some changes to the API. Making WebTransport an abstract message-based transport API for both streams and large datagram streams (i.e. streams of streams) would be a win from my perspective.

@ricea Any thoughts you want to add? :slightly_smiling_face:

**Comment by ricea** [comment]
There are good arguments for both of
* built-in message framing like WebSocket has
* leaving it to the application layer like QuicTransport does.

However, I think trying to support both paradigms in a single API is a recipe for confusion.

Not having messages in the API means that we don't need two levels of streaming, and I think that's the right choice.

**Comment by lgrahl** [comment]
I can see the value in not adding it right now since it would not be used immediately. Furthermore, there don't seem to be any inherent incompatibilities if a message stream API, as proposed above, would be added later. The only thing left of this proposal would then be to ensure that the interface names are precise enough. To quote:

> it would make sense to rename `SendStream` to `SendByteStream`, `ReceiveStream` to `ReceiveByteStream`, `OutgoingStream` to `OutgoingByteStream`, `IncomingStream` to `IncomingByteStream`, `SendStreamParameters` to `SendByteStreamParameters`, etc. and the various method names correspondingly. That being said, I think it makes sense to incorporate the _type of stream_ into the interface in general to avoid confusion in a dynamically typed language (_what kind of stream is this? a stream of bananas?_), so this is IMO a good idea to implement regardless of this proposal.

**Comment by jan-ivar** [comment]
Closing as deferred for potential future version.
