### ISSUE TITLE
Allow updating send order for streams

### ISSUE THREAD

**Issue by vasilvv** [w3c/webtransport#492]
We currently only allow sendOrder to be set whenever a stream is created.  This is limiting, since we don't get to change the priority of incoming streams.  I think we should add an `updateSendOrder()` method to deal with that.

**Comment by jan-ivar** [comment]
Meeting:
- We need this
- Bikeshedding on API
  - Do we want to keep things simpler for implementations?
  - stream.priority = n — keeps the API regular
  - what if you're running code divorced from where it was created
  - No other good alternatives come to mind
