### ISSUE TITLE
Define default send order

### ISSUE THREAD

**Issue by vasilvv** [w3c/webtransport#493]
We currently define that:

- Send order is optional
- If it's specified, streams with higher order go first
- If it's not, it's implementation-defined

This does not define what happens when two streams have the same order, and dealing with "int-or-undefined" order is annoying.  I propose to simplify this as:

- Send order is always defined, and is `0` if not specified
- If two streams have different orders, the one with higher order goes first
- If two streams have the same order, the ordering is implementation-defined.

This leaves the default case (no orders ever used) entirely implementation-defined, but provides well-defined behavior of how specified vs unspecified order is handled.

**Comment by valenting** [comment]
As I understand it, the current sendOrder was specified like this to make it work with MoQ requirements where the application would create new streams with constantly increasing sendOrder. The problem here is that you might also need a control stream. You don't want the media streams to starve the control stream, so the control stream can't have sendOrder = 0 - you could set it to the maximum allowed value, but in this case it would also starve the media streams. The solution is to treat streams with no sendOrder as having the same priority as the streams with the highest sendOrder.

We might want to explicitly say that:
> If two streams have the same order, the ordering is implementation-defined.

but I think you can still infer that from the current text.

**Comment by vasilvv** [comment]
I don't believe control streams starving out media streams is a concern (we happily prioritize control over data in a lot of places in our QUIC implementation, and since control is small, this works out in practice).  The text currently in the draft introduces unnecessary complexity because it requires three layers of priority (round robin -- strict -- round robin), with the top layer allowing exactly two buckets -- this seems really suboptimal.

**Comment by jan-ivar** [comment]
>  I propose to simplify this as:
> - Send order is always defined, and is `0` if not specified

Is there new information to reverse our earlier decision on this? See https://github.com/w3c/webtransport/pull/441#issuecomment-1340224240 and https://github.com/w3c/webtransport/issues/431#issuecomment-1323753217.

> As I understand it, the current sendOrder was specified like this to make it work with MoQ requirements where the application would create new streams with constantly increasing sendOrder. The problem here is that you might also need a control stream.

This matches my understanding. A control channel is just one example of a separate flow an application might wish to send concurrently with a stream-per-frame flow. Another is a [file upload](https://github.com/w3c/webtransport/issues/419#issuecomment-1261535895).

The problem with saying everything must be ordered is that having other concurrent flows becomes near impossible.

> The solution is to treat streams with no sendOrder as having the same priority as the streams with the highest sendOrder.

👍

**Comment by jan-ivar** [comment]
Meeting:
- no agreement. Implementers encouraged to share notes on implementation difficulties.
- Keep an eye on problem

**Comment by vasilvv** [comment]
Currently, I can see three potential implementation strategies:
1. Treat "all unordered streams" and "all ordered streams" as two different buckets of equal weight.
2. Treat "all ordered streams" as a bucket, and every unorderd stream as its own bucket of equal weight.
3. Set the default order for unordered stream to one of "0", "+∞", or "-∞"
(I believe all of those are consistent with the current text in the spec)

I find (2) unsatisfying, since it effectively punishes streams for being ordered.
Both (1) and (3) are viable, however, I would prefer (3) over (1), since (1) is more prone to errors (a developer forgetting to set a priority on any stream would lead to "bandwidth leaks" where high-priority streams would lose bandwidth to streams where developers forgot to set priority).

**Comment by jan-ivar** [comment]
> 1. ... 2. ... bucket of equal weight.

The spec says nothing about weight. All it [says](https://w3c.github.io/webtransport/#webtransportsendstream-write) is:

- _"If stream.[[[SendOrder]]](https://w3c.github.io/webtransport/#dom-webtransportsendstream-sendorder-slot) is null then this sending MUST NOT starve"_
- _"If stream.[[[SendOrder]]](https://w3c.github.io/webtransport/#dom-webtransportsendstream-sendorder-slot) is not null then this sending MUST starve until all bytes queued for sending on [WebTransportSendStream](https://w3c.github.io/webtransport/#webtransportsendstream)s with a non-null and higher [[[SendOrder]]](https://w3c.github.io/webtransport/#dom-webtransportsendstream-sendorder-slot) ... have been sent."_

But as someone who wished the spec said more, I'm happy to discuss.

To me, it seems odd to compare "buckets" of ordered vs unordered streams, given that only one stream in the ordered bucket would typically be sent at a time (though this depends on the number of simultaneous videos being sent perhaps!), whereas in the unordered bucket, all are sent at once. So maybe 2 seems fairer than 1?

That said, without something like flows (rejected in https://github.com/w3c/webtransport/issues/419), a user agent can only guess how many separate media streams may be contributing to the ordered bucket (it could look at how many streams there are with the exact same priority).

I imagine an algorithm like this:
 1. Let _highest_ be the highest priority of all open streams at this moment
 2. Let _sendHighestOrdered_ be the subset of streams that have priority _highest_
 2. Let _sendUnordered_ be the subset of streams that have no priority
 3. Update _sendingNow_ to be the union of _sendHighestOrdered_ and _sendUnordered_
 4. Roundrobin on _sendingNow_
 5. Once moment has passed, goto 1

> Set the default order for unordered stream to one of "0", "+∞", or "-∞"
(I believe all of those are consistent with the current text in the spec)

I think "0" or "-∞" would violate the _"MUST NOT starve"_, and the fact that "+∞" doesn't seems like a loophole.

**Comment by vasilvv** [comment]
> The spec says nothing about weight. All it [says](https://w3c.github.io/webtransport/#webtransportsendstream-write) is:

Ah, I did not know that text exists.  We should probably rewrite it, "MUST NOT starve" is really vague (and probably unimplementable, if you interpret that literally).

**Comment by LPardue** [comment]
Victor's comment about the vagarity of meaning of "starvation"  echoes some feedback we had during the standardization of RFC 9218. There might be text about starvation concepts in https://www.rfc-editor.org/rfc/rfc9218.html#section-10 that you can borrow, despite using a different scheme in this API

**Comment by jan-ivar** [comment]
> We should probably rewrite it, "MUST NOT starve" is really vague (and probably unimplementable, if you interpret that literally).

I should let @vasilvv finish his response, just realized I should have included the whole sentence to avoid confusion:
-_"If stream.[[[SendOrder]]](https://w3c.github.io/webtransport/#dom-webtransportsendstream-sendorder-slot) is null then this sending MUST NOT starve except for [flow control](https://w3c.github.io/webtransport/#stream-signal-flow-control) reasons or[ error](https://streams.spec.whatwg.org/#writablestream-error)."_

**Comment by vasilvv** [comment]
> But as someone who wished the spec said more, I'm happy to discuss.
> 
> To me, it seems odd to compare "buckets" of ordered vs unordered streams, given that only one stream in the ordered bucket would typically be sent at a time (though this depends on the number of simultaneous videos being sent perhaps!), whereas in the unordered bucket, all are sent at once. So maybe 2 seems fairer than 1?

Well, that's only the case if you use them the way Warp uses them.  If you, for instance, have `sendOrder = 2` for high-priority control streams, `sendOrder = 1` for low-priority control streams and `sendOrder = 0` for data, you would have a lot of streams, but only three sendOrder values.

> That said, without something like flows (rejected in #419), a user agent can only guess how many separate media streams may be contributing to the ordered bucket (it could look at how many streams there are with the exact same priority).

We should probably bring the "flows" back (probably not weighted).  The current text effectively already does flows, except it only allows two of them, one for ordered streams, and one (or N, depending on interpretation) for unordered ones.  And there's been some discussion of cases in MoQ of where we could potentially want two different ordered entities sharing the same session.

> 
> I imagine an algorithm like this:
> 
> 1. Let _highest_ be the highest priority of all open streams at this moment
> 2. Let _sendHighestOrdered_ be the subset of streams that have priority _highest_
> 3. Let _sendUnordered_ be the subset of streams that have no priority
> 4. Update _sendingNow_ to be the union of _sendHighestOrdered_ and _sendUnordered_
> 5. Roundrobin on _sendingNow_
> 6. Once moment has passed, goto 1

I would be careful writing out any algorithm with an exact complete ordering, since as a QUIC/H3/WT implementer, you have to consider (a) QUIC control frames, (b) HTTP-level control data (QPACK, etc), (c) HTTP traffic that's not WT, (d) WT connect stream, (e) distinguishing streams with new data vs streams with retransmissions.  Having to spell out most of those can be a mouthful, so I'd just add a set of rules of how things should align relative to each other.

**Comment by vasilvv** [comment]
> This API was not designed for that, and I think it would fail miserably at it, since priority is strict, not weighted. We made a screwdriver not a hammer.

I don't see any reason to believe that.  RFC 9218 priorities are strict, for instance, and in case when incremental is set to false, the RFC even encourages the implementations to starve streams that have the same priority.  I still haven't seen a compelling case for applications where weighted priority is desired (I know cases where unweighted equal priority groups would be useful).

> For traditional prioritization of long-lived streams (https://github.com/w3c/webtransport/issues/419) we failed to reach any agreement, so I think apps are better off leaving "sendOrder" (not "sendPriority" mind you) set to the default and be prudent about how much they send on their control channel.

We cannot leave implementing prioritization to the application, since the application has no control over retransmissions; nor is the "control how much you write" approach practical, since limiting write sizes would be really bad for CPU performance.

An ideal priority API would be: on every write, ask the application which of the streams it wants to go now.  We are sadly not in a position to actually offer that due to process separation and resulting latency.
