### ISSUE TITLE
Should there be any way to send capsules on the WebTransport session CONNECT stream?

### ISSUE THREAD

**Issue by LPardue** [w3c/webtransport#496]
The WebTransport protocol uses extended CONNECT in order to initiate a WebTransport session; see https://www.ietf.org/archive/id/draft-ietf-webtrans-http3-05.html#section-3.3. On success, this enables the HTTP Capsule protocol on that stream, which allows the exchange of WebTransport control messages. 

In theory, the endpoints can also send other capsule types on the CONNECT stream. The W3C WebTransport API doesn't expose the ability to send or receive these. It isn't clear if this required or even useful to clients. If we are not going to provide support, we should probably make that clear in the spec because it is a limitation that doesn't exist for other WebTransport implementations.

**Comment by jan-ivar** [comment]
> it is a limitation that doesn't exist for other WebTransport implementations.

Normally we work off of use cases. Are these non-web implementations, and what do they use capsules for?

**Comment by LPardue** [comment]
Capsules as defined at the protocol level are an extension point, so they could be used by applications to do anything. 

I would expect all WebTransport implementations to drain all capsules from the CONNECT stream so that it doesn't block. I would expect WebTransport capsules to be handled by WebTransport but other capsules could be delivered up to the application. For example, on the server side, I could choose to send some custom capsule to clients and might want them to be readable.

In the absence of being able to send/receive custom capsule types, an application can create their own WebTransport streams to achieve something similar. That's probably good enough to satisfy a use case that would have used capsules.

If we don't want to expose an API, we probably need to add a pointer to https://www.rfc-editor.org/rfc/rfc9297.html#section-3.2-7 to remind people that:

> Endpoints that receive a Capsule with an unknown Capsule Type MUST silently drop that Capsule and skip over it to parse the next Capsule.

**Comment by jan-ivar** [comment]
Meeting:
- capsules tend to be privileged, not necessarily for JS
- there are proposals for capsules to do nested flow control
- exposing this to JS would be moderately concerning.
- potential security issue

**Comment by LPardue** [comment]
These sound like valid concerns and reasons to not provide an API for sending/receiving.

**Comment by wilaw** [comment]
Closing based on consensus in last meeting and Lucas final comment.
