### ISSUE TITLE
Support sendRateEstimate for pooled connections

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webtransport#497]
As mentioned in https://github.com/w3c/webtransport/pull/494#issuecomment-1503435831, opening this issue to discuss sendRateEstimate for pooling.

**Comment by wilaw** [comment]
A pooled connection must be against the same host. Does this limit the privacy concern to some degree as it would prevent an application from inferring peer throughput to arbitrary hosts?

**Comment by martinthomson** [comment]
Yes, and requests to the same host from different (top-level) browsing contexts use different connections, which reduces the ability of the server to correlate connections from the same client (except using the stuff mentioned in the cited PR).

**Comment by wilaw** [comment]
Discussed during weekly call https://www.w3.org/wiki/WebTransport/Meetings2023#WebTransport_Bi-weekly_Virtual_Meeting_.2358_late_-_April_25.2C_2023.

> Support sendRateEstimate for pooled connections #497 - Martin, reluctant to make info available to website as other things using that connection. Server can observe all of the same things. Bernard - issue is about other tabs on the client. You should not be able to pool WT connections with other tabs. Browser should not pool webtransport connections across tabs. No worse than exposing CWIND. No huge risk of leakage. Martin - we should remove checks and simplify spec.

PR should remove language that estimate must be absent when pooled.
