### ISSUE TITLE
WebTransport new features

### ISSUE THREAD

**Issue by MuratovBektur** [w3c/webtransport#506]
Sorry for my english. I'm just a fan of web technology. I'd like to see web transport continue to evolve, and I've compiled a list of things I'd like to see (or at least some of them) in the new version of web transport.:

### 1) Static property WebTransport.VERSION. To check if new options are supported in the current version.
 ```typescript
if (!WebTransport.VERSION) {
    // code for old browser
}
else if (WebTransport.VERSION >= 2)  {
    // code for a browser that supports 
    // the second or higher version of the WebTransport
}
```
### 2) New options as the second argument to the WebTransport constructor
```typescript
const transport = new WebTransport(URL, {
  reconnectInterval: 1000, // reconnect (in ms)  to server if close type isn't was a clear and if this parameters  isn't  setted, so never reconnect
  maxReconnectNum: 5, // maximum number of reconnections, default(infinity)
  pingInterval: true // auto send ping (in ms), default(0)
})
```
#### The first option is to add some new method
```typescript
const transport = new WebTransport(URL);
await transport.ready;

const stream = await transport.createBidirectionalStream();
await writer.writeWithCustomEvent('custom-event', data); // Please change writeWithCustomEvent to something more appropriate.
```

#### The second option is write method reload
```typescript
const transport = new WebTransport(URL);
await transport.ready;

const stream = await transport.createBidirectionalStream();
await writer.write('custom-event', data);
```

**Comment by jan-ivar** [comment]
Hi Bektur, thanks for your interest in WebTransport! I'll try to address each item individually:

> ### 1) Static property WebTransport.VERSION. To check if new options are supported in the current version.

WebTransport is a part of the web platform, which is evergreen. [Established practice](https://w3ctag.github.io/design-principles/#feature-detect) is for web developers to use [feature detection](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing/Feature_detection) practices to detect support for individual capabilities and features. If you know of features in WebTransport that aren't easily detectable, please let us know!

> ### 2) New options as the second argument to the WebTransport constructor
> 
> ```typescript
> const transport = new WebTransport(URL, {
>   reconnectInterval: 1000, // reconnect (in ms)  to server if close type isn't was a clear and if this parameters  isn't  setted, so never reconnect
>   maxReconnectNum: 5, // maximum number of reconnections, default(infinity)
>   pingInterval: true // auto send ping (in ms), default(0)
> })
> ```

These seem like reasonable features an application might want. However, they also seem like they could easily be shimmed with a bit of JavaScript using today's API.

WebTransport provides [low-level](https://w3ctag.github.io/design-principles/#high-level-low-level) primitives, and we encourage libraries to build higher-level abstractions on top of it. E.g. it should in theory be possible to shim the client-side of [WebSocket](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket) on it, if someone wanted to.

Should common patterns emerge, the Working Group should be able to consider them at that time.

> ### 3) WebTransport custom event, to make it easier for the client and server to process incoming data.
> ...
> ```typescript
> const stream = await transport.createBidirectionalStream();
> await writer.writeWithCustomEvent('custom-event', data); // ...
> ```

Are you looking for a [request-response](https://en.wikipedia.org/wiki/Request%E2%80%93response) pattern like [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API)? With `'custom-event'`, are you looking to do multiple requests on the same stream? This would cause head-of-line blocking between requests, and also require some transaction id in the payload.

Instead, each bidirectional stream itself is an id in WebTransport protocol, so creating one per transaction gives you request-response by default. [E.g.](https://jsfiddle.net/jib1/e3hq08sm/):
```js
send.onkeypress = async ({keyCode}) => {
  if (keyCode != 13) return;
  const {writable, readable} = new TextEncoderStream("utf-8");
  const writer = writable.getWriter();
  writer.write(send.value);
  writer.close();

  await readable
    .pipeThrough(await transport.createBidirectionalStream())
    .pipeThrough(new TextDecoderStream("utf-8"))
    .pipeTo(new WritableConsole());
}
```
Hope that helps.
