### ISSUE TITLE
Sorry for the interruption 

### ISSUE THREAD

**Issue by lemanschik** [w3c/webtransport#517]
Hi i am frank some maybe know me i am wondering what this has as goal compared to SCTP and WebRTC

At present i am able to do such connections today and we even got TCPOpen and UDPOpen see our demo:

https://github.com/GoogleChromeLabs/telnet-client

maybe i can speed this efforts up as i am implementer.

https://wicg.github.io/direct-sockets/

**Comment by jan-ivar** [comment]
Hi Frank, the goals of WebTransport are outlined in the [explainer.md](https://github.com/w3c/webtransport/blob/main/explainer.md).

WebTransport solves server ←→ client head-of-line blocking, while remaining encrypted and congestion controlled by the browser. It  leverages TLS, QUIC, the same-origin web security model, and privacy protections built into HTTP/3 like CSP. It also requires no special user consent or permission.

Unlike WebRTC data channels, it requires no p2p setup, no ICE gathering or TURN servers. WebRTC ICE gathering unfortunately still has a [dependency on camera or microphone permission](https://www.rfc-editor.org/rfc/rfc8828.html#section-5.2) that can be cumbersome with some routers for non-video-conferencing applications.

> https://wicg.github.io/direct-sockets/

Direct Sockets appear to lack broad support among browser vendors. E.g. the [Mozilla position](https://mozilla.github.io/standards-positions/#low-level-sockets) is negative.

I hope that answers your questions.

**Comment by lemanschik** [comment]
@jan-ivar your aware of direct sockets and UDPOpen?
we can send encrypted traffic over it via DTLS?

see the direct sockets early demo https://github.com/GoogleChromeLabs/telnet-client

**Comment by lemanschik** [comment]
ok your correct at last out of w3c view the thing is clear good effort from your !!
