### ISSUE TITLE
WebTransport http2 idea's suggestions

### ISSUE THREAD

**Issue by martenrichter** [w3c/webtransport#518]
I have been working on a node webtransport plugin (build around quiche (the google one)) and a polyfill for webtransport on unsupported browsers or networks.

The polyfill currently uses for every session and every stream has its own web socket connection. The streams and sessions are tied together by initial signed tokens, that authorize and tied together the websession connections. Data within the streams are sent as binary WebSocket messages and control messages (equivalents to quic messages) as text messages.
It does not suffer head-of-line blocking, but probably the higher number of TCP connections is not beneficial for large setups (but I have no experience with this, pure speculation).

Anyway, I did this, before finding the http2 proposal (I do not know if it was at this point already in the spec).
As my main motivation for the polyfill is to

1. Support browsers, that do not implement webtransport (yet?).
2. Work in environments, where UDP is potentially blocked. (This is true for most of the network, I will deploy my application, which is my motivation for the webtransport work)

So I took a look on the current http/2 spec for webtransport including the capsule protocol. I think it will not be hard to add it to my node plugin using node's native http/2 implementation. So I will probably do it in the next time. 
But my motivation is not so high, since there is currently no browser implementation, so the use case is pretty limited.
And the design of the capsule protocol prevents use case 1.

So I was wondering if it would make sense to add a capsule over websocket protocol (only for the server side) to the specifications.
The benefits are as follows:

1. The protocol's way of working would be very similar to the actual http/2, so one could easily test ideas without waiting for the browser implementation.
2. It will not be hard to implement it in a shim/polyfill (or I think it comes naturally out from my node plugins work)
3. Having it specified ensures, that one shim/polyfill is enough for all future servers deployed that comply to the spec.
4. And it will automatically address points 1. and 2. above.

My proposal would be as follows, the normal capsule protocol:
```
Capsule {
     Capsule Type (i),
     Capsule Length (i),
     Capsule Value (..),
   }
```
The idea would be to transport is as binary frame/payload of length `Length + 4 `, and the payload will start with capsule type and continue with capsule value. Maybe an initial text frame indicates, that it is a capsule over websocket connection.
The rest of the http/2 capsule protocol will remain unchanged. So besides a little bit extra overload, the mechanics of most of the protocol will remain unchanged.

One thing, good for a shim/polyfill would be a mechanism to identify, if the webtransport implementation actually supports the http/2 protocol, so that it can otherwise wrap around and provide a fallback mechanism. Or is this possible and I missed it?

**Comment by ekinnear** [comment]
The capsule semantics that might needed here are probably something to discuss on the IETF draft ([File an issue here](https://github.com/ietf-wg-webtrans/draft-ietf-webtrans-http2/issues/new/choose)).

> One thing, good for a shim/polyfill would be a mechanism to identify, if the webtransport implementation actually supports the http/2 protocol, so that it can otherwise wrap around and provide a fallback mechanism. Or is this possible and I missed it?

For this part, I think we'd specifically tried to steer away from being able to tell the exact underlying transport in favor of expressing the capabilities of that transport so that we aren't making assumptions that "HTTP/3 means X" and then getting stuck when HTTP/4 is in use and we now have hardcoded a bunch of these assumptions. If that means that there are more capabilities that we should expose, that's definitely a good thing to follow up on, however.

**Comment by martenrichter** [comment]
> The capsule semantics that might needed here are probably something to discuss on the [IETF draft](https://datatracker.ietf.org/doc/draft-ietf-webtrans-http2/) ([File an issue here](https://github.com/ietf-wg-webtrans/draft-ietf-webtrans-http2/issues/new/choose)).

Thanks I did this, I was not aware to post for this part.

> 
> > One thing, good for a shim/polyfill would be a mechanism to identify, if the webtransport implementation actually supports the http/2 protocol, so that it can otherwise wrap around and provide a fallback mechanism. Or is this possible and I missed it?
> 
> For this part, I think we'd specifically tried to steer away from being able to tell the exact underlying transport in favor of expressing the capabilities of that transport so that we aren't making assumptions that "HTTP/3 means X" and then getting stuck when HTTP/4 is in use and we now have hardcoded a bunch of these assumptions. If that means that there are more capabilities that we should expose, that's definitely a good thing to follow up on, however.

I understand the idea behind it. But now, I have more or less exactly the same problem only in another direction, I have to make based on the capabilities of the transport assumptions if a particular protocol is implemented to polyfill it.

**Comment by martenrichter** [comment]
In principle yes, I am using something similar together with my old ponyfill (https://www.npmjs.com/package/@fails-components/webtransport-ponyfill-websocket) in my lecture webapplication (https://github.com/fails-components/lectureapp/blob/c2cf54a4246ed8b18b23006baf74d898401b1a99/src/avtransport.js#L64). Currently in testing in my lecture.
But of course, we need also to check if Webtransport is available, as one major browser for specific devices does not support it.

But it is not really ideal, especially during development. If you tear down the server and restart it again, it is very likely, that you end up with the ponyfill, even if the server is up again, as the browser is stuck in the first attempt connecting with the normal webtransport.
Also the long timeout of chromium for the http3 webtransport is not really improving the experience in this case. (I use chromium, as my app is too slow in firefox because of rendering).

But it is the best I can do, as some of our networks have UDP completely blocked.

**Comment by jan-ivar** [comment]
Meeting:
- No current interest in new API surface.

**Comment by martenrichter** [comment]
Ok, I have also had no idea how to make it better.
Anyway, I am no 80% through with coding the polyfill (not pushed yet), only some boilerplate code is mssing and testing is missing.
The following issues arose:

- Is there a way to determine, if a reliable transport is available? It will be quite useful, for the following scenario.
Imagine the reliable transport as a means to support routes with blocked UDP. If I do not know, if reliability is supported. The UA will probe QUIC, then reliable and after this the application or polyfill will again test for a reliable fallback, so that the time out is delayed three times. If the app or polyfill knows, that it is already supported, it can skip its own reliable fallback. (And yes I know a fingerprinting is an issues, but otherwise, one has to use the browser version...)
- Error codes: Are there any suggestions how to map WebSocket error codes to WebTransport?
- The secondary protocol option of WebSocket seems to be a good idea to indicate, that it is used for WebTransport over WebSocket. So I set it to "webtransport". Any objections? Or information, how widespread this option is implemented? (The information on MDM was not that detailed.

**Comment by jan-ivar** [comment]
> ... my app is too slow in firefox because of rendering

May I ask what the rendering problem with Firefox is? Is there bug filed? If not, would you mind filing one?

> Is there a way to determine, if a reliable transport is available? ... as a means to support routes with blocked UDP

On success? Yes. On failure, no.
```js
const wt = new WebTransport(url);
await wt.ready;
if (wt.reliability == "reliable-only") // reliable transport
```

> If I do not know, if reliability is supported. The UA will probe QUIC, then reliable

Not exactly. The UA should be probing both at the [same time](https://w3c.github.io/webtransport/#initialize-webtransport-over-http): _"Let connection be the result of [obtaining a connection](https://fetch.spec.whatwg.org/#concept-connection-obtain) with networkPartitionKey, url, false, newConnection, and http3Only."_ — which in turn says:
<img width="1223" alt="image" src="https://github.com/w3c/webtransport/assets/3136226/8dc3112c-fad7-4261-b504-30183b434e45">

What's chosen is implementation-defined, though _"etc."_ allows e.g. favoring HTTP/3 connections.

> and after this the application or polyfill will again test for a reliable fallback, so that the time out is delayed three times. If the app or polyfill knows, that it is already supported, it can skip its own reliable fallback.

So the total delay should only be two times.

That being said, [§ 2.5. New features should be detectable](https://w3ctag.github.io/design-principles/#feature-detect) might apply here.

**Comment by jan-ivar** [comment]
Maybe we could set `wt.reliability` to `"reliable-only"` on failure if the UA supports HTTP/2 fallback?

**Comment by martenrichter** [comment]
> > ... my app is too slow in firefox because of rendering
> 
> May I ask what the rendering problem with Firefox is? Is there bug filed? If not, would you mind filing one?
It is basically a stylus based app, which receives a lot of pointerevents and generates drawings.
And the last time I checked (a year ago), it is usable but feels more laggy than on chromium.
No I did not file a bug, since it is mainly a performance issue, which, if a had more resource, probably could fix on the app level and the other thing is, for reporting bug, I need code, which the developer can use to reproduce the issue, and this is hard to achieve. (So I advise the users to use blink based browsers, even though I use mostly for other stuff firefox for work).

> 
> > Is there a way to determine, if a reliable transport is available? ... as a means to support routes with blocked UDP
> 
> On success? Yes. On failure, no.
> 
> ```js
> const wt = new WebTransport(url);
> await wt.ready;
> if (wt.reliability == "reliable-only") // reliable transport
> ```
Yes, sure this I know, but this does not solve the problem of probing it twice.

> 
> > If I do not know, if reliability is supported. The UA will probe QUIC, then reliable
> 
> Not exactly. The UA should be probing both at the [same time](https://w3c.github.io/webtransport/#initialize-webtransport-over-http): _"Let connection be the result of [obtaining a connection](https://fetch.spec.whatwg.org/#concept-connection-obtain) with networkPartitionKey, url, false, newConnection, and http3Only."_ — which in turn says: <img alt="image" width="1223" src="https://user-images.githubusercontent.com/3136226/281529386-8dc3112c-fad7-4261-b504-30183b434e45.png">
> 
> What's chosen is implementation-defined, though _"etc."_ allows e.g. favoring HTTP/3 connections.
> 
> > and after this the application or polyfill will again test for a reliable fallback, so that the time out is delayed three times. If the app or polyfill knows, that it is already supported, it can skip its own reliable fallback.
> 
> So the total delay should only be two times.
Ok this is even better...., but not as good as it can be.

> 
> That being said, [§ 2.5. New features should be detectable](https://w3ctag.github.io/design-principles/#feature-detect) might apply here.

Yes, probably....

**Comment by martenrichter** [comment]
> Maybe we could set `wt.reliability` to `"reliable-only"` on failure if the UA supports HTTP/2 fallback?

I think this would be a good idea.

**Comment by martenrichter** [comment]
When working on the implementation, I came across another thing, what is about [draining](https://www.w3.org/TR/webtransport/#dom-webtransport-draining);, what should I do if no corresponding frames arrived and the connection was closed, because of another reason. So what to do at close cleanup, when draining ist still pending?

**Comment by martenrichter** [comment]
I have pushed a web transport over web socket implementation by wrapping the capsule protocol onto a WebSocket. So far all my unit tests have passed. Of course, it needs some further testing. I am mapping the error codes to the WebSocket close reason using the form `${code}:${actual_reason}`.

**Comment by jan-ivar** [comment]
> what to do at close cleanup, when draining ist still pending?

My (limited) understanding of draining is that it's a nicety allowing apps to trade early signals to wind down sending from the other end, that in no way should delay or interfere with closing.

**Comment by martenrichter** [comment]
> > what to do at close cleanup, when draining ist still pending?
> 
> My (limited) understanding of draining is that it's a nicety allowing apps to trade early signals to wind down sending from the other end, that in no way should delay or interfere with closing.

Ok, but this is not what I meant.
But my question was poorly written.
What to do with the draining promise, when the session is closed? (So the close promise resolved or rejected).

**Comment by jan-ivar** [comment]
> What to do with the draining promise, when the session is closed?

Nothing. [Never settling](https://w3c.github.io/webtransport/#dom-webtransport-draining-slot) is fine.
