### ISSUE TITLE
WebTransport API and ManagedMediaSource API 

### ISSUE THREAD

**Issue by aboba** [w3c/webtransport#522]
The proposed [ManagedMediaSource API](https://github.com/w3c/media-source/issues/320) includes eventHandlers for `onqualitychanged`, `onstartstreaming` and `onendstreaming`. 

How would a WebTransport-based client (e.g. MoQ) respond to these events?  

WWDC Presentation is [here](https://developer.apple.com/videos/play/wwdc2023/10122).

**Comment by jan-ivar** [comment]
What is your question? This seems like MSE and WebTransport is a byte transport without concept of media.

**Comment by wilaw** [comment]
@aboba  - how would the server know what the client's burst window is i.e the time between the onstartstreaming and onendstreaming events?? Do you anticipate the client listening to these events and then communicating them to the server via some type of control channel?

**Comment by aboba** [comment]
@wilaw I don't forsee any coordination between server and client. [ManagedMediaSource API](https://www.w3.org/TR/media-source-2/#managedmediasource-interface) is designed to manage power consumption of streaming implementations on mobile devices.  It works by providing events to applications that enable them to bundle their reads during periods when the cellular modem is awake.  As a result, mobile WebTransport applications decoding and rendering CMAF (e.g. MoQ) will most need to implement ManagedMediaSource API.

**Comment by aboba** [comment]
@jyavenard @marcoscaceres  Any thoughts on this?

**Comment by jyavenard** [comment]
There's no requirement to strictly follow the `onstartstreaming` `onendstreaming` event. They are hints.

on iOS devices what it means is that the 5G modem won't be used and instead it uses 4G as it has a lower power usage.

So if you ignore it, it will work just the same from a user perspective.

Just like streaming a live stream with MMS, there's no expectations that you would only fetched content between the two events.

As you mentioned, the primary aim was to allow sites to switch from a HLS stream to a MMS one with no power regression

**Comment by jan-ivar** [comment]
Meeting:
- You have less control of when you wake up in WebTransport. Except maybe reject new incoming streams.
- Apps in general can switch from pull to push to gain control of timing
- @wilaw to follow up

**Comment by wilaw** [comment]
@jyavenard  - can you clarify on an iOS device whether the 5G modem access granted to HTTP FETCH requests between the hinted events, also applies to data transmitted over WebTransport, both sending from client to server and receiving from server to client?

**Comment by jyavenard** [comment]
> @jyavenard - can you clarify on an iOS device whether the 5G modem access granted to HTTP FETCH requests between the hinted events, will also apply to data transmitted over WebTransport, both sending from client to server and receiving from server to client?

There's no fine grain control such as one packet goes over 5g while another would simultaneously go on 4g. It's on or the other.

While a ManagedMediaSource is active, if you fetch content between the two events: they are flagged as media, and the system *may* turn on 5G.
So if the fetch has access to 5G, any other traffic transiting at the same time will also go over 5G

**Comment by wilaw** [comment]
@aboba  - Jean-Yves's reply indicates that traffic over WebTransport would follow traffic via Fetch during the window between `onstartstreaming `and `onendstreaming.`. An application could monitor these MMS events and adjust its WebTransport send behavior appropriately. Are you OK with closing this issue?

**Comment by aboba** [comment]
@wilaw It's ok to close the "question". 

Based on the MoQ WG discussion at IETF 119 and Jean-Yves' reply, it seems possible to write a sample combining WebTransport w/Fetch-like client requests and Managed MSE, utilizing the `onstartstreaming` and `onendstreaming` events. All the pieces are not yet in place in Safari TP, but they are in progress. 

Unless Managed MSE has some implicit dependency to HLS, it shouldn't make a make a difference whether the WebTransport is left open.
