### ISSUE TITLE
Make create(Uni|Bi)directionalStream() synchronous?

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webtransport#529]
https://github.com/w3c/webtransport/pull/440 and https://github.com/w3c/webtransport/pull/528 remove the reasons for [createUnidirectionalStream](https://w3c.github.io/webtransport/#dom-webtransport-createunidirectionalstream) and [createBidirectionalStream](https://w3c.github.io/webtransport/#dom-webtransport-createunidirectionalstream) to be asynchronous. Making them synchronous would simplify the API by removing an unnecessary async step:
```js
const writable = wt.createUnidirectionalStream(); 
const bistream = wt.createBidirectionalStream(); 
```
Interestingly, old code like the following would continue to work (saved by how `await` works):
```js
const writable = await wt.createUnidirectionalStream(); 
const bistream = await wt.createBidirectionalStream(); 
```
As would old code inside a promise chain (saved by how `then` works):
```js
Promise.resolve().then(() => wt.createUnidirectionalStream()).then(writable => { ... });
``` 
It would only break code at the head of a promise chain:
```js
wt.createUnidirectionalStream().then(writable => { ... });
```
I suspect usage is still low enough, and async/await popular enough that we could get away with this change. If this is a concern, browsers could add a temporary workaround (`stream.then = f => Promise.resolve(f(stream))`) with a warning.

**Comment by vasilvv** [comment]
I don't think this is necessarily true?  Similar to getStats, we're not actually guaranteed to have the available number of open streams and up-to-date MAX_STREAM_ID values available on the same thread as JavaScript.

**Comment by jan-ivar** [comment]
I see, there might be some challenges here then. MAX_STREAM_ID affected by incoming streams?

**Comment by vasilvv** [comment]
Not the streams themselves, but MAX_STREAM_ID is affected by the incoming MAX_STREAM_ID frames from the peer.

**Comment by jan-ivar** [comment]
What happens to already open streams if the MAX drops below the number of streams already created?

**Comment by vasilvv** [comment]
MAX cannot drop, it's cumulative boundary (you're allowed to create a stream with ID `x` iff `x <= MAX_STREAM_ID`).  That said, it's possible that you could reject a stream that would be accepted if you had an up-to-date value.

Also, given the proposed changes, I am not sure how the user is supposed to know when it's now possible to create new streams.

**Comment by jan-ivar** [comment]
Closing this. Would have been nice but not having an updated MAX_STREAM_ID to work with sounds like a problem.
