### ISSUE TITLE
Protocol concepts don't include sending on streams

### ISSUE THREAD

**Issue by martinthomson** [w3c/webtransport#533]
In [Section 3](https://w3c.github.io/webtransport/#protocol-concepts), streams only have creation and sending capabilities, but apparently sending is not permitted.

**Comment by nidhijaju** [comment]
The second table in Section 3 talks about the "[send bytes](https://w3c.github.io/webtransport/#stream-send)" capability of streams. Are you potentially referring to that as streams having sending capabilities, or did you mean something else?

**Comment by jan-ivar** [comment]
It's all there I think, but maybe we have a discovery problem. Would it help to break out the concepts in the TOC?

- § 3. Protocol concepts
  - § 3.1 WebTransport session
  - § 3.1 WebTransport stream
