### ISSUE TITLE
Reconsider whether we need sub-protocol negotiation

### ISSUE THREAD

**Issue by vasilvv** [w3c/webtransport#536]
Both WebSocket and QUIC have a subprotocol negotiation mechanism (QUIC mandates ALPN, WebSocket has Sec-WebSocket-Protocol).  When we designed WebTransport originally, we decided that between the application streams and the URL path/query, those are redundant.

Reasons why we may want to reconsider this:
- People design applications for QUIC, and they may rely on ALPN for things like version negotiation.  Supporting a similar mechanism in WebTransport would make porting those protocols easier.
- QUIC requires ALPN for protection against cross-protocol attacks, which may be a useful property here too.

Reasons why we may want to keep it as-is:
- Mitigating cross-protocol attacks might not be particularly useful.  While HTTP itself does support a similar mechanism (Content-Type/Accept), Web developers often assume that the URL implies the format it contains (i.e. if you have an endpoint called `/api/update-entry`, you know what can be POSTed onto it, and what format the response will be).

**Comment by martinthomson** [comment]
ICYMI: https://datatracker.ietf.org/doc/html/rfc7639

**Comment by LPardue** [comment]
I noted the ALPN header RFC during the call, I think the discussion us summarized under the final point Jan-Iver captured

**Comment by ekinnear** [comment]
New header is available from the IETF side in [this PR](https://github.com/ietf-wg-webtrans/draft-ietf-webtrans-http3/pull/144), so we should be fine to start offering a constructor that takes this list of protocol strings.

**Comment by jan-ivar** [comment]
So something like:
```js
const wt = new WebTransport(url, {protocols: ["moqt", "loc"]);
await wt.ready;
console.log(wt.protocol); // null or "moqt" or "loc");
```

**Comment by jan-ivar** [comment]
Meeting:
- A PR would need to validate length limits for string inputs based on https://github.com/ietf-wg-webtrans/draft-ietf-webtrans-http3/pull/144 ...
- ...which BTW also says _"Servers MAY reject the request if the client did not include a suitable subprotocol."_
- If the server doesn't reject over unsupported protocol, should the API still reject?
- E.g. either
  - It could succeed and `wt.protocol` is `null`, OR
  - `wt.ready` rejects anyway
- Found ref _"Parsers must support tokens of at least 512 characters."_
- Maybe look at WebSocket for mitigations?

**Comment by vasilvv** [comment]
> If the server doesn't reject over unsupported protocol, should the API still reject?

So, the reason we changed protocol from non-nullable to nullable is that this provides a way for applications that have not used subprotocols previously to start using them; it would make sense for the API to follow that logic.

> Found ref "Parsers must support tokens of at least 512 characters."

I think we should pick some number and make sure that we support it, and reject everything above (the server has to pick one of the client-offered tokens, so if we say "reject above N bytes", that will be the de-facto limit).
