### ISSUE TITLE
Expose [[State]] internal slot

### ISSUE THREAD

**Issue by achingbrain** [w3c/webtransport#539]
The spec sets out a  [[[State]]](https://www.w3.org/TR/webtransport/#dom-webtransport-state-slot) internal slot that contains the current state of the transport.

It would be really useful to expose this as an [attribute](https://www.w3.org/TR/webtransport/#webtransport-attributes) to allow js code to have a little more introspection ability.

It would help with application observability and diagnostics, and also to better understand the lifecycle of a WebTransport object.

**Comment by aboba** [comment]
This seems duplicative. We already have the ready promise and error events. If we added this, we'd need a corresponding event that would duplicate existing functionality.

**Comment by jan-ivar** [comment]
I agree it's duplicative since we went with promises over events and state. Here's a [polyfill](https://jsfiddle.net/jib1/wx5b8nep/) to illustrate this:
```js
const wt = new WebTransport("https://webrtc.internaut.com:6161/echo");

button.onclick = async () => console.log(await getState(wt));

async function getState(wt) {
  const [ready, closed, draining] = await Promise.all([
    await promiseState(wt.ready),
    await promiseState(wt.closed),
    await promiseState(wt.draining || new Promise(() => {}))
  ]);
  switch (ready) {
    case "pending": return "connecting";
    case "rejected": return "failed";
    case "fulfilled": {
      switch (closed) {
        case "pending": return draining == "fulfilled"? "draining" : "connected";
        case "rejected": return "failed";
        case "fulfilled": return "closed";
      }
    }
  }
}

function promiseState(p) {
  const t = {};
  return Promise.race([p, t])
    .then(v => (v == t)? "pending" : "fulfilled", () => "rejected");
}
```

**Comment by jan-ivar** [comment]
Here's a MUCH simpler [polyfill](https://jsfiddle.net/jib1/21s64vbe/):
```js
const wt = new WebTransport("https://webrtc.internaut.com:6161/echo");

button.onclick = async () => console.log(wt.state);

if (!wt.draining) wt.draining = new Promise(() => {});
wt.state = "connecting";
wt.ready.then(() => wt.state = "connected", () => wt.state = "failed");
wt.closed.then(() => wt.state = "closed", () => wt.state = "failed");
wt.draining.then(() => wt.state = "draining", () => {});

```

**Comment by jan-ivar** [comment]
I agree it's duplicative since we went with promises over events and state. Here's a [polyfill](https://jan-ivar.github.io/polyfills/webtransportstate.js) that [works](https://jsfiddle.net/jib1/21s64vbe/):
```js
if (!('state' in WebTransport.prototype)) {
  const nativeWebTransport = window.WebTransport.bind(window);

  window.WebTransport = function(url, options) {
    const wt = new nativeWebTransport(url, options);
    wt.state = "connecting";
    wt.ready.then(() => wt.state = "connected", () => wt.state = "failed");
    wt.closed.then(() => wt.state = "closed", () => wt.state = "failed");
    wt.draining?.then(() => wt.state = "draining", () => {});
    return wt;
  };
}
```

**Comment by jan-ivar** [comment]
I propose we close this at next meeting.

**Comment by achingbrain** [comment]
The problem with the suggested polyfill is that if you call `.then` with two args, if the promise rejects it no longer causes an unhandled promise rejection.

If a user wants this in their application that's down to them but it's not the sort of code you could reasonably include in a library.

Exposing the `[[State]]` slot would allow observability without changing the behaviour of the thing it is observing.

**Comment by jan-ivar** [comment]
@achingbrain thanks for spotting that. Rethrowing the error should hopefully fix that.
```js
if (!('state' in WebTransport.prototype)) {
  const nativeWebTransport = window.WebTransport.bind(window);

  window.WebTransport = function(url, options) {
    const wt = new nativeWebTransport(url, options);
    wt.state = "connecting";
    wt.ready.then(() => wt.state = "connected", e => { wt.state = "failed"; throw e; });
    wt.closed.then(() => wt.state = "closed", e => { wt.state = "failed"; throw e; });
    wt.draining?.then(() => wt.state = "draining");
    return wt;
  };
}
```

**Comment by jan-ivar** [comment]
Hmm, that might always trigger unhandled rejections. I'll have to think about it a little more.

**Comment by aboba** [comment]
@jan-ivar I agree with closing this issue. So far, I haven't found a situation in which a [[State]] internal slot would be useful.

**Comment by achingbrain** [comment]
> So far, I haven't found a situation in which a [[State]] internal slot would be useful

Here's one - I put [this demo page together](https://libp2p-webtransport-sessions.on.fleek.co/) while investigating a [bug](https://issues.chromium.org/issues/40069954) that makes WebTransport unusable for peer to peer applications, it tracks the state of various WebTransport connections opened by the page.

It does so by doing something similar to the suggested polyfills above, but due to the semantics of using promises for `.ready`, `.closed`, etc it can't observe the state of a connection without changing it's behaviour.

`[[State]]` would have been very useful here.

Here's another, though similar - I'd like to also expand the observability of [js-libp2p](https://github.com/libp2p/js-libp2p) through a dashboard similar to [ipfs-webui](https://github.com/ipfs/ipfs-webui) but again this isn't something we can do without either causing [unhandled promise rejections](https://github.com/w3c/webtransport/issues/539#issuecomment-1932992899) or [smothering errors](https://github.com/w3c/webtransport/issues/539#issuecomment-1932970574).

**Comment by jan-ivar** [comment]
Meeting:
- Some interest, but stronger desire to match the streams spec

**Comment by jan-ivar** [comment]
Meeting:
- @nidhijaju Any more thoughts on this?
- @jan-ivar to see if there is a general problem here with use of promises as attributes vs browser's unhandled rejection detection?

**Comment by saschanaz** [comment]
> * Suggestion to reach out to streams spec folks for ways a JS library might observe promises without interfering with the browser's [unhandled promise rejections](https://github.com/w3c/webtransport/issues/539#issuecomment-1932992899) or [smothering errors](https://github.com/w3c/webtransport/issues/539#issuecomment-1932970574).

Streams has several "Set promise.[[PromiseIsHandled]] to true" in several places, is that what you want?

**Comment by saschanaz** [comment]
Briefly checked other existing [`readonly attribute Promise`](https://github.com/search?q=repo%3Aw3c%2Fwebref%20%22attribute%20Promise%22&type=code)s and those never reject, while WebTransport rejects promise attributes. 👀

**Comment by jan-ivar** [comment]
I found streams rejecting `reader.closed` [here](https://streams.spec.whatwg.org/#readable-stream-reader-generic-release).

[[PromiseIsHandled]] might work.

**Comment by achingbrain** [comment]
My opinion is that libraries should not modify built ins or globals as the results can be unpredictable when deployed in an app with other libraries, so I'd rather not go down the polyfill route but it that's the only option then that's what it's going to have to be.

Thanks for looking into this.

**Comment by jan-ivar** [comment]
With the polyfill I only meant to suggest these ergonomics can be provided by a JS library. This can be done as a function.
