### ISSUE TITLE
Provide flow control minimums from the browser side

### ISSUE THREAD

**Issue by vasilvv** [w3c/webtransport#541]
Currently, the maximum number of streams that a server can open for an individual session is not defined in the spec and is entirely up to the browser.  I believe Chrome defaults to max 100 streams by default, so dedicated transports would get ~99 streams.  We should probably provide some guarantees about the minimum available to the server -- e.g. 1 or 2 would make a lot of application simply not work.

**Comment by vasilvv** [comment]
Just realized this is related to #446, but I feel like the discussion there diverged from this specific issue, so keeping this one open to make sure we don't lose track of this.

**Comment by jan-ivar** [comment]
@vasilvv Did you mean https://github.com/w3c/webtransport/issues/544?

**Comment by jan-ivar** [comment]
@jesup to come back with what the default is in Firefox.

**Comment by jan-ivar** [comment]
> ... 1 or 2 would make a lot of application simply not work.

@vasilvv what do you mean with "not work" specifically?

**Comment by vasilvv** [comment]
It is entirely plausible that your application uses a protocol that requires server to open at least three streams; if the theoretical browser allows only two streams, the third stream will be never opened, and the application will deadlock.

**Comment by jan-ivar** [comment]
@vasilvv Wouldn't the third stream will be opened after a roundtrip? Aren't we just discussing defaults/starting values for max?

**Comment by jan-ivar** [comment]
@vasilvv Couldn't the server open the third stream after a roundtrip of the server asking for a limit increase? Aren't we just discussing defaults/starting values for max?

**Comment by vasilvv** [comment]
There isn't really a way to ask the peer for an increase, the limit increases are unilateral.

> Aren't we just discussing defaults/starting values for max?

Yes.  The specific issue I have is that if the defaults are too low, some applications won't work, so we should specify *some* minimum default.
