### ISSUE TITLE
Define datagram

### ISSUE THREAD

**Issue by achristensen07** [w3c/webtransport#542]
This specification does not define what a datagram is, or even directly link to another specification that does.  It says a session can send and receive datagrams, and a stream can send and receive bytes.  From this spec it is not clear what the difference between those two is.

**Comment by martinthomson** [comment]
That is probably because it is assumed knowledge.  Anything in things like the Internet Users' Glossary (RFC 1983) are probably fair game.  See the bottom of page 14: https://www.rfc-editor.org/rfc/rfc1983#page-14

**Comment by ekinnear** [comment]
In the event that sending a "datagram" maps to a QUIC datagram or H2-based HTTP datagram (or other future things, if we're thinking of WebTransport as a generic transport representation), perhaps we should consider some editorial text to make some of that clear?
Not so much the part about what a datagram itself is, but the role it plays here.

**Comment by ricea** [comment]
I think the definition of "datagram" should be left to the lower-levels, however there are two properties of datagrams that are important when using a BYOB datagram reader:
1. Datagrams are always delivered completely or not at all
2. Datagrams are never more than 65536 bytes in length

It might be useful to have an advisory note for authors recommending using Uint8Array to hold datagrams.

**Comment by achristensen07** [comment]
Where does a datagram come from?  Firefox seems to only accept ArrayBuffer or ArrayBufferView objects written to the WebTransportDatagramDuplexStream.writable, otherwise it rejects with a TypeError.  I found that at https://searchfox.org/mozilla-central/source/dom/webtransport/api/WebTransportDatagramDuplexStream.cpp#263 .  I assume Chrome has similar behavior, though I'm having a little more trouble finding it.  Maybe I'm missing something, but the WritableStream spec seems to accept 'any' here.  This is information I'd expect to find in this specification.

Where does a datagram go?  You don't need to explain what a datagram is or where it goes, but I'd expect a link to a document that does.  Having a specification that assumes you already know what the specification specifies isn't as useful as it could be.

**Comment by vasilvv** [comment]
"A datagram is a sequence of bytes that is limited in size (generally to the path MTU) and is not expected to be transmitted reliably. The general goal for WebTransport datagrams is to be similar in behavior to UDP while being subject to common requirements expressed in [Section 2](https://www.ietf.org/archive/id/draft-ietf-webtrans-overview-05.html#common-requirements)." https://www.ietf.org/archive/id/draft-ietf-webtrans-overview-05.html#name-datagrams

We should probably link to that document in the "Protocol concepts" section.
