### ISSUE TITLE
Busy requestAnimationFrame Causes WebTransport Send Queue Starvation

### ISSUE THREAD

**Issue by cybersoulK** [w3c/webtransport#543]
Overview:
While working on a project that uses WebTransport, I've noticed that a busy requestAnimationFrame loop seems to slow down the WebTransport send queue significantly. This causes the client to severely delay sending datagrams.

Video of the issue:
[YouTube Video Demonstration](https://www.youtube.com/watch?v=zXbi_15Lu-Y&ab_channel=CyberGate)
busy loop runs at 20fps, my machine has 120 fps refresh rate.

Steps to Reproduce:
Set up a local server on https://localhost:3100.
Connect a WebTransport client to the server.
Run a busy requestAnimationFrame loop in the client (as shown in the example code below).

minimal client code: 
[example.zip](https://github.com/w3c/webtransport/files/12564363/example.zip)

**Comment by wilaw** [comment]
Discussed in bi-weekly meeting 9/26. Assigned @jesup to see if this is a Firefox issue.

**Comment by jan-ivar** [comment]
@cybersoulK BTW do you see the same symptom in Chrome, or is this specific to Firefox?

**Comment by cybersoulK** [comment]
> @cybersoulK BTW do you see the same symptom in Chrome, or is this specific to Firefox?

sorry i missed this message, 
has been quite some time, and i have been using a web-worker since, but i believe i had the issue in chrome as well. Firefox is the most noticeable.

https://github.com/hyperium/h3/issues/209#issuecomment-1711009051

**Comment by wilaw** [comment]
Sounds like an implementation issue, not a specification issue. Closing. Please reopen if you feel otherwise.
