### ISSUE TITLE
Should all fields in WebTransportConnectionStats be nullable?

### ISSUE THREAD

**Issue by vasilvv** [w3c/webtransport#567]
We can always get minRtt and friends on all platforms for QUIC, since we use UDP.  For HTTP/2 and TCP, we're at the mercy of platform APIs, and not all of those may be consistently available everywhere. We should make those nullable rather than present a bogus value to the user.

**Comment by jan-ivar** [comment]
These are dictionaries, which allows us to omit members already. Might this serve the same purpose?

**Comment by jan-ivar** [comment]
Meeting:
- Absence is fine. Need to clarify in note that availability is subject to platforms.
