### ISSUE TITLE
How should the WebTransport constructor handles timeouts?

### ISSUE THREAD

**Issue by martenrichter** [w3c/webtransport#578]
This is an issue that I experienced while writing automated tests for a Webtransport polyfill.
While testing the functionality of the fallback, the http/3 server was not running, so the fallback kicked in.
As I tried to open the same non-existing server with different paths again and again, I saw that the tests failed.
After a long debugging session, I found out that the UA (chromium in playwright), was increasing the timeout after each failure.
I ended up using a promise to ensure a maximum timeout.
It looks like an intentional behavior, so I did not file a bug with Chromium, but is this desired behavior, especially if several servers may be tested to find the most suitable transport?

So, I thought I would just ask the spec workgroup. It is not important to me as I found out the cause (after two days), but I think it is worth discussing with other users.

**Comment by martenrichter** [comment]
Ok, I am just writing unit tests against Firefox, which has a minimum timeout time of 30 s, so Chromium is modest.

**Comment by jan-ivar** [comment]
This spec at some point calls into the same code path as fetch [here](https://w3c.github.io/webtransport/#initialize-webtransport-over-http): _"Let connection be the result of [obtaining a connection](https://fetch.spec.whatwg.org/#concept-connection-obtain) w"_, and we don't impose any timeouts on top of that currently. 

What behavior would you desire instead?

**Comment by martenrichter** [comment]
My motivation for the question was for the polyfill, as I originally used it only after the native connection failed.
Now, I use it if the native connection fails or a timeout of 2 seconds has passed. (of course, the old connection attempt prevails).

I expect that web transport is often used for applications such as video conferences or online games. There may be a number of VMS or containers that directly serve the demand (so without a proxy), and the application may want to switch fast to another server in case of a problem.
Ok, I can still just use SetTimeout and open another connection... and close the other while connecting (can I?), but maybe a custom timeout or a fast timeout may be worth thinking about. But I do not have a strong opinion.

**Comment by jan-ivar** [comment]
> Ok, I can still just use SetTimeout and open another connection... and close the other while connecting (can I?)

Yes you can. I think this is the approach I'd recommend. This seems sufficient to me.

Unless others disagree I propose we close this.

**Comment by jan-ivar** [comment]
Said differently, there already is a timeout (in fetch) and it's implementation-defined.
