### ISSUE TITLE
Remove dependency on "Data Recvd" state

### ISSUE THREAD

**Issue by martinthomson** [w3c/webtransport#581]
https://github.com/ietf-wg-webtrans/draft-ietf-webtrans-http2/issues/103 has more background.

The [text for session termination](https://w3c.github.io/webtransport/#web-transport-termination) starts with this:

> Let cleanly be a boolean representing whether transport.[[[Session]]](https://w3c.github.io/webtransport/#dom-webtransport-session-slot)'s [CONNECT stream](https://w3c.github.io/webtransport/#connect-stream) is in the "Data Recvd" state. [[QUIC]](https://w3c.github.io/webtransport/#biblio-quic)

Whether data has been acknowledged is not a useful signal.  However, the point of this variable is to split the difference between a graceful and abrupt termination.  That's not a concept that can be known in the way that is described.  Though data might have been received by an immediate peer, it might not have been processed, so the "Data Recvd" signal is not really that useful.

I suggest that we strike this and it's dependent conditions.

**Comment by martenrichter** [comment]
OK, could you also clarify/change §6.4 procedures for `WebTransportSendStream` of the point 
>Wait for stream.[[[InternalStream]]](https://w3c.github.io/webtransport/#dom-webtransportsendstream-internalstream-slot) to enter the "Data Recvd" state. [[QUIC]](https://w3c.github.io/webtransport/#biblio-quic)

Because this is the one point that confused me, could you clarify that this will only take place for http/3?

**Comment by martinthomson** [comment]
@martenrichter, see #580 for that part.  I did separate pull requests because this one took a bit more thinking than the other.

**Comment by martenrichter** [comment]
Ah ok, I overlooked this.
