### ISSUE TITLE
What are "first-strong heuristics"?

### ISSUE THREAD

**Issue by martinthomson** [w3c/webtransport#583]
Quoth the specification:

> Note: No language or direction metadata is available with reasonBytes. First-strong heuristics can be used for direction when displaying the value.

This concept is not one that I'm familiar with. It could benefit from a reference of some sort.

**Comment by wilaw** [comment]
Hi Martin - this language was introduced as a result of issue https://github.com/w3c/webtransport/issues/414 and particularly this comment from Addison Phillips, Chair, W3C Internationalization (I18N) Working Group. 

The term 'first-strong" is referenced in Strings on the Web: Language and Direction Metadata https://www.w3.org/TR/string-meta/ and in particular this section https://www.w3.org/TR/string-meta/#firststrong . It is a heuristic to determine the directionality of a string, in which the rendering system looks for the first character in the string with a strong Unicode directional property, and then sets the base direction to match it.

Proposal is that we update our spec to add a reference pointing to https://www.w3.org/TR/string-meta/#firststrong

**Comment by martinthomson** [comment]
That sounds like a good idea.  Thanks for chasing that down (searching the web was not productive for me).
