### ISSUE TITLE
Relative URL in WebTransport constructor

### ISSUE THREAD

**Issue by devsnek** [w3c/webtransport#596]
WebSocket recently added support for relative URLs: https://github.com/whatwg/websockets/commit/771cd4ffa1385c0b66ac17d0e82015f354359e36

If there isn't any particular reason that WebTransport does not allow relative URLs, it might be a nice quality of life improvement for developers to allow them.

**Comment by jan-ivar** [comment]
Good idea and seems noncontroversial. I'll add a PR for discussion.
