### ISSUE TITLE
What are the initial values of the RTT stats?

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webtransport#608]
If I call
```js
const wt = new WebTransport(url);
const {smoothedRtt, rttVariation, minRtt} = await wt.getStats();
```
What values will I get when the connection transitions to "connected"?

Is the RTT calculated from the connection handshake?

**Comment by vasilvv** [comment]
Yes, generally, a handshake should be sufficient for the initial RTT calculation.

**Comment by jan-ivar** [comment]
OK in that case I'll close this and make them `required` in #609.
