### ISSUE TITLE
Detect support for waitUntilAvailable=true?

### ISSUE THREAD

**Issue by martenrichter** [w3c/webtransport#613]
I currently have the following issues:
I am running automated tests to get new streams.
If waitUntilAvailable=true is supported (there is no support currently, right?), the tests must run differently.
So far, the test for waitUntilAvailable=true has failed as there is no support (at least in Chrome). How should an application detect support for waitUntilAvailabl? It may be crucial, as the behavior for allocating streams may differ.

(Of course, this may be an unimportant detail, but it is a thought that came to me while writing tests. (However, until now, I manually select or deselect the tests depending on the browser engine.)

**Comment by jan-ivar** [comment]
You should be able to feature detect it like this:
```js
let supported = false;
wt.createUnidirectionalStream({get waitUntilAvailable() { supported = true; }});
console.log(supported); // true or false
```
This [existing pattern](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#safely_detecting_option_support) relies on step 5 in [createUnidirectionalStream](https://w3c.github.io/webtransport/#dom-webtransport-createbidirectionalstream). Please LMK if this is insufficient.

**Comment by jan-ivar** [comment]
Please reopen if this is still an issue.

**Comment by martenrichter** [comment]
I'm sorry for the late reply. For the last few weeks, I have been traveling with limited internet access.
I just tried it with node.js, and it does not work. It fails with "ReferenceError: supported is not defined."
Do I have to bind the current context in some way?

**Comment by martenrichter** [comment]
Another question: I have the impression that Firefox currently behaves as if waitUntilAvailable is set to true. Is this observation correct? I am wondering how to deal with it. Either write an exception in the test, or a patch for the browser....

**Comment by jan-ivar** [comment]
Good question. cc @jesup and @vasilvv.

I'd assume both browsers today would behave as is waitUntilAvailable is true given that's what the spec said prior to https://github.com/w3c/webtransport/pull/528.

If so, then defaulting to false may cause a bit of a headache.

**Comment by vasilvv** [comment]
I think the current Chrome behavior is `waitUntilAvailable=false`; there was a bug to fix that, but it was overcome by #528.

**Comment by martenrichter** [comment]
Well, in my unit tests for stream flow control: https://github.com/fails-components/webtransport/blob/master/test/stream-limits.spec.js. Chromium behaves as `waitUntilAvailable=false`. Firefox behaves more like `waitUntilAvailable=true`, but as far as I interpret the behavior it is never available after all, at least this is what I currently think, but I am not sure (and this why I ask). So I believe, that apps, that open and close streams get a problem with interoperability.

**Comment by martenrichter** [comment]
Also, Chrome has close to 150 streams available, and Firefox has close to 100 streams available. (I think I have read that there was some consensus to choose a similar value.)

**Comment by jan-ivar** [comment]
The [server](https://www.rfc-editor.org/rfc/rfc9000#section-19.11) dictates the number of streams you can create, so if Chrome and Firefox differ that's a bug somewhere.

Maybe you're thinking of [anticipatedConcurrentIncomingUnidirectionalStreams](https://w3c.github.io/webtransport/#dom-webtransportoptions-anticipatedconcurrentincomingunidirectionalstreams) which says: _"The user agent MUST initially allow at least 100 [incoming unidirectional](https://w3c.github.io/webtransport/#stream-incoming-unidirectional) streams from the server."_, but that's in the other direction.

**Comment by martenrichter** [comment]
Thanks that is a good point. I will investigate this at the weekend. All I need to do is look at the flow control values on the client and server sides for both browsers. Either I am not sending out flow control values, or a browser does not respect them.

And yes I may have confused it...

**Comment by martenrichter** [comment]
Ok, I have check it, I just forgot, that I used server side different limits for the two waituntilavailable values.
