### ISSUE TITLE
Add SendStream to UnidirectionalStreamsTransport can be racy

### ISSUE THREAD

**Issue by ddragana** [w3c/webtransport#70]
> 2. Let stream be the newly created SendStream object.

> 3. Add stream to transport’s [[OutgoingStreams]] slot.

> 3. Continue the following steps in the background.

> 4. Create stream’s associated underlying transport.

If underlying transport is pooled Http3 connection. This can be racy. The spec checks if the max stream limit  allowed creating new streams, than creats a new SendStream and than it adds it to the trabsport. Since the transport may be used by normal browsing the limit may be already reached again.

**Comment by LPardue** [comment]
This seems a bit like a concrete instance of the HTTP/3 unidirectional arms race issue I opened up on the spec a while back - https://github.com/quicwg/base-drafts/issues/2559

**Comment by jan-ivar** [comment]
This seems covered [here](https://w3c.github.io/webtransport/#dom-unidirectionalstreamstransport-createunidirectionalstream) now, modulo the ambiguous conditional: _"Resolve p with a newly created SendStream object and add the SendStream to transport when all of the following conditions are met:"_ (Do A and B when C)

My reading of this is that the promise remains pending until the condition is met. I'll do a PR to clarify.

**Comment by jan-ivar** [comment]
No, you're right, the adding algorithms still bail early:
```
3. Continue the following steps in the background.
4. Create stream’s associated underlying transport.
```
Since both callers return promises, this seems like an oversight to me, and we should just wait to resolve this promise until the last step has completed. Does that seem reasonable?
