### ISSUE TITLE
Use Application Error Code in a CONNECTION_CLOSE

### ISSUE THREAD

**Issue by flano-yuki** [w3c/webtransport#80]
If my understanding is correct, I think that WebTransport should use CONNECTION_CLOSE (0x1d) and reserve Application Error Code used in it.

The current [specification section 7.4](https://wicg.github.io/web-transport/#web-transport-close-info) says:
> The WebTransportCloseInfo dictionary includes information relating to the error code for closing a WebTransport. For QUIC, this information is used to set the error code and reason for an CONNECTION_CLOSE frame.

It is not clear whether to use CONNECTION_CLOSE (0x1d).

in the [QUIC specification (draft-ietf-quic-transport-24)](https://tools.ietf.org/html/draft-ietf-quic-transport-24#section-19.19) , definition of Error Code in CONNECTION_CLOSE Frames is written as follows:
> Error Code:  A variable length integer error code which indicates the reason for closing this connection.  A CONNECTION_CLOSE frame of type 0x1c uses codes from the space defined in Section 20.  A CONNECTION_CLOSE frame of type 0x1d uses codes from the application protocol error code space; see Section 20.1

[section 20.1](https://tools.ietf.org/html/draft-ietf-quic-transport-24#section-20.1) says
> the management of application error codes is left to application protocols.

Application Error Code are managed. so, Error codes for WebTransport and the applications that use WebTransport should be reserved.

Using and resevation an Apprication Error Code has the following advantages
- It can be distinguished from QUIC transport error sent by QUIC library.
- Separate the error code used by the WebTransport protocol layer from the error code used by the upper WebTanport application (see related issue)

(This issue is related to https://github.com/vasilvv/webtransport/issues/15 )

**Comment by steveanton** [comment]
Yes, I think the spec should be clarified to say that the error code space is the application protocol error code space and not the quic one.

**Comment by yutakahirano** [comment]
Closing this, we're now using WebTransport over HTTP/3 rather than WebTransport over QUIC. This should be covered by #235 and #252.
