### ISSUE TITLE
One-way vs two-way reset on the stream

### ISSUE THREAD

**Issue by vasilvv** [w3c/webtransport#95]
Currently, the API provides with a pair of methods called `abortReading` and `abortWriting` that close the read and the write half of the stream respectively.  While that matches exactly with what QUIC provides, other transports (notably HTTP/2) do not have those two operations as separate; instead, they have a single reset that closes both read and write halves.

I think it would make sense to start with a single `abort` method equivalent to calling both `abortReading` and `abortWriting`, since in practice this is what most applications want anyways, and then consider adding `abortReading` and `abortWriting` if there are web developers who really want that.

**Comment by steveanton** [comment]
I don't have a strong opinion to either keep or remove `abortReading`/`abortWriting`, but I think adding the `abort` method for the common case makes sense.

**Comment by alvestrand** [comment]
Most developers want just a single close operation until they understand about the need for graceful close. When they understand graceful close, they want a separate abortwriting (or "I'm finished sending") method, and a different signal for "the connection is closed and you have everything" that is easily separable from "the connection is closed and you may or may not have lost something".

abortReading causes you to not know whether you got everything the other party sent, so abortReading and the naive close() method can easily be combined, I think.

**Comment by steveanton** [comment]
@alvestrand I think in the case of QUIC the graceful close facility is provided by the stream fin bit. `abortWriting` maps to a QUIC protocol feature which will throw away any pending data right away, so shouldn't be used for normal operation.

**Comment by yutakahirano** [comment]
ReadableStreamDefaultReader has [cancel](https://streams.spec.whatwg.org/#default-reader-cancel) method, and WritableStreamDefaultWrier has [abort](https://streams.spec.whatwg.org/#default-writer-abort) method (in addition to [close](https://streams.spec.whatwg.org/#ws-close) method).

My initial thought was to map cancel to STOP_SENDING, map close to FIN, map abort to nothing.

**Comment by yutakahirano** [comment]
Now we have

 - abort() mapped to RESET_STREAM
 - close() mapped to FIN

on outgoing streams, and

 - cancel() mapped to STOP_SENDING

on incoming streams.

@vasilvv can we close this?

**Comment by vasilvv** [comment]
I think we should keep both methods, and if HTTP/2 transport causes issues, we could deal with it at IETF level.  Closing this.
